config/base.webpack.config.js
Adds a trailing slash to fix the 404s we are seeing in prod
=> fixes path error on prod

.travis.yml, .travis/release.sh, .travis/release_stable.sh
refactors travis build process to better align with insights-dashboard build process.
=> cleaning up build process

src/App.scss, src/SmartComponents/Actions/ActionsOverview.js, src/SmartComponents/Actions/ViewActions.js, src/SmartComponents/Actions/_actions.scss
removes capitalization in url
adds 'Risk Actions' in the card header
adds specific page styling and class on `#root`
=> fixing capitalization and cleaning

package-lock.json, package.json, src/PresentationalComponents/RulesCard/RulesCard.js, src/SmartComponents/Actions/ListActions.js, src/SmartComponents/Actions/_actions.scss, src/SmartComponents/Rules/ListRules.js
Adding basis for list-actions page. Still needs filters and a systems table
=> adding list-actions page

src/SmartComponents/Actions/ListActions.js
=> adding title to listActions page

src/SmartComponents/Actions/ListActions.js
I am guilty of not jumping into a pr, #39, and am now paying for the pony. Timey whimey component things are exciting especially when we're doing data processing  in the component, the more permanent fix is gonna be moving most of this logic into actions...
=> Prevents undefined prop error  in listactions component

package.json
=> Adds license,author,repo to package.json

package-lock.json, package.json
pf-core 1.14.0 still jacks everything up 😏
=> Update deps that don't jack anything up 😬 👍🏽

src/AppActions.js, src/SmartComponents/Rules/ListRules.js
but first we need https://github.com/RedHatInsights/insights-advisor-api/issues/90 (https://projects.engineering.redhat.com/browse/RHIADVISOR-217) resolved
related prs we also neeeeeed:
https://github.com/RedHatInsights/insights-advisor-api/pull/87
ok I lied above, don't need issue 90 resolved, will just fake it till data is present...
This gives RHIADVISOR-207 and each of its subtasks are given a little bitta love.. doesn't close any one issue... completely... yet...
the two TODOS this work adds, 
* implement pagination properly
* remove the randomly generated numbers
=> Adds api support to listrules

package-lock.json, package.json
cuz https://github.com/RedHatInsights/insights-frontend-components/pull/112 happened we can now update a few more deps
=> Update deps for ☀️🌮

package-lock.json, src/SmartComponents/Actions/ViewActions.js, src/SmartComponents/Rules/ListRules.js
And a little cleanup to listrules
package.json wanted to be update, who am I to refuse it? 🤷‍♂️ 
PS: not much changes again, this work incurs the same unpayable (at the moment) tech debt as the last component
=> Adds api support to viewactions component

package-lock.json, package.json, src/Store/index.js
Merge after https://github.com/RedHatInsights/insights-frontend-components/pull/125
=> Use redux registry from frontend components

src/Utilities/Api.js
So https://github.com/RedHatInsights/insights-advisor-api/pull/96 kinda messed us up here in consuming the api... this pr looks to right that... cept it doesn't quite work yet
=> Adds x-rh header to api

src/SmartComponents/Rules/ListRules.js
Does a little bitta work on RHIADVISOR-209
You'll notice there setting the page can be a little difficult, this isn't an issue with this work, just the way the component is built... it ought to have a bitta `debounce`... something to look into in the future...
=> Listrules support api pagination

src/SmartComponents/Actions/ViewActions.js
~~Does NOT add filtering/searching, in fact this kinda breaks it, restricts it to only whats presently visible to the user~~ was thinkin of the wrong view, we don't do that here... yet... 
hey its kinda like #60 all over again :thinking:
=> Adds pagination to viewactions component

config/spandx.config.js, src/AppConstants.js
This presently breaks dev api calls
=> Reconfigures api to support production routes

src/PresentationalComponents/RulesCard/RulesCard.js, src/SmartComponents/Actions/ListActions.js, src/SmartComponents/Actions/ViewActions.js, src/SmartComponents/Rules/ListRules.js
* https://github.com/RedHatInsights/insights-advisor-api/pull/87
* https://github.com/RedHatInsights/insights-advisor-api/pull/98
=> Adds missing attributes impact, likelihood

README.md, src/AppConstants.js
TODO: future nicety to make this easier, use .env
=> Set base url set to run in production by default

src/AppActions.js
Nothing changes, which is always nice <3
LESS CODE IS MORE!! <3
=> DRY actions to use async await as per dank's request <3

src/SmartComponents/Actions/ActionsOverview.js, src/SmartComponents/Actions/ViewActions.js, src/SmartComponents/Rules/ListRules.js
Refactoring out a bad pattern.
=> Array.map returns an array, no need to create one and push

.babelrc, package.json
=> Adds babel async plugin to support iaf api actions

src/AppActions.js
=> Restores api support for headers and options

config/spandx.config.js
=> Update apps host url

src/SmartComponents/Actions/ActionsOverview.js
=> Ends up we need to display reports not rules

package-lock.json, package.json
I know it seems like we've been doing this a lot lately... but we gotta do it again else be without global notification component!!!
=> Updates deps, adds global notification component 

src/SmartComponents/Actions/ViewActions.js
If the data in the list doesn't show up, it might be that the api hasn't updated yet, but check the network tab and you'll notice it lines up just okie dokie with https://github.com/RedHatInsights/insights-advisor-api/pull/120#issuecomment-438731447
=> Ensures our bar chart filtering of the rule list behaves expectedly

package-lock.json, package.json
=> Updates deps

src/SmartComponents/Actions/ListActions.js
fixes https://projects.engineering.redhat.com/browse/RHIADVISOR-307
Bah, don't really want to wait for tags any longer, will do another pr when they're available...
=> Adds kba to rule page, refactors as per latest mocks

package-lock.json, package.json, src/SmartComponents/Actions/ListActions.js
Note that at this point Remediations only has API deployed in CI so CI is the only environment where a remediation creation will actually work.
=> add Remediation support (via hot-loaded RemediationWizard)

package-lock.json, package.json
https://github.com/reduxjs/react-redux/releases
gotta reconfigure us to use contexts all over da place
=> Rollback react-redux update, it requires more work to get working

config/base.webpack.config.js, config/base.webpack.plugins.js, package-lock.json, package.json, src/App.scss, src/PresentationalComponents/Charts/ActionsOverviewDonut.js, src/SmartComponents/Actions/ActionsOverview.js
Donut? Doughnut? 
* mousing over the legend (or chart) does not slightly enlarge the doughnut (totally possible I believe... just passing an `onMouseover` event  to the ChartLegend.events.... something to look into)
* label is not in donut center, this is tricky, [pf4 pie chart fixes the size of the chart and label and overlays the latter](https://patternfly-react.surge.sh/patternfly-4/components/donutchart#ChartLabel)
can work on all the bummers, but wanted to get this thrown out there first, cuz peeps be complain' bout da lookz of present state 💃 🦂
=> Refactors dashboard doughnut to use pf4 widget

src/SmartComponents/Actions/ListActions.js
https://github.com/RedHatInsights/insights-advisor-api/pull/145
=> Adds tags list to rule view

src/PresentationalComponents/Cards/ExpandableRulesCard.js, src/SmartComponents/Actions/ListActions.js, src/SmartComponents/Actions/ViewActions.js, src/SmartComponents/Rules/ListRules.js
https://github.com/RedHatInsights/insights-advisor-api/pull/142
=> Change .ansible attribute to .has_playbook as per #142 in api repo

src/SmartComponents/Actions/ActionsOverview.js
=> Dan wanted this to happen on this day 🙇🏾‍♀️🍲👩🏾‍🚒👾

src/SmartComponents/Actions/ViewActions.js
Nothing changes, cept each dashboard chart does what it's supposed to
=> Impacting flag only valid when filtering by category

src/AppConstants.js, src/PresentationalComponents/Cards/ExpandableRulesCard.js, src/PresentationalComponents/Inventory/InventoryRuleList.js, src/SmartComponents/Actions/ViewActions.js
=> This endpoint also changed, ensures we correctly fetch rules on systems

src/PresentationalComponents/Inventory/Inventory.js
[waiting on this to show up in chrome before we merge](https://github.com/RedHatInsights/insights-frontend-components/pull/168)
=> Adds pagination/filtering to inventory table

src/SmartComponents/Actions/ListActions.js
Woops, this api change went unnoticed :worried:
=> Inv component needs array of strings, returned by /systems on host_ids

package-lock.json, package.json, src/PresentationalComponents/Loading/Failed.js, src/PresentationalComponents/Loading/Loading.js, src/SmartComponents/Actions/ListActions.js, src/SmartComponents/Actions/ViewActions.js
To better align ourselves with IFC adding the failed component (displays when there is an issue fetching data in a list) and updates the loading component to use react-content-loader
=> Updates loading component adds Failed component

package-lock.json, package.json, src/PresentationalComponents/Cards/RulesCard.js, src/SmartComponents/Actions/ListActions.js
Similar to https://github.com/RedHatInsights/insights-frontend-components/pull/209
=> Ensure valid non-null input for reactmarkdown

src/PresentationalComponents/Charts/ActionsOverviewDonut.js
=> Cleans up donut chart tspan errors

package-lock.json, src/PresentationalComponents/Breadcrumbs/_breadcrumbs.scss, src/SmartComponents/Actions/ListActions.js, src/SmartComponents/Actions/ViewActions.js
=> Correct spacing around breadcrumbs

src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js, src/SmartComponents/Actions/ListActions.js, src/SmartComponents/Actions/ViewActions.js
Also has an options parameter that should move #148 forward.
=> Refactor breadcrumbs to make them match based

src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js, src/SmartComponents/Actions/ListActions.js, src/SmartComponents/Actions/ViewActions.js
Fixed `undefined` errors from previous PR and added support for `match.params.inventoryId`
=> Refactor Breadcrumbs

src/SmartComponents/Actions/ActionsOverview.js
Fixes RHIADVISOR-378.
Before:
After:
Before:
After:
=> Adjusts responsive breakpoints/sizes for the Donut

src/AppReducer.js, src/PresentationalComponents/Inventory/InventoryDetails.js
=> BU directed the removal of vulnerabilities tab

package-lock.json, package.json
https://github.com/RedHatInsights/insights-frontend-components/pull/263
Also adds https://github.com/RedHatInsights/insights-frontend-components/pull/262
=> Applies ICF #263

src/SmartComponents/Rules/ListRules.js
[ok so the bad news is we suffer from this](https://github.com/facebook/react/issues/6779)
the good news is that fake warning aside this works like a 🥩🐝  so imma err on the side of merge it
=> Adds filtering rule list by those that have impacted systems

src/PresentationalComponents/Charts/ActionsOverviewDonut.js, src/PresentationalComponents/Charts/ActionsOverviewDonut.scss, src/SmartComponents/Actions/ActionsOverview.js
Fixes https://projects.engineering.redhat.com/browse/RHIADVISOR-378
Fixes https://projects.engineering.redhat.com/browse/RHIADVISOR-371
=> Forces fixed victory container height for donut so we don't 😱🍩

package-lock.json, package.json
fixes https://projects.engineering.redhat.com/browse/RHIADVISOR-400
=> RHIADVISOR-400 fix inv rule sort, active rule always on top

src/Routes.js, src/index.html
In support of https://github.com/RedHatInsights/insights-chrome/pull/147
=> Update page layout to support chrome pf v1.0.175

src/SmartComponents/Actions/ViewActions.js, src/SmartComponents/Rules/ListRules.js
Fixes per https://github.com/RedHatInsights/insights-frontend-components/pull/248 update.
Will convert to https://github.com/RedHatInsights/insights-frontend-components/pull/282 once merged.
Fixes RHIADVISOR-380
=> Update pagination to use debounce

src/SmartComponents/Actions/ViewActions.js
=> Ux feedback,"systems" to "systems exposed" 

src/index.html
as per https://github.com/RedHatInsights/insights-frontend-starter-app/pull/55
if you don't see it... try bouncing the server and incognito 
cc @jkinlaw
=> insights-chrome change warrants index cleanup

src/PresentationalComponents/Filters/Filters.js
Fixes #193
matching values is tough 🤗
=> Can't unselect a filter if more than one are selected #193

src/SmartComponents/Rules/ListRules.js
fixes https://projects.engineering.redhat.com/browse/RHIADVISOR-437
Here's a fix till we get clarification on how to handle other types of systems, this will stop the blow up.
**Note: you will see the battery warning as we'll be passing a zero, which makes a gray unknown battery, but again, just a warning, doesn't blow anything up**
=> RHIADVISOR-437 - If the system type is not of type rhel, we used to blow up, now we dont😋

src/SmartComponents/Actions/ViewActions.js
=> Link needs an encapsulating element to append an `a` onto

src/SmartComponents/Actions/ViewActions.js
=> Adds `impacting` checkbox to actions table

src/SmartComponents/Actions/ViewActions.js
fixes https://projects.engineering.redhat.com/browse/RHIADVISOR-458
=> Centers action table cells that have icons

src/PresentationalComponents/RulesTable/RulesTable.js
fixes https://projects.engineering.redhat.com/browse/RHIADVISOR-451
~~side note, this needs https://github.com/RedHatInsights/insights-advisor-api/pull/191/ pushed to prod before we can play around with this  this pr kinda broke things, so we're waiting for another one before this can be merged~~
So this works in ci, kinda mostly
=> Adds sorting for systems count and ansible columns to actions table

src/PresentationalComponents/RulesTable/RulesTable.js
fixes https://projects.engineering.redhat.com/browse/RHIADVISOR-469
=> Toggling impacting stays sane when on a page !== 1

package-lock.json, src/AppConstants.js, src/PresentationalComponents/RuleDetails/RuleDetails.js, src/PresentationalComponents/RuleDetails/_RuleDetails.scss, src/SmartComponents/Actions/ViewActions.js
Moving linking the list of tags to a separate PR, PR link coming soon.
=> Add RuleDetails component

src/SmartComponents/Actions/ListActions.js
=> Fix capitalization of List Action page titles

src/PresentationalComponents/Filters/Filters.js
=> A filter should only ever be set if one exists (to be set)

.babelrc
fixes https://projects.engineering.redhat.com/browse/RHIADVISOR-496
for the curious https://babeljs.io/docs/en/babel-preset-env#shippedproposals
=> Swaps .flat for flatten, ff60.5.2 compatability, no visual changes

src/PresentationalComponents/RulesTable/RulesTable.js
=> Sorting happens by column index, not by those that are sorting

.babelrc, src/PresentationalComponents/RulesTable/RulesTable.js
Undoes https://github.com/RedHatInsights/insights-advisor-frontend/pull/228 AND USES LODASH :godmode:
=> Gonna just rely on lodash to flatten the rules array

README.md, config/base.webpack.plugins.js, config/spandx.config.js, config/webpack.common.js, src/App.js, src/Routes.js, src/entry-dev.js, src/entry.js, src/index.html
as per https://github.com/RedHatInsights/landing-page-frontend/commit/853ec2f75702baf70591c24ca1c0858b730b9723
note, from browser console run `localStorage.setItem('cs-app', 'insights');`
=> Convert all paths to the cloud.redhat.com paths

src/entry-dev.js, src/entry.js
from https://docs.google.com/document/d/1Ku_MELkCjhY5ggwyQ7aawftiLMoKlqdpdsRPPSr8nyI/edit?ts=5c8fb40a#
=> Update app to support beta branch release as per cloud migration guide

package-lock.json, package.json
includes https://github.com/RedHatInsights/insights-frontend-components/pull/357
ignore the kba issues, working that still, but look EVERYTHING ELSE IS WORKING 🤤
=> Updates inventory to version that has the correct (most current) api url

src/PresentationalComponents/RuleDetails/RuleDetails.js, src/Utilities/Api.js
fixes https://projects.engineering.redhat.com/browse/RHIADVISOR-502
=> Fixes broken kba links does away with unnecessary common header

src/AppConstants.js
edit:
of course my commit message has a spelling error 🙄
=> Updating "Critcal" to "Critical"

package-lock.json, package.json
Includes https://projects.engineering.redhat.com/browse/RHCLOUD-503
=> PRO-STABLE pr, to that includes 503 fix

package-lock.json, package.json
=> Dupe of pr#248 for prod-beta

src/PresentationalComponents/Charts/ActionsOverviewDonut.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-556
No visual changes to donut
=> Removes a few unnecessary divs, adds label to donut legend

package-lock.json, package.json
Includes https://projects.engineering.redhat.com/browse/RHCLOUD-503
this is the pr for master MASTER not prod-stable/beta 
(s why we're tagging yah @kensible)
=> Discrepancy in Ansible support indication between insights and inventory

package-lock.json, package.json
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-402
includes https://github.com/RedHatInsights/insights-frontend-components/pull/364
=> Fixes rule resolution content consolidated to single line

src/PresentationalComponents/RulesTable/RulesTable.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-526
=> Reword show/hide reports to enable/disable rule, attribute not changing😢

.travis/custom_release.sh
Stolen from: https://github.com/RedHatInsights/insights-inventory-frontend/pull/76
@dkuc wanta get your thoughts on this
=> Automatically release beta when we push to master

README.md
Lemme know if you were thinking of more or less ya'll
=> Update readme to detail IF branches/deploy process

src/SmartComponents/Actions/ViewActions.js
this is my fault, lets never speak of it again.
=> playbook_count is a num, not an array, fixes the remediation button

.travis/custom_release.sh
=> Update release process to work for all branches (sans prod)

src/PresentationalComponents/RulesTable/RulesTable.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-605
So we did a few things here...
* jumped to pf4 pagination
* support offset/limit 
* support new api response format
* well i guess that's it
=> Supports limit/offset and new api response format

config/webpack.common.js, src/Utilities/getBaseName.js, src/entry-dev.js, src/entry.js, src/index.html
The biggest issue here was the esi:include was looking for src="apps/chrome...
This needs to be src="/apps/chrome...
Other refactoring changes pulled in as well
=> Resync with starter application Cloud fixes/refactor

src/SmartComponents/Actions/ViewActions.js
as directed here: https://docs.google.com/spreadsheets/d/1xbzvLhRUd0o27CIk1MOQWbpYMpJXktx3HUpI2MAjpk4/edit?ts=5cacabb9#gid=2076529373
=> "Hosts" to "Systems" as per ux

src/PresentationalComponents/RuleDetails/RuleDetails.js
fixes https://docs.google.com/spreadsheets/d/1xbzvLhRUd0o27CIk1MOQWbpYMpJXktx3HUpI2MAjpk4/edit?ts=5cacabb9#gid=967324608&range=11:11
=> Remove "other rules related to" (no topics for summit)

src/PresentationalComponents/RuleDetails/RuleDetails.js
=> The risk of change should be stacked like total risk above

src/PresentationalComponents/Inventory/Inventory.js, src/SmartComponents/Overview/Details.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-722
=> Relocates remediate with ansible button to inside inv table

src/PresentationalComponents/Filters/Filters.js, src/PresentationalComponents/MessageState/MessageState.js, src/PresentationalComponents/RulesTable/RulesTable.js, src/SmartComponents/Overview/List.js
~We look finish, but need finish two pieces before this is g2g~
~* get the filtering interaction down solid (when clicking the link)~
~* center the message state, this is tricky cuz we are an action table~
=> Just a wip for the sake of wipping

src/SmartComponents/Overview/Dashboard.js
=> Change empty state text as per ux guidance 

src/PresentationalComponents/RuleDetails/RuleDetails.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-976
=> Bolds impact and likelihood

src/PresentationalComponents/RulesTable/RulesTable.js
=> Increase cellwidth of added column 

src/App.scss
=> Adds react core styles to insights app

package-lock.json, package.json
temporary fix for https://projects.engineering.redhat.com/browse/RHCLOUD-1011
=> Roll back react-table update in order to fix styling issue

src/PresentationalComponents/RuleDetails/RuleDetails.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-1001
=> KBA link opens in new tab/window

package-lock.json, package.json
includes https://github.com/RedHatInsights/insights-frontend-components/pull/412
=> Removes external icon on reports, broken likely react-dom prod version

src/index.html
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-1157
=> Removes RHCSS from title

package-lock.json, package.json
fixes bug where remediations wizard notification does not work
=> bump ifc to 3.41.48

src/PresentationalComponents/RuleDetails/RuleDetails.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-1195
=> Swaps kba fetch for  url build off node_id, Access handles the redirect

src/index.html
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-1169
=> Update title per BU guidance 

package-lock.json, package.json, src/App.js, src/App.scss, src/AppReducer.js, src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js, src/PresentationalComponents/Charts/SummaryChart/SummaryChart.scss, src/PresentationalComponents/Charts/SummaryChart/SummaryChartItem.js, src/PresentationalComponents/Filters/Filters.js, src/PresentationalComponents/Inventory/Inventory.js, src/PresentationalComponents/Inventory/InventoryDetails.js, src/PresentationalComponents/RuleDetails/RuleDetails.js, src/PresentationalComponents/RulesTable/RulesTable.js, src/SmartComponents/Overview/Dashboard.js, src/SmartComponents/Overview/Details.js, src/SmartComponents/Overview/Details.scss, src/SmartComponents/Overview/List.js, src/SmartComponents/Overview/Overview.js, src/SmartComponents/Rules/ListRules.js, src/SmartComponents/Rules/Rules.js, src/Store/index.js, src/entry-dev.js, src/entry.js
This is how we should start using FEC, they are moving to brand new repo - https://github.com/RedHatInsights/frontend-components
=> Use new frontend components monrepo packages

src/PresentationalComponents/RulesTable/RulesTable.js
also we want impact to be true by default, its a wonder this got by for so long
=> onSort makes a FetchRules call, no need have a second one in didmount

package-lock.json, package.json
includes https://github.com/RedHatInsights/frontend-components/pull/35 👈  also has a few ss of this work in action
=> White-space pre-wrap fixes our text overflow issues for pre code blocks

src/PresentationalComponents/RulesTable/RulesTable.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-1055
~~waiting on https://github.com/RedHatInsights/insights-advisor-api/pull/261 to be merged, make it up to prod~~
=> Adds sorting by description, removes expanded detail loading text

src/PresentationalComponents/Charts/OverviewDonut.js, src/PresentationalComponents/Charts/SummaryChart/SummaryChartItem.js, src/PresentationalComponents/RulesTable/RulesTable.js
=> Fixes donut semi colon, adds comma for system counts

src/PresentationalComponents/Filters/Filters.js, src/PresentationalComponents/RulesTable/RulesTable.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-1520
=> Adds pagination bar to rule toolbar, always farthest right

config/spandx.config.js
=> Migrate from old non-prod environments for Cloud to new

package-lock.json, package.json
includes https://github.com/RedHatInsights/frontend-components/pull/58
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1721265
=> Ensures correct sanitization of >, <, & (system details)

package-lock.json, package.json
includes https://github.com/RedHatInsights/frontend-components/pull/60
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-1612
see https://github.com/RedHatInsights/frontend-components/pull/60#issue-289440329 for gif and ux approval
=> Do not block report rendering on article search

src/PresentationalComponents/Filters/FilterChips.js, src/PresentationalComponents/Filters/Filters.js, src/PresentationalComponents/RulesTable/RulesTable.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-1550
=> Display "filter chips" to show users actively selected filters

src/PresentationalComponents/Filters/Filters.js, src/PresentationalComponents/RulesTable/RulesTable.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-1320
ATM this does nothing more than look pretty
we're a wip awaiting api work being done here https://github.com/RedHatInsights/insights-advisor-api/pull/257
=> Allen makes a download master csv export button

src/PresentationalComponents/RuleDetails/RuleDetails.js
Nothing changes, cept the code just a lil
=> Maintains no state, doesn't need to be a class, refactor rule details

src/PresentationalComponents/Charts/OverviewDonut.js, src/PresentationalComponents/Charts/SummaryChart/SummaryChartItem.js, src/PresentationalComponents/Filters/FilterChips.js, src/PresentationalComponents/Filters/Filters.js
=> Refactors a number of  class components to be functional components 🌮 

.eslintrc.yml, package-lock.json, package.json, src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js
Rewrites breadcrumbs component using  hooks
###Still works
=> Taking some time to cleanup: Breadcrumbs

src/PresentationalComponents/RulesTable/RulesTable.js
=> Adds hacky cross browser blob download prompt for data export

src/PresentationalComponents/RulesTable/RulesTable.js, src/Utilities/Debounce.js
~SO this thing has a super neat problem in that debounce doesn't work, sure yes yes there is a delay in input BUT watching network tab we  see one more call than should be happening... meaning that the previous debounce instance isn't being canceled.  if we remove the setOffset MAGICALLY we only get one call (but the offset doesn't display correctly) whenever we run that setOffset we're re-rendering the component and debounce is losing that it was ever called before~
with our new fancy debounce function, this works real nice, like nothing ever changed!
well ok so debounce now works, before it didn't so much, also this fixes the pagination red box thing...
=> Refactor rulestable to functional component using hooks

package-lock.json, package.json
includes https://github.com/RedHatInsights/frontend-components/pull/80
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-1431
=> All report details links open in new tab

src/AppConstants.js
Aligns constants with mock here: https://marvelapp.com/i4441ie/screen/58398655
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-1822
=> Update impact, likelihood, riskofchange, totalrisk constant values

package-lock.json, package.json
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-1547
includes https://github.com/RedHatInsights/frontend-components/pull/78
includes https://github.com/RedHatInsights/frontend-components/pull/81/
=>  Hides reports if show_satellite_managed is false

src/AppConstants.js
Now we use other words better aligned with roc states
=> Update risk of change constants

src/App.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-1194
=> Ensures correct lnav is active on page reload, based on app location

src/AppConstants.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-1823
depends on https://projects.engineering.redhat.com/browse/RHCLOUD-1856
ready to go! ~~all we need is https://github.com/RedHatInsights/insights-advisor-api/pull/287 to be merge-ah-rooed~~
=> Adds risk of change to filter options

src/AppConstants.js
=> Correct risk of change filter urlParam is res_risk, adds roc filtering

src/AppActions.js, src/SmartComponents/Overview/Dashboard.js, src/SmartComponents/Rules/Details.js, src/SmartComponents/Rules/ListRules.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-1953
makes it so we don't have to worry about this for any future calls
=> Api calls need to do an auth check, this consolidates em in one place

src/App.js
As soon as we merge/push this, can merge the work in cloud-services-config, removing overview as the default selected
yeah, we merge this work, then https://github.com/RedHatInsights/cloud-services-config/pull/25
=> Highlight app nav based on url, both rules and overview

src/PresentationalComponents/RulesTable/RulesTable.js
includes https://github.com/patternfly/patternfly-react/pull/2639
=> Fix page offset bug, simplify ruletable pagination

src/PresentationalComponents/RulesTable/RulesTable.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-410
When you throw a url like `https://ci.foo.redhat.com:1337/insights/rules?impacting=false&reports_shown=true&total_risk=4,3` into the browser (already logged in) you go to a page that looks like this
as yah add more filters the url is updated to reflect the selected filters
navigating forwards/backwards/sidewards throughout the app doesn't do anything hokey
also, if you visit `/rules` with NO filters, whatever is in the filters state is pushed in the url
=> Rulestable on init informs state filter( is updated when changes occur)

src/PresentationalComponents/RulesTable/RulesTable.js
so now if you select "All"  from rule status and refresh the page, it works as expected
=> Fixes rule status-all not correctly reading from the url on table refresh

src/PresentationalComponents/RulesTable/RulesTable.js
mocks here have it https://marvelapp.com/i4441ie/screen/58398662 so lets add it!
=> Adds export icon to export actions

src/PresentationalComponents/TopicCard/TopicCard.js, src/SmartComponents/Topics/Details.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-2106
=> Reconfigures topic filter to be set on card rather than in component

locales/data.json, locales/translations.json, src/Messages.js, src/SmartComponents/Topics/List.js
=> Corrects topics empty state text

config/spandx.config.js
=> New CNAMES for pre prod environments

locales/data.json, locales/translations.json, src/Messages.js, src/PresentationalComponents/TopicCard/TopicCard.js, src/SmartComponents/Topics/Details.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-2303
=> Adds "featured" word to replace "recommended"  (for highlighting topics)

package-lock.json, package.json
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-2340
=> Updates inv-insights ansible icons

package-lock.json, package.json, src/PresentationalComponents/Charts/OverviewDonut.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-2338
=> Updates pf-charts to version 5, brings better tooltips

src/PresentationalComponents/RulesTable/RulesTable.js, src/PresentationalComponents/TopicCard/TopicCard.js, src/SmartComponents/Topics/Details.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-2367
=> Topic details to support setFilters, replace search query 

src/SmartComponents/Overview/Dashboard.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-2216
=> Updates "Getting Started" Overview url

src/App.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-2123
to work, requires https://github.com/RedHatInsights/insights-chrome/pull/383/ to be promoted from ci-beta 
☝️ good news is, without this nothing is broken, so we can merge this w/e
=>     click on nav root, redirects user to nav root

locales/data.json, locales/translations.json, src/Messages.js, src/PresentationalComponents/Inventory/Inventory.js, src/SmartComponents/Rules/Details.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-2069
=> Adds bulk select to rule details inventory table (bulk bulk bulk bulk)

locales/data.json, locales/translations.json, src/Messages.js, src/PresentationalComponents/RuleDetails/RuleDetails.js, src/SmartComponents/Rules/Details.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-546
=> Adds related topics list to rule detail component

src/PresentationalComponents/Filters/FilterChips.js
=> Increases the number of visible chip groups before collapse to 4 (from 3) 

package-lock.json, package.json, src/PresentationalComponents/RulesTable/RulesTable.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-2342
includes https://github.com/patternfly/patternfly-react/pull/3040/files
=> Fixes rules table ansible column on collapse 

locales/data.json, locales/translations.json, src/Messages.js
=> Fix broken translation line breaks

src/PresentationalComponents/RuleDetails/RuleDetails.js, src/PresentationalComponents/RuleDetails/_RuleDetails.scss, src/Utilities/BarDividedList.js, src/Utilities/_BarDividedList.scss
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-2612
=> Adds highlight card for rule detail topics

locales/data.json, locales/translations.json, src/Messages.js, src/PresentationalComponents/RuleDetails/_RuleDetails.scss
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-2654
=> Update rule detail topic card as per ux feedback

src/SmartComponents/Overview/Overview.js, src/SmartComponents/Rules/Rules.js, src/SmartComponents/Topics/Topics.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-2679
=> Ensures crazy routes inside of our allowed ones redirect to root

src/PresentationalComponents/RulesTable/RulesTable.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-2678
=> Preserves sorting when hiding or enabling a rule

package-lock.json, package.json
includes https://github.com/RedHatInsights/frontend-components/pull/205
=> Updates inv-insights 

src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js, src/PresentationalComponents/RuleDetails/RuleDetails.js, src/Routes.js
=> Fix app catchall, topics system count (hidden), exhaust deps warning

src/PresentationalComponents/MessageState/MessageState.js, src/PresentationalComponents/RulesTable/RulesTable.js
=> Updates empty state check color, ansible check icon

locales/data.json, locales/translations.json, src/Messages.js, src/PresentationalComponents/Charts/SummaryChart/SummaryChart.scss, src/PresentationalComponents/Charts/SummaryChart/SummaryChartItem.js, src/PresentationalComponents/MessageState/MessageState.js, src/SmartComponents/Overview/Dashboard.js, src/SmartComponents/Overview/Dashboard.scss
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-2757
=> Fix ux bugs on dashboard

locales/data.json, locales/translations.json, src/Messages.js, src/PresentationalComponents/RulesTable/RulesTable.js
similar to https://github.com/RedHatInsights/frontend-components/pull/216
=> Adds 'No' string when there is not an ansible playbook available

src/PresentationalComponents/SystemsTable/SystemsTable.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-2894
=> Updates system table to use primary toolbar

src/SmartComponents/Rules/Details.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-2929
=> Bulk select checkbox now toggles selectall/none

src/PresentationalComponents/RulesTable/RulesTable.js
This PR fixes problem with rememered values when switching filter types.
=> Add keys to filter so they render correctly

src/PresentationalComponents/RulesTable/RulesTable.js, src/PresentationalComponents/SystemsTable/SystemsTable.js
N then we'll update the inv-insights app!
=> Adds key to systems table text filter

locales/data.json, locales/translations.json, src/AppActions.js, src/AppConstants.js, src/AppReducer.js, src/Messages.js, src/PresentationalComponents/Modals/DisableRule.js, src/PresentationalComponents/RulesTable/RulesTable.js, src/SmartComponents/Rules/Details.js, src/SmartComponents/Rules/Details.scss, src/Utilities/Api.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-2982
=> Add disable rule message state to rule detail component

src/App.js
sort of almost fixes https://projects.engineering.redhat.com/browse/RHCLOUD-2926
=> Refactors app.js to be functional component

src/PresentationalComponents/TopicsAdminTable/TopicsAdminTable.js, src/SmartComponents/Topics/Topics.js
As this is foundational work for RHCLOUD-2988 that will not be visible to external users, gonna merge this so @LI0131 can start **FRESH FRESH** 👶 
supports but doesn't fix https://projects.engineering.redhat.com/browse/RHCLOUD-2988
=> Adds topic admin component and add/edit modal 

src/PresentationalComponents/Modals/DisableRule.js, src/SmartComponents/Rules/Details.js, src/SmartComponents/Rules/Details.scss
as per https://marvelapp.com/i4441ie/screen/62092193
=> Rule detail disabled notification is now a card (not a fake alert)

locales/data.json, locales/translations.json, src/Messages.js, src/PresentationalComponents/Modals/DisableRule.js, src/PresentationalComponents/Modals/ViewHostAcks.js, src/PresentationalComponents/RuleDetails/RuleDetails.js, src/PresentationalComponents/RuleDetails/_RuleDetails.scss, src/PresentationalComponents/RulesTable/RulesTable.js, src/SmartComponents/Rules/Details.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-2981
**TODO:**
* ~exchange impacted ack rule count with existing *6* (blocked) https://github.com/RedHatInsights/insights-advisor-api/pull/381 to be merged~
* ~updated to use filtered hostack call (blocked, but this wont stop us from merging) just waiting for api promotion so this can be merged https://github.com/RedHatInsights/insights-advisor-api/pull/387~
=> Adds host ack support to rules table

src/SmartComponents/Rules/Details.js
Nothing changes, just one less call
=> GET hostacks no longer required by rule details (s on the details call)

src/PresentationalComponents/Modals/ViewHostAcks.js
Before: blank modal to populated table
After: loading table to populated table
=> Adds loading component to ack hosts modal

src/PresentationalComponents/Modals/ViewHostAcks.js, src/SmartComponents/Rules/Details.js
Before we we're only acting on 10, now we'll act on em all (up to 1000)
=> Ensures all acked hosts are fetched, up to 1000

src/PresentationalComponents/RuleDetails/RuleDetails.js, src/PresentationalComponents/RuleDetails/_RuleDetails.scss
=> Improve rule details small screen performance 

src/SmartComponents/Rules/Details.js
=> Upon enabling a host, on modal exit, update rule detail as this is the source of the hostack count

src/PresentationalComponents/RuleDetails/RuleDetails.js, src/PresentationalComponents/RuleDetails/_RuleDetails.scss
=> Ensure we don't blow up the page with too many topics

src/PresentationalComponents/Modals/ViewHostAcks.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-3743
=> View hosts modal defaults to display_name fallback system_uuid

src/PresentationalComponents/Modals/DisableRule.js, src/PresentationalComponents/RuleDetails/RuleDetails.js, src/PresentationalComponents/RuleRating/RuleRating.js, src/SmartComponents/Rules/Details.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-3747
=> Await setAck so the afterFn doesn't fire too soon

src/PresentationalComponents/RuleRating/RuleRating.js, src/SmartComponents/Rules/Details.js
fixes the issue where on refresh only 10 hosts were unacked with bulk actions
=> When hosts_acked_count changes, refetch the list of host acks 

src/PresentationalComponents/RulesTable/RulesTable.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-3546
all behavior remains the same (description behaves identical to the others), fixes the bug where 'Clear all' from a topics details page does not clear all 👍 💃
=> Rule table description is now a filter chip, fixes Topic clear all bug

locales/data.json, locales/translations.json, package-lock.json, src/AppConstants.js, src/Messages.js, src/PresentationalComponents/RulesTable/RulesTable.js, src/PresentationalComponents/RulesTable/_RulesTable.scss
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-3734
s a really sweet pr 🍫
Thanos would be proud of the balance in this pr 💪 (aww 💩  lost a line)
=> Adds icons to filter labels, restores translated labels

src/PresentationalComponents/Inventory/InventoryDetails.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-3823
=> Refactors inv details component to be functional

src/PresentationalComponents/SystemsTable/SystemsTable.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-3827
=> Adds filter chip to systems table

src/PresentationalComponents/Charts/SummaryChart/SummaryChart.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-3841
=> Severity chart vars are translated constants, gotta dig to pull em out

src/PresentationalComponents/RulesTable/RulesTable.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-3842
=> Restores functionality of "include disabled rules" button

src/PresentationalComponents/RuleRating/RuleRating.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-3870
=> Adds explicit labels to rating buttons

src/PresentationalComponents/Inventory/Inventory.js
uses https://github.com/RedHatInsights/frontend-components/pull/317
=> Fixes inventory table bottom pagination 

src/PresentationalComponents/RulesTable/RulesTable.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-3869
=> Filtering by disabled rules auto sets impacting to false

src/PresentationalComponents/Inventory/Inventory.js
=> Per page for inv-table also persists across inv-table changes 🌮

src/PresentationalComponents/Charts/SummaryChart/SummaryChart.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-3921
=> Minor UI tweak to improve automation

src/PresentationalComponents/Modals/AddEditTopic.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-3971
works just fine everywhere else as well 🦊
=> Ends up safari doesn't like to put without a slash at the end 👨‍🏫🤷‍♀️

src/PresentationalComponents/RulesTable/RulesTable.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-4026
you can clear this filter chip, it'll leave yah seeing all rules (enabled and disabled), clearing the filterchip will leave yah with only the enabled rules (our default state)
=> Show filter chip for rule status, absent filter = all

src/PresentationalComponents/Inventory/Inventory.js
Reverts RedHatInsights/insights-advisor-frontend#541
=> Revert "Fix default page when going from inv detail"

src/AppActions.js, src/AppConstants.js, src/AppReducer.js, src/PresentationalComponents/Common/Tables.js, src/PresentationalComponents/RulesTable/RulesTable.js, src/PresentationalComponents/SystemsTable/SystemsTable.js
tl;dr systems table now supports url params, maintains state when not in use, updates url params when table filters change, abstracts the similarities with rule table
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-3973
=> Adds statefulness to Systems table

src/PresentationalComponents/RuleLabels/_RuleLabels.scss, src/PresentationalComponents/RulesTable/RulesTable.js
=> Fixes incident label color in prod, filtering by ansible via url bug

src/PresentationalComponents/RulesTable/RulesTable.js, src/PresentationalComponents/SystemsTable/SystemsTable.js
something probably changed somewhere and we didn't change with it
=> Bottom pagination was missing onPerpageSelect

src/PresentationalComponents/RulesTable/RulesTable.js, src/PresentationalComponents/SystemsTable/SystemsTable.js
=> Fixes  url parsed limit/offset, now numbers instead of string in array

src/PresentationalComponents/RulesTable/RulesTable.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-4598
=> No longer require fetchaction as rules are refetched on filter change

src/PresentationalComponents/SystemsTable/SystemsTable.js
now everyone should be playing along with tags
=> Followup to #561, adds tag support to systems table

locales/data.json, locales/translations.json, src/Messages.js, src/PresentationalComponents/TagsToolbar/TagsList.js, src/PresentationalComponents/TagsToolbar/_TagsToolbar.scss
as per https://ansible.slack.com/archives/CADT032B0/p1582893802295700?thread_ts=1582823771.258000&cid=CADT032B0
=> Adds state for no tags and reduces dropdown padding

src/AppActions.js, src/AppConstants.js, src/AppReducer.js, src/PresentationalComponents/Modals/DisableRule.js, src/SmartComponents/Rules/Details.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-4802
=> Reconfigures bulk acking to utilize POST response

src/PresentationalComponents/RulesTable/RulesTable.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-4958
=> Ensures whenever filters are modified, table offset is reset

src/PresentationalComponents/RulesTable/RulesTable.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-4958
=> Offset reset when filters modified 

src/PresentationalComponents/Modals/DisableRule.js
Gotta add this to however were previously acked
=> Hostack POST returns count of number hosts acked in call 

src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js
similar to https://github.com/RedHatInsights/insights-advisor-frontend/pull/577
=> Fix insights tabs breadcrumbs

src/SmartComponents/Rules/Details.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-4994
=> Fix an errant 'rule' 

src/AppActions.js, src/PresentationalComponents/Modals/DisableRule.js, src/SmartComponents/Rules/Details.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-5007
=> Adds tagging support to rec details page

locales/data.json, locales/translations.json, src/Messages.js, src/PresentationalComponents/TagsToolbar/TagsList.js, src/PresentationalComponents/TagsToolbar/TagsToolbar.js, src/PresentationalComponents/TagsToolbar/_TagsToolbar.scss
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-4994
cc @kybaker
=> Reconfigures tag dropdown to use select component

src/PresentationalComponents/RulesTable/RulesTable.js
What the title is trying to say is.... the .text filter value, on a debounce would overwrite initial filter values provided by ah url, (ie nav by url or weekly email)
This pr simplifies the filter setting n getting, ensures debounce function doesn't ruin our day.
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-5162
=> .text filter set timing avoids overwriting url values

src/PresentationalComponents/RulesTable/RulesTable.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-5162
=> .text filter set timing avoids overwriting url values (#586)

src/PresentationalComponents/RulesTable/RulesTable.js
fixes limit offset being incorrectly set
=> Ensures rec table loads every component init

src/App.js, src/Routes.js
fixes  https://projects.engineering.redhat.com/browse/RHCLOUD-5281
=> Ensures advisor query params aren't stripped on entry

src/PresentationalComponents/TagsToolbar/TagsToolbar.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-5387
=> Selectoption prefers to not be a child, so tooltip as child works

config/prod.webpack.config.js, package-lock.json, package.json
will cherrypick this from master-stable once merged
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-5511
=> Restores missing webpack image copy  action - for Dan 🌺🥰

package-lock.json, src/PresentationalComponents/SystemsTable/SystemsTable.js, src/PresentationalComponents/TagsToolbar/TagsToolbar.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-5581
mucho thanks to @dkuc for advocating this one 🙇
=> Fix system table dupe calls

src/AppReducer.js, src/PresentationalComponents/RulesTable/RulesTable.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-5692
=> Default rec table params include limit/offset 👈 set on clear all filters

src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-5850
=> Removes sentence casing from breadcrumbs

src/PresentationalComponents/ExecutiveReport/Download.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-5944
=> If we're loading the exec report, disable the button

src/AppReducer.js, src/PresentationalComponents/RulesTable/RulesTable.js, src/SmartComponents/Topics/Details.js
As per the request of one @robcwilliams
=> Swaps default rec sorting, publish_date, for total_risk

src/PresentationalComponents/ExecutiveReport/Download.js
here's what a report might look like with this change
[Advisor-Executive-Report--Mon,-20-Apr-2020-20 39 36-GMT.pdf](https://github.com/RedHatInsights/insights-advisor-frontend/files/4506051/Advisor-Executive-Report--Mon.-20-Apr-2020-20.39.36-GMT.pdf)
=> Utilizes compound sorting to return exec reports top 3 recs

src/PresentationalComponents/RulesTable/RulesTable.js
fixes https://projects.engineering.redhat.com/browse/RHIADVISOR-528
=> Rec table, remove search field when cleared by filter chips

src/AppReducer.js, src/PresentationalComponents/SystemsTable/SystemsTable.js
=> Use inventory when showing list of systems

src/SmartComponents/Topics/Details.js
=> Add TagToolbar component to Topics detail page

src/PresentationalComponents/RulesTable/RulesTable.js
=> Impacting no longer required local to rec table component

src/SmartComponents/InsightsTabs/InsightsTabs.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-6711
=> Persists cve alert status to session storage 

src/PresentationalComponents/SystemsTable/SystemsTable.js
there was a jira at one point, who knows where it is now
=> Adds sorting to system table hits columns

src/AppConstants.js, src/PresentationalComponents/Common/Tables.js, src/PresentationalComponents/RulesTable/RulesTable.js, src/PresentationalComponents/SystemsTable/SystemsTable.js
fixes: https://projects.engineering.redhat.com/browse/RHCLOUD-6434
=> Filter systems table by whether or not the columns have hits

src/PresentationalComponents/SystemsTable/SystemsTable.js
=> System table to prioritize name columnsize

src/AppConstants.js, src/Messages.js, src/PresentationalComponents/RulesTable/RulesTable.js, src/PresentationalComponents/SystemsTable/SystemsTable.js, src/PresentationalComponents/TagsToolbar/TagsToolbar.js, src/PresentationalComponents/TagsToolbar/_TagsToolbar.scss
This PR is in response to https://projects.engineering.redhat.com/browse/RHCLOUD-6739, which requests the implementation of filtering for the tags selection tool.
Before:
After:
=> Add Filtering to Tags Selector

src/PresentationalComponents/SystemsTable/SystemsTable.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-7222
=> Prevent systable debounce from 🤯 offset

locales/data.json, locales/translations.json, src/Messages.js, src/PresentationalComponents/Common/Tables.js, src/PresentationalComponents/RulesTable/RulesTable.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-7081
=> Renames systable filterchip to name, rectable to recommendation

src/PresentationalComponents/Inventory/Inventory.js
=> Rec detail, ensure remediate button is disabled when no playbook

src/PresentationalComponents/TagsToolbar/TagsToolbar.js
Super insignificant but what the heck.
=> URI decode the tags tooltip

src/SmartComponents/Recs/List.js, src/SmartComponents/Recs/_List.scss
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-8035
=> Removes cve banner 🤙🏾🙂😆🤫🤭😵🤐🥴

src/SmartComponents/Recs/Details.js, src/SmartComponents/Recs/Details.scss
https://projects.engineering.redhat.com/browse/RHCLOUD-7990
=> Add rule category to recommendation details component

src/PresentationalComponents/RuleLabels/RuleLabels.js
https://projects.engineering.redhat.com/browse/RHCLOUD-7948
=> Remove the bell icon from the Disabled label

src/SmartComponents/Recs/List.js, src/SmartComponents/Recs/_List.scss
this removes the cve label for prod-stable branch, dupe of #699
=> Dupe of #699 for prod stable, for Rob 💌

src/PresentationalComponents/TagsToolbar/ManageTags.js, src/PresentationalComponents/TagsToolbar/TagsToolbar.js
This PR doesn't change anything visually just some code changes that I think will help once the /tags endpoint gets fixed by inventory 👍
=> Return all data from inventory tags endpoint

src/PresentationalComponents/RuleDetails/RuleDetails.js
=> Ensures rec details titles are bold

src/PresentationalComponents/RulesTable/RulesTable.js, src/PresentationalComponents/TopicsTable/TopicsTable.js
also now fixes topics table, cuz s small n related
=> Make rec table upper pagination compact

package-lock.json, package.json, src/PresentationalComponents/ExecutiveReport/Build.js
Following up the FEC updates, and adding in the InsightsLabel for the Exec Reports 😁 🤝 🥇
=> Add InsightsLabel to PDF

src/PresentationalComponents/Export/SystemsPdf.js
Fixes 🎫 -> https://projects.engineering.redhat.com/browse/RHCLOUD-8527
=> Title only on first page of SystemsPDF

src/PresentationalComponents/RulesTable/RulesTable.js, src/PresentationalComponents/RulesTable/_RulesTable.scss, src/PresentationalComponents/SystemsTable/SystemsTable.js, src/SmartComponents/Recs/Details.js
Just a couple of updates for the following 🎟️ 👍 
https://projects.engineering.redhat.com/browse/RHCLOUD-8654
and... https://projects.engineering.redhat.com/browse/RHCLOUD-8659
=> Update sorting and width

src/Messages.js, src/PresentationalComponents/Modals/DisableRule.js, src/PresentationalComponents/RulesTable/RulesTable.js, src/SmartComponents/Recs/Details.js
This PR fixes a few things for the following 🎟️
https://projects.engineering.redhat.com/browse/RHCLOUD-8656
https://projects.engineering.redhat.com/browse/RHCLOUD-8657
https://projects.engineering.redhat.com/browse/RHCLOUD-8658
1. Updates DisableRule modal text
2. Adds successfully disabled notifications
3. Adds successfully enabled notifications
=> Update DisableRule modal and add Notifications

src/PresentationalComponents/Modals/DisableRule.js, src/PresentationalComponents/RulesTable/RulesTable.js, src/SmartComponents/Recs/Details.js
Adds the default timeout to the notifications after you disable or enable a rule 💯
=> Add timeout to disable/enable notifications

package-lock.json, package.json, src/Messages.js, src/PresentationalComponents/RulesTable/RulesTable.js
This PR is in response to https://projects.engineering.redhat.com/browse/RHCLOUD-8729 
**After:**
=> Add tooltip to export icon

src/App.js, src/AppConstants.js, src/SmartComponents/Recs/Details.js, src/SmartComponents/Recs/List.js, src/SmartComponents/Systems/List.js, src/SmartComponents/Topics/Details.js, src/SmartComponents/Topics/List.js
=> Disable custom filter on beta branches or if localStorage is set

src/App.js
in  lieu of getting local chrome showing the global filter... this guess can't break it any more than it already is 🤷‍♀️🦹‍♀️💪
=> This work restores Advisor storing selected tags encoded

profiles/local-frontend.js, src/App.js
follow on to#747 that fixed very little
=> Fixes global filter tagging, removes hardcoded chrome source

src/App.js, src/PresentationalComponents/TagsToolbar/TagsToolbar.js
=> For Dan, changeup how tags are encoded🛠🐡🧠

src/PresentationalComponents/SystemsTable/SystemsTable.js
fixes https://issues.redhat.com/browse/ADVISOR-1307
=> Default state of system table is show all systems🥰🦹‍♀️

.eslintrc.yml, src/App.js, src/AppActions.js, src/AppConstants.js, src/AppReducer.js, src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js, src/PresentationalComponents/Common/Tables.js, src/PresentationalComponents/ExecutiveReport/Build.js, src/PresentationalComponents/Export/SystemsPdfBuild.js, src/PresentationalComponents/Inventory/Inventory.js, src/PresentationalComponents/Modals/DisableRule.js, src/PresentationalComponents/Modals/ViewHostAcks.js, src/PresentationalComponents/RulesTable/RulesTable.js, src/PresentationalComponents/SystemsTable/SystemsTable.js, src/SmartComponents/Recs/Details.js, src/SmartComponents/Topics/Details.js, src/SmartComponents/Topics/List.js, src/cveToRuleid.js
fixes https://issues.redhat.com/browse/ADVISOR-1257
yah. so now we'll have workloads on the urls, changes when global filter selection changes... not sure this work (that does the filtering) is in prod api yet... (results don't look different) :thinking:
also tired of excusing camel case, get over it eslint, we deal with it sometimes (makes this pr much larger than it woulda been by leaving it alone 🤷 )
=> Adds workflow filter to advisor

src/App.js, src/PresentationalComponents/Common/Tables.js, src/PresentationalComponents/RulesTable/RulesTable.js, src/PresentationalComponents/SystemsTable/SystemsTable.js, src/SmartComponents/Recs/Details.js, src/SmartComponents/Topics/List.js
once we merge this in, will fix the dashboard card
=> Fixes workloadahroo filterahroonie, removes rule_status undefined url

src/AppConstants.js, src/PresentationalComponents/Common/Tables.js, src/PresentationalComponents/RulesTable/RulesTable.js
fixes https://issues.redhat.com/browse/ADVISOR-1419
=> Change rule_status param to suit api change

src/App.js, src/AppActions.js, src/AppConstants.js, src/AppReducer.js, src/PresentationalComponents/Common/Tables.js, src/PresentationalComponents/RulesTable/RulesTable.js, src/PresentationalComponents/SystemsTable/SystemsTable.js, src/SmartComponents/Recs/Details.js, src/SmartComponents/Topics/List.js
fixes https://issues.redhat.com/browse/ADVISOR-1414
workloads still show up broken locally, but oughta work on beta
~woops back to wip gotta throw sid everywhere 😬~
=> SID support, rec table all status filter param, adopt mapGlobalFilter 👩‍🏭 

src/SmartComponents/Common/ClassicRedirect.js
Some of my testing changes somehow found their way into the last PR 😬
=> Fix switch in ClassicRedirect

src/SmartComponents/Recs/List.js
Fixes https://issues.redhat.com/browse/ADVISOR-1496
=> Store the alert close action in local storage (.. and update deps)

src/PresentationalComponents/RuleDetails/RuleDetails.js
fixes https://issues.redhat.com/browse/ADVISOR-1552
=> Changes rec detail topic to not be in a card 🤷‍♀️🤯

package-lock.json, package.json, profiles/local-frontend.js, src/App.js, src/PresentationalComponents/RulesTable/RulesTable.js, src/Routes.js
@AllenBW I've made a little clean up after we used advisor for the chrome 2 testing. Also removed some legacy code that is not required anymore.
=> Federated modules debugging

locales/translations.json, package-lock.json, package.json, src/Messages.js, src/PresentationalComponents/ExecutiveReport/Download.js, src/PresentationalComponents/Export/SystemsPdf.js
fixes https://issues.redhat.com/browse/RHCLOUD-12429
=> Adds support for pdf export group names

locales/translations.json, src/Messages.js, src/PresentationalComponents/RulesTable/RulesTable.js
fixes https://issues.redhat.com/browse/ADVISOR-1619
=> Change rectable name filter placeholder

src/PresentationalComponents/RulesTable/RulesTable.js, src/PresentationalComponents/TopicsAdminTable/TopicsAdminTable.js, src/PresentationalComponents/TopicsTable/TopicsTable.js
fixes https://issues.redhat.com/browse/ADVISOR-1677
locally my styles aren't sticking too well, gonna see how this shows up in prod-beta, thinkin it might work there
=> Adds sticky header to all the tables, refresh stale ones🥑🥑🥑🥑🥑🥑🥑

src/PresentationalComponents/TopicsTable/TopicsTable.js
fixes https://issues.redhat.com/browse/ADVISOR-1620
=> Topics filter value to lowercase

src/AppActions.js, src/PresentationalComponents/Inventory/Inventory.js, src/SmartComponents/Recs/Details.js
how filter by systems! also refactors component to be... better? **BE BETTER COMPONENT**
ps: managing expectations, not preserving table state, not updating url, didn't do these things before here, maybe do them in the future? 🤷
=> Adds search to rec details system table, refactors details page

src/SmartComponents/Recs/Details.js
fixes https://issues.redhat.com/browse/ADVISOR-1710
=> Force load systems on rec details page 

src/PresentationalComponents/ReportDetails/ReportDetails.js, src/PresentationalComponents/ReportDetails/report-details.scss
fixes https://issues.redhat.com/browse/ADVISOR-831
=> Reconfigures report rendering a wee bit for better readability

config/dev.webpack.config.js, config/prod.webpack.config.js
fixes https://issues.redhat.com/browse/ADVISOR-1750
=> Advertise advisor report details as fedmod ⛲️

package-lock.json, package.json, src/PresentationalComponents/Inventory/Inventory.js
fixes https://issues.redhat.com/browse/RHCLOUD-12763
=> Fix sentence case, also npm audit

src/SmartComponents/Recs/List.js
fixes https://issues.redhat.com/browse/ADVISOR-1778
=> Removes rh disabled rules alert from rec page

README.md
=> Update travis-ci links in README.md

src/AppReducer.js, src/PresentationalComponents/RulesTable/RulesTable.js, src/PresentationalComponents/SystemsTable/SystemsTable.js
Fixes https://issues.redhat.com/browse/ADVISOR-1777
=> Use compact tables for systems/recs and page size 20

locales/translations.json, src/Messages.js, src/PresentationalComponents/RuleDetails/_RuleDetails.scss
Fixes https://issues.redhat.com/browse/ADVISOR-1814
Sorry I missed this :facepalm:
=> Reduce font size in compact table expanded view

src/PresentationalComponents/Inventory/Inventory.js, src/PresentationalComponents/SystemsTable/SystemsTable.js
fixes https://issues.redhat.com/browse/ADVISOR-1718
=> Updates inv tables as per InventoryTable post-summit refactoring plan 🍟

src/AppReducer.js, src/PresentationalComponents/SystemsTable/SystemsTable.js
Update to sys table to rely on getEntities n remove all the other crutches
everything work EXCEPT when yah input display name n refresh the page it doesn't carry over (everything else does) gotta figure out how to ensure that thing plugs into the inventory table, that aside getting this up there real fast cuz it fixes some noticeable problems
=> fun timez making getEntities workin

src/PresentationalComponents/Common/Tables.js, src/PresentationalComponents/Inventory/Inventory.js, src/PresentationalComponents/SystemsTable/SystemsTable.js, src/SmartComponents/Recs/Details.js
fixes https://issues.redhat.com/browse/ADVISOR-1838
=>     Update rec details table to support pagination, getEntities and OS 👨‍🔬

src/AppConstants.js, src/PresentationalComponents/Export/SystemsPdfBuild.js
partially fixes https://issues.redhat.com/browse/ADVISOR-1851
=> Migrate cloud.rh to w/e the base is

src/App.scss, src/AppConstants.js, src/Messages.js, src/PresentationalComponents/Inventory/Inventory.js, src/PresentationalComponents/SystemsTable/SystemsTable.js
fixes https://issues.redhat.com/browse/ADVISOR-1836 , https://issues.redhat.com/browse/ADVISOR-1835
one update to the pictures, dropdown has been limited to max height of 400px, same as global filter, vertical scroll thereafter
=> Adds os filtering to systems and affected systems pages

src/PresentationalComponents/RulesTable/RulesTable.js, src/SmartComponents/SystemAdvisor/SystemAdvisor.js
fixes https://issues.redhat.com/browse/ADVISOR-1857
=> Adds expand all to /recommendations, updates sysdetails expand all 🥸❤️‍🔥

src/SmartComponents/Recs/Details.js
fixes https://issues.redhat.com/browse/ADVISOR-1877
=> Rec details, relocates status label behind rec name

src/Messages.js, src/PresentationalComponents/Common/Common.js, src/PresentationalComponents/Common/_Common.scss, src/PresentationalComponents/PathwaysPanel/PathwaysPanel.js, src/PresentationalComponents/PathwaysPanel/_PathwaysPanel.scss, src/PresentationalComponents/PathwaysPanel/testdata.json, src/PresentationalComponents/RuleDetails/RuleDetails.js, src/PresentationalComponents/RuleDetails/_RuleDetails.scss, src/SmartComponents/Recs/List.js
fixes https://issues.redhat.com/browse/ADVISOR-1879
=> Adds pathways panel and pathway panel cards

src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js, src/PresentationalComponents/Inventory/InventoryDetails.js, src/SmartComponents/Recs/Details.js, src/SmartComponents/Topics/Details.js, src/SmartComponents/Topics/List.js
fixes https://issues.redhat.com/browse/ADVISOR-1922
=> Fixes breadcrumbs, sets us up for pathways support 🗺🤓

config/dev.webpack.config.js, config/prod.webpack.config.js, src/PresentationalComponents/RuleDetails/index.js
=> Adds rec details as a federated module for OCPAF consumption

src/PresentationalComponents/Common/Common.js, src/PresentationalComponents/Common/_Common.scss, src/PresentationalComponents/Labels/RuleLabels.js, src/PresentationalComponents/Labels/_RuleLabels.scss, src/PresentationalComponents/PathwaysPanel/PathwaysPanel.js, src/PresentationalComponents/PathwaysPanel/_PathwaysPanel.scss, src/PresentationalComponents/ReportDetails/ReportDetails.js, src/PresentationalComponents/ReportDetails/report-details.scss, src/PresentationalComponents/RuleDetails/RuleDetails.js, src/PresentationalComponents/RuleDetails/_RuleDetails.scss, src/SmartComponents/Recs/Details.js, src/SmartComponents/Recs/Details.scss, src/SmartComponents/Recs/DetailsPathways.js, src/SmartComponents/Recs/List.js, src/SmartComponents/Recs/List.scss
Jira: https://issues.redhat.com/browse/RHCLOUD-16357
- Rename class prefixes with "adv-" in place of "ins-" where possible
- Add missing PF variables 
- general cleanup
=> rescope class names

src/AppConstants.js
9.0, 8.6, 8.5, are new rhel version in the inventory.
=> Add new RHEL versions

locales/data.json, locales/translations.json, src/Messages.js
https://issues.redhat.com/browse/ADVISOR-1816
=> Fix rbac denial message typo

src/PresentationalComponents/Common/DownloadHelper.js, src/PresentationalComponents/Inventory/Inventory.js, src/SmartComponents/Recs/Details.js
This export button has a different requirement than the other two export buttons in the app.  The requirement is that it export exactly what is in the table. This is a hacky solution but should satisfy that.
=> Export affected systems

src/PresentationalComponents/RuleDetails/RuleDetails.js
=> [prod-beta] Wrap RuleDetails with custom router; refactor (#891)

locales/data.json, locales/translations.json, src/Messages.js, src/PresentationalComponents/RulesTable/RulesTable.js, src/SmartComponents/Recs/Details.js, src/SmartComponents/Recs/DetailsPathways.js, src/SmartComponents/SystemAdvisor/SystemAdvisor.js
Closes [ADVISOR-2163](https://issues.redhat.com/browse/ADVISOR-2163)
=> Rename 'added' and 'publish date' to 'modified'

src/SmartComponents/SystemAdvisor/EmptyStates.js, src/SmartComponents/SystemAdvisor/SystemAdvisor.js
Resolves: [Advisor](https://issues.redhat.com/browse/ADVISOR-2061).
To test:
1. Visit the system details page in Advisor application.
2. Filter the table to get empty state, check if everything is ok.
3. Open system details page with 0 recomendations, check if everything is ok.
=> Advisor-2061: system details empty states are refactored

.eslintrc.yml, package-lock.json, package.json
this PR is to resolve error with the command 'npm run lint:js:fix'. The command is very helpfull to resolve all lint issues at once.
=> RHIF-15: fix eslint configuration

src/SmartComponents/SystemAdvisor/SystemAdvisor.js
Fixes incorrect row count in SystemAdvisor page:
=> fix: SystemAdvisor table row count is fixed

src/PresentationalComponents/Cards/Pathways.js
Added Pathway card name
Before:
After:
=> feat: ADVISOR-2265 - Added Pathway card name

src/PresentationalComponents/AppIntro/IntroBody.js
This is needed for an easy Pendo access to the button.
=> chore: add ouiaId to tour button

src/App.scss, src/PresentationalComponents/Common/Tables.js, src/PresentationalComponents/Inventory/Inventory.js, src/PresentationalComponents/SystemsTable/SystemsTable.js, src/SmartComponents/Recs/Details.js, src/SmartComponents/Recs/DetailsPathways.js
Closes [ADVISOR-2013](https://issues.redhat.com/browse/ADVISOR-2013)
=> Systems tag filtering

config/setupTests.js, package-lock.json, package.json, src/PresentationalComponents/Common/Tables.js, src/PresentationalComponents/Common/__tests__/Tables.fixtures.js, src/PresentationalComponents/Common/__tests__/Tables.tests.js
I also added Advisor's first test tests and removed enzyme.
=> [RHIF-20] Add AAP and MSSQL workloads

src/PresentationalComponents/SystemsTable/SystemsTable.js, src/PresentationalComponents/SystemsTable/SystemsTableAssets.js
The PR includes work for making OS column in systems table sortable as well as some refactoring column management.
=> feat(SystemsTable): ADVISOR-1960 make OS column sortable

package-lock.json
Same update fixed the same error message in Vulnerability https://github.com/RedHatInsights/vulnerability-ui/pull/1628
=> fix: Update FEC config utils to fix crash related to fedmods

src/PresentationalComponents/RuleRating/RuleRating.js
Fixes [ADVISOR-1920](https://issues.redhat.com/browse/ADVISOR-1920).
Testing:
1. Open recommendation detail page
2. Click on thumbs up or thumbs down rating
3. Feedback modal should open
=> Open feedback modal on rule rating

src/PresentationalComponents/Cards/Pathways.js, src/PresentationalComponents/Inventory/Inventory.js, src/Routes.js, src/SmartComponents/Recs/DetailsPathways.js, src/SmartComponents/Recs/Recs.js
System affected link now takes you to pathways details page with 'systems' tag select. To view changes 
- Click Recommendations in the left hand menu
- Select any systems affected link (on the top card, displays text that says 'improve recommended pathways'
- You are navigated to the new route, /recommendations/pathways/systems/
- It scrolls down to the affected systems
=> System Affected Link works properly - ADVISOR 2116

build_deploy.sh, pr_check.sh
* `IMAGE` now matches quay name
* `COMPONENT` matches folder name in app-interface
=> Fix image name and component

package-lock.json, package.json
=> Bump FEC config to resolve CVEs

package-lock.json
This combines the package update PRs by dependabot into one, as tackling them with dependabot commands etc. would be a hassle.
=> chore(deps): Bump dependencies with high severity CVEs

src/PresentationalComponents/Inventory/Inventory.js
Following up upon the pathways check for advisor-2388 PR, This PR makes it possible for the button status to change properly when selecting recommendations. 
To test you will need to run against prod with `CHROME_ENV=prod-stable npm run start:proxy:beta`
-Navigate to pathways
- First select a pathway with manual remediation, go the systems tab, you'll see that the remediation button is disabled.
-Then do the same thing with a pathway with an automatic remediation available, you'll see the remediation button can be enabled when you select
Then navigate to recommendations page, 
select a recommendation with an automatic remediation playbook, you'll see its possible to enable to button
Follow the same steps for a recommendation with a manual playbook, you'll see the button isnt selectable
=> Rules check for ADVISOR-2388

src/SmartComponents/SystemAdvisor/SystemAdvisor.js
This is regarding ADVISOR-2546
1) Go to the recommendation list
2) Click on any recommendation with affected systems
3) Click on any system
4) The first recommendation should be open
=> ADVISOR-2546: expanded first item on page load

src/PresentationalComponents/Cards/Pathways.js, src/PresentationalComponents/Cards/Pathways.scss
This is a rework of the pathways card seen in pathway details page. To view ,
Run advisor in beta env
select a pathway
Now you should have access to this card
The mock for it is here (in the [ticket](https://issues.redhat.com/browse/ADVISOR-2122), you can see that the size of the mock is smaller, and that it is something to be ignored)
=> Advisor-2122

src/Messages.js, src/SmartComponents/SystemAdvisor/SystemAdvisor.js
Promotes the fix for [missing recommendations](https://issues.redhat.com/browse/ADVISOR-2605) bug into prod-beta.
=> Promotes the fix for [missing recommendations](https://issues.redhat.com/browse/ADVISOR-2605) bug into prod-beta.

src/PresentationalComponents/Cards/Pathways.js, src/PresentationalComponents/Cards/Pathways.scss, src/PresentationalComponents/Inventory/InventoryDetails.js, src/PresentationalComponents/Labels/CategoryLabel.js, src/PresentationalComponents/Labels/RecommendationLevel.js, src/PresentationalComponents/Labels/RuleLabels.js, src/PresentationalComponents/PathwaysPanel/PathwaysPanel.js, src/PresentationalComponents/PathwaysPanel/_PathwaysPanel.scss
Styling changes from Advisor SPUD meeting. 
Will be looked over by Stefan , once approved, just needs code review
=> style(ADVISOR-2645) SPUD-UI Changes

src/PresentationalComponents/PathwaysTable/PathwaysTable.js, src/PresentationalComponents/RulesTable/RulesTable.js, src/SmartComponents/Recs/List.js
[ADVISOR-2735](https://issues.redhat.com/browse/ADVISOR-2735)
=> Only apply filters on page load if tab is active

README.md
Remove outdated information (running with Insights proxy, old environments, running with custom API) and replace it wit useful information.
=> Redo README.md to be up to date

cypress/fixtures/systemRecommendations.json, cypress/support/component.js, cypress/support/globals.js, locales/data.json, locales/translations.json, package.json, src/Messages.js, src/SmartComponents/SystemAdvisor/SystemAdvisor.cy.js, src/SmartComponents/SystemAdvisor/SystemAdvisor.js
Resolves https://issues.redhat.com/browse/ADVISOR-2783
=> feat(SystemAdvisor): ADVISOR-2783 - Add first impacted column

src/PresentationalComponents/Inventory/Inventory.js, src/PresentationalComponents/Inventory/helpers.js, src/PresentationalComponents/SystemsTable/SystemsTable.js, src/PresentationalComponents/helper.js
This PR introduces the refactor of the options object in the Refactor PR (much more readable), and sends parameter correctly to the api endpoints. 
For testing navigate to to /recommendations, and select an recommendation with a high number of systems.
Here add filters like the os system, name, etc. Also make sure sorting is working and updating properly.
=> fix(ESSNTL-3781): Fixes filter issues in options object

src/PresentationalComponents/SystemsTable/SystemsTable.js, src/PresentationalComponents/helper.js
Fixes https://issues.redhat.com/browse/ADVISOR-2902.
=> Release to prod-beta

src/PresentationalComponents/SystemsTable/SystemsTable.js, src/PresentationalComponents/helper.js
Fixes https://issues.redhat.com/browse/ADVISOR-2902.
=> Release to prod-stable

cypress/support/globals.js, src/PresentationalComponents/RulesTable/RulesTable.cy.js
Each filter change triggers a new network request with filter query parameters appended. These tests ensure that the table adds correct URL parameter to requests.
=> test(Recs list): Test filter query parameters

package.json, src/PresentationalComponents/RulesTable/RulesTable.cy.js
Need advice, during the development, I discovered that if we double-click on the sorting button, URL addresses do not contain minus sign before the sorting parameter. When I added the console.log(window.location.href); to the "descending" part of the IF statement, it showed the same URL address as in ascending.
If we can solve this issue - we can add these tests to the other tables where we utilize sorting with API requests.
=> feat(RecsListTests): sorting tests

.github/pull_request_template.md
introduces pull request template.
=> chore: introduce pull request template

src/PresentationalComponents/RulesTable/RulesTable.cy.js
Removed unnecessary code bloat in the test file
Make sure that tests are passing
Too much code that repeated itself
Less code repeat
=> chore(RulesTable): cleaning up the test file

.github/workflows/CI.yml, cypress/fixtures/topics.json, cypress/support/globals.js, src/PresentationalComponents/TopicsTable/TopicsTable.cy.js, src/PresentationalComponents/TopicsTable/TopicsTable.js, src/PresentationalComponents/helper.js, src/PresentationalComponents/helper.test.js
https://issues.redhat.com/browse/ADVISOR-2908
Moar tests!!!!!!
=> test(topics table): Sorting refactor and testing the Topics table

src/PresentationalComponents/Inventory/InventoryDetails.js, src/PresentationalComponents/RulesTable/RulesTable.js, src/PresentationalComponents/TopicsAdminTable/TopicsAdminTable.js, src/SmartComponents/Recs/Details.js, src/SmartComponents/Recs/DetailsPathways.js, src/SmartComponents/Recs/DetailsRules.js, src/SmartComponents/Recs/List.js, src/SmartComponents/Systems/List.js, src/SmartComponents/Topics/Details.js, src/SmartComponents/Topics/List.js
https://issues.redhat.com/browse/RHCLOUD-23126
Removed Main component and replaced it with Section
Launch it locally and check how it works on stage-beta
A lof of screenshots to put here, I will create a topic in slack
=> fix(Tables): Remove Main from the tables

cypress/fixtures/pathways.json, cypress/support/globals.js, src/PresentationalComponents/PathwaysTable/PathwaysTable.cy.js
Tests for pathways tab in RHEL Advisor
Missing tests for filtering, we'll have to add it
https://issues.redhat.com/browse/ADVISOR-2908
run npx cypress open --component and run the tests for pathways tab
=> test(Pathways tab): cypress tests 

cypress/fixtures/detailsrules.json, cypress/fixtures/detailsrulestopic.json, src/SmartComponents/Recs/DetailsRules.cy.js
The basic test for the details rules
https://issues.redhat.com/browse/ADVISOR-2908
run npx cypress open --component and run test
=> test(DetailsRules): Basic test for the details rules

.github/workflows/CI.yml, .travis.yml
It seems that GH actions have some issues with push the fresh builds. This PR gives release back to the travis
=> fix(ghactions): travis release is back

package-lock.json, package.json
https://issues.redhat.com/browse/ADVISOR-2945
Updating FEC to the latest version
=> chore(deps): updating fec

package-lock.json, package.json
https://issues.redhat.com/browse/ADVISOR-2945
fixing asterix bug
=> chore(deps):updating advisor components to fix bug

src/App.js
Associated Jira ticket: # [(RHIF-162)](https://issues.redhat.com/browse/RHIF-162)
Nav click events do not need extra processing, let's get rid of unnecessary code. Also, after RBAC checking has been introduced, there is no need to check user using `chrome.auth.getUSer()`
general functionality should not change
=> chore(RHIF-162): get rid of unnecessary app nav code

.codecov.yml
The codecov/patch adds incorrect annotations that make CI to fail 
=> chore(codecov): updating codecov settings

src/PresentationalComponents/Inventory/Inventory.js, src/SmartComponents/Systems/List.js
Loads systems table synchronously as the component is directly rendered in the UI.
=> chore: load systems table sync

src/App.js, src/SmartComponents/Topics/AdminProtectedRoute.js, src/Utilities/Api.js
Replacing insights.chrome with a chrome hook
https://issues.redhat.com/browse/RHIF-123
Run npm run start:proxy:beta and go through the pages, try to break the UI
=> enh(chrome): updating to chrome hook

src/PresentationalComponents/Inventory/InventoryDetails.js
=> chore: pass inventoryId to DetailWrapper

src/Routes.js
 As in accordance to these mocks, this PR adds zero state to Advisor,  https://docs.google.com/document/d/1FGuzbL2jyRmn_coYD5Z_o3d0MhOf1vQDT46NQvsfPyA/edit#heading=h.1hvxoje16w3i  https://www.sketch.com/s/550bd962-ca1f-42d8-8d89-d457527a059a/a/qbe9Ol2#Inspect   https://www.sketch.com/s/550bd962-ca1f-42d8-8d89-d457527a059a/prototype/a/AEF47CA9-8F00-40FC-B39B-3B989D3F83FD   To test, sign into an account with 0 systems connected 
=> feat(RHIN-830): Add Zero State to Advisor

config/dev.webpack.config.js
=> chore: fix routes url to use beta/apps

src/Routes.js
=> Add ID to zerostate banner

src/SmartComponents/SystemAdvisor/SystemAdvisor.js
https://issues.redhat.com/browse/ADVISOR-3041
Run pr locally
use insights-qa account
open rhel advisor systems table
find the system called "master.test310.com"
Expand rules recommendations and check the "Related Knowledgebase article" links.
Check the rule Decreased system performance occurs when not running the irqbalance service
it should have a link that leads to an article or solution page and work!!!
<br class="Apple-interchange-newline">
=> fix(advisor-3041): restrict hydra docs to solutions or articles

README.md, config/dev.webpack.config.js
Associated Jira ticket: no jira
This makes sure there is an option to run Advisor together with other apps in the local environment.
Try to follow new docs and make sure you are able to run more apps with Advisor.
=> chore: Support LOCAL_API

.codecov.yml
SOURCE
https://community.codecov.com/t/codecov-patch-strange-behavior/4348/5
=> fix(codecov): fixing wrong codecov messages

package-lock.json, package.json
ticket advisor-3041
how to test:
launch advisor against production
use insights-qa account
check the system https://console.redhat.com/insights/advisor/systems/3cce4a57-acaf-4974-a0b1-84961354a5de
if it's not exist - request it from rodrigo antunes
=> fix(advisor-3041): fix broken links in report details

src/App.js
Associated Jira ticket: #ADVISOR-2955
Verify that navigating via sidebar still works and the app acts as expected.
- [-] Screenshots before and after the change are added
- [-] Tests for the changes have been added
- [-] README.md is updated if necessary
- [] Needs additional dependent work
=> chore: ADVISOR-2955 - Remove APP_NAVIGATION registration

src/PresentationalComponents/SystemsTable/SystemsTable.js, src/PresentationalComponents/SystemsTable/createColumns.js, src/PresentationalComponents/SystemsTable/createColumns.test.js, src/PresentationalComponents/helper.js
=> feat(essntl-3715): unrevert inv groups filter and column

package-lock.json, package.json
https://issues.redhat.com/browse/RHINENG-1722
=> Update FEC to fix bug with Not Connected empty state

config/cypress.webpack.config.js, config/overrideChrome.js, src/PresentationalComponents/PathwaysTable/PathwaysTable.cy.js, src/PresentationalComponents/RulesTable/RulesTable.cy.js, src/PresentationalComponents/TopicsTable/TopicsTable.cy.js, src/SmartComponents/Recs/DetailsRules.cy.js
Went back and fixed tests that were commented out.
https://issues.redhat.com/browse/ADVISOR-3168
=> fix(advisor-3168): fixed cypress tests

README.md
=> chore(README): announce container migration

config/prod.webpack.config.js
Adds beta code verification config 
=> chore(prodConfig): enable beta/stable difference for deployments

package-lock.json
Fixes https://github.com/advisories/GHSA-xwcq-pm8m-c4vf.
=> chore: Bump crypto-js version to 4.2.0

src/SmartComponents/Recs/Details.js, src/SmartComponents/Recs/helpers.js, src/SmartComponents/Recs/helpers.test.js
This PR institues https://issues.redhat.com/browse/RHINENG-3064 and adds a different title to Rec details page. 
Acceptance criteria:
When there is an immutable system, the title above the table should include total number
Total number should count both conventional and immutable systems
when there is no immutable system, the title should have no change and the total number
=> feat(RHINENG-3064): Add Modified Table title of Rec Details Title

config/dev.webpack.config.js, package-lock.json, package.json
This PR updates the FEC package to allow for the use of the updated web pack config settings. As more gets added there, more can be removed in the individual app.
=> chore(fec): FEC package bump and updated wepback config

src/SmartComponents/Recs/Details.js, src/SmartComponents/Recs/DetailsTitle.js, src/SmartComponents/Recs/DetailsTitle.test.js
Cosmetic change: introduces a loading state while hybrid system counts are being fetched from API in recommendation details page
0 is shown while API requests are made, which is not good
Skeleton is shown while API requests are made.
=>  chore(RecommendationDetail): show Skeleton on table title

src/PresentationalComponents/ExecutiveReport/Download.js
In an attempt to diagnose the pdf generator issue ,this PR refactors bits of the Download.js file : https://issues.redhat.com/browse/RHINENG-6162
=> refactor(RHINENG-6162): Refactor pdf generator

src/SmartComponents/HybridInventoryTabs/ImmutableDevices.js, src/SmartComponents/HybridInventoryTabs/ImmutableDevices.test.js
Enables group filter on immutable devices
=> feat(RHINENG-6256): enable group filter on immutable tabs

package-lock.json, package.json, src/SmartComponents/SystemAdvisor/SystemAdvisor.js, src/SmartComponents/SystemAdvisor/SystemAdvisorAssets.js
Updating UI after this PR
https://github.com/RedHatInsights/frontend-components/pull/1992
https://issues.redhat.com/browse/RHINENG-9046
we removed hook from the fec components, now we are passing isProd through props
=> chore(RHINENG-9046): updating UI after fec update

package-lock.json, package.json
=> chore(deps-dev): bump qs from 6.10.1 to 6.12.0

package-lock.json, package.json
Associated Jira ticket: [# (issue)](https://issues.redhat.com/browse/RHINENG-8925)
=> chore(deps): Fix follow-redirects CVE

.gitignore, config/prod.webpack.config.js, package-lock.json, package.json
Adds configuration to add source maps to sentry
=> feat(sentryConfig): Adds sentry configuration

.github/workflows/webpack.yml
=> Create webpack.yml for sentry config

src/Messages.js, src/PresentationalComponents/Inventory/InventoryDetails.js, src/SmartComponents/Recs/Details.js, src/SmartComponents/Recs/DetailsPathways.js, src/SmartComponents/Recs/List.js, src/SmartComponents/Systems/List.js, src/SmartComponents/Topics/Details.js, src/SmartComponents/Topics/List.js
Resolves: https://issues.redhat.com/browse/RHINENG-9387
Updates page titles according to 'Current concept' column, single line treatment in this [sheet](https://docs.google.com/spreadsheets/d/1Uhwn6i9B383xUbnRQ2IWY3EZ6dihc-UfkHxnR_c7zXI/edit#gid=1001620868)
=> chore(RHINENG-9387): update page titles

fec.config.js
Associated Jira ticket: [RHINENG-7044](https://issues.redhat.com/browse/RHINENG-7044)
=> fix(fec): RHINENG-7044 - Correct module federation config

.github/workflows/webpack.yml
Just builds the application before sending anything to sentry
=> Update webpack.yml to build before sending to sentry

src/PresentationalComponents/PathwaysTable/PathwaysTable.cy.js, src/PresentationalComponents/PathwaysTable/PathwaysTable.js, src/PresentationalComponents/RulesTable/RulesTable.cy.js, src/PresentationalComponents/RulesTable/helpers.js, src/PresentationalComponents/TopicsTable/TopicsTable.cy.js, src/PresentationalComponents/TopicsTable/TopicsTable.js
Associated Jira ticket: [RHINENG-3595](https://issues.redhat.com/browse/RHINENG-3595)
How to test:
1. Open recommendations table and click on system count -- you should be navigated to the recommendation detail page
2. Open pathways table and click on system count -- you should be navigated to the pathway detail page
3. Open topics table and click on system count -- you should be navigated to the topic detail page
=> Change system counts inside tables to links

src/PresentationalComponents/helper.js, src/PresentationalComponents/helper.test.js
Associated Jira ticket: #[RHINENG-10448](https://issues.redhat.com/browse/RHINENG-10448)
=> fix(SystemsTable): RHINENG-10448 - Fix os filter conversion

cypress/support/component.js, src/PresentationalComponents/Loading/Loading.cy.js
https://issues.redhat.com/browse/RHINENG-10340
=> Fix Cypress config

src/AppConstants.js, src/PresentationalComponents/Common/DownloadHelper.js, src/PresentationalComponents/ExecutiveReport/Download.js, src/PresentationalComponents/RulesTable/RulesTable.js, src/PresentationalComponents/helper.js
=> fix(RHINENG-12793): Make exports querystring like rules

package-lock.json, package.json, src/PresentationalComponents/PathwaysTable/PathwaysTable.js, src/PresentationalComponents/RulesTable/helpers.js, src/PresentationalComponents/TopicsTable/TopicsTable.js, src/SmartComponents/SystemAdvisor/SystemAdvisorAssets.js
Fixes https://issues.redhat.com/browse/RHINENG-11992.
=> fix(RHINENG-11992): Upgrade FEC/config dependency

package-lock.json
This is quick commit to address the ongoing issue on master while running npm run ci: the dependencies seem to be not synced with package-lock.json.
Associated Jira ticket: no jira.
=> chore: Fix unsynced package-lock.json

.tekton/advisor-frontend-pull-request.yaml, .tekton/advisor-frontend-push.yaml
=> feat(konflux): add new mandatory RPM signature scan task to tekton

package-lock.json
https://issues.redhat.com/browse/RHINENG-14273
=> chore(deps): Update packages to fix cross-spawn CVE

fec.config.js
Just changes the names- allows for easier demoing/testing
=> fix(sentry): Change sentry var names

src/SmartComponents/Recs/List.js
https://issues.redhat.com/browse/RHINENG-14774
=> feat(Header): Add tooltip explaining recommendations to header

.github/workflows/sentry.yml
We need debug IDs to get better error reporting
=> Create sentry.yml for debugID uploads to sentry

.github/workflows/sentry.yml
Theres a potential hiccup with the arguments. it shouldnt be --dist/sourcemaps as thats a path and not a paramater
=> Update sentry.yml to fix arguments

src/PresentationalComponents/PathwaysTable/PathwaysTable.cy.js
Associated Jira ticket: [RHINENG-14746](https://issues.redhat.com/browse/RHINENG-14746)
Add tests checking that categories in Pathways table get abbreviated
run npm test:ct
=> tests for checking categories in pathways table

.github/workflows/webpack.yml
=> fix(sentry): No prefix for sentry uploads

cypress/support/interceptors.js, fec.config.js, src/PresentationalComponents/ExecutiveReport/BuildExecReport.js, src/PresentationalComponents/ExecutiveReport/Download.js, src/PresentationalComponents/ExecutiveReport/NewDownload.js, src/SmartComponents/Recs/List.js, src/Utilities/Api.js
=> feat(RHINENG-3020) Updgrade to pdf-generator v2

src/PresentationalComponents/Inventory/Inventory.js, src/SmartComponents/HybridInventoryTabs/helpers.js
https://issues.redhat.com/browse/RHINENG-11271
=> fix(RHINENG-11271): Fix inconsistent table header capitalization

fec.config.js, package-lock.json, package.json, src/PresentationalComponents/ExecutiveReport/NewBuildExecReport.js, src/PresentationalComponents/ExecutiveReport/NewDownload.js
Based on the landing page template https://github.com/RedHatInsights/landing-page-frontend/blob/master/src/moduleEntries/PdfEntry.tsx
=> Trying a different pdf generator script

.gitmodules, .tekton/advisor-frontend-pull-request.yaml, .tekton/advisor-frontend-push.yaml
Associated Jira ticket: [RHINENG-16149](https://issues.redhat.com/browse/RHINENG-16149)
Use shared `Dockerfile`
=> chore(build): use shared Dockerfile

src/PresentationalComponents/Inventory/Inventory.js, src/Utilities/Hooks.js
https://issues.redhat.com/browse/RHINENG-11884
=> chore(RHINENG-11884): Remove feature flag for Groups-Workspaces rename

src/PresentationalComponents/RulesTable/helpers.js, src/SmartComponents/SystemAdvisor/SystemAdvisorAssets.js
There were 2 more instances where the logo would appear, this removes them
=> fix(RHINENG-16786): Remove remaining ansible icons

package-lock.json, package.json
Associated Jira ticket: [RHINENG-15914](https://issues.redhat.com/browse/RHINENG-15914).
This upgrades dependencies to use axios of the latest version (^1.8.4). This PR should have upgraded javascript-clients as well (as it's the main goal of the ticket), thought Advisor doesn't use any of these clients directly so this is irrelevant.
Make sure the main functionality is preserved, no visual/behavioural changes expected.
```
insights-advisor-frontend ➤ npm list axios                                                                                                                                git:master
advisor-frontend@2.0.0 /Users/gkaratae/insights/insights-advisor-frontend
├─┬ @redhat-cloud-services/frontend-components-charts@3.2.6
│ └─┬ …
```
=> fix(RHINENG-15914): Fix axios CVE and upgrade library to latest version

src/SmartComponents/Recs/DetailsRules.cy.js
=> add new cypress tests

src/PresentationalComponents/RulesTable/RulesTable.cy.js
Associated Jira ticket: # [RHINENG-16325](https://issues.redhat.com/browse/RHINENG-16325)
=> enable skipped cypress tests

package-lock.json, package.json
Updating fec config for the future iop work
=> chore(deps): update fec config for iop work

src/PresentationalComponents/Inventory/Inventory.js
Before the changes:
After the changes:
=> fix(RHINENG-18687): Disable 'Disable recommendation for selected systems' kebab for read-only users

src/Utilities/OnPremiseBridge.js
https://issues.redhat.com/browse/RHINENG-17893
I don't know why I am doing this but hope it helps
=> feat(RHINENG-17893): iop context for sysdetail

fec.config.js, src/Temporary/SatelliteDemoComponent.js
Update for satellite demo component
=> feat(iop): update fec config and satellite component

src/AppConstants.js, src/PresentationalComponents/OverviewDashbar/OverviewDashbar.js, src/PresentationalComponents/OverviewDashbar/__tests__/OverviewDashbar.test.js, src/SmartComponents/Recs/List.js, src/SmartComponents/Topics/Details.cy.js, src/Utilities/Hooks.js, src/Utilities/Hooks.test.js
=> feat(RHINENG-17643): Turn off functions for IOP

src/AppConstants.js, src/Messages.js, src/Modules/SystemDetail.js, src/PresentationalComponents/Inventory/Inventory.js, src/SmartComponents/SystemAdvisor/SystemAdvisor.js, src/Utilities/Hooks.js, src/Utilities/Hooks.test.js
https://issues.redhat.com/browse/RHINENG-17644
1. During testing federated module (advisor tab in inventory details) I discovered that we're not providing env context properly, so I had to add it to the system details component
2. Remediation button text now change depending on the environment we're running in according to the ticket
=> feat(RHINENG-17644): fix env context in fed module and update rem button text

src/SmartComponents/SystemAdvisor/SystemAdvisor.cy.js, src/SmartComponents/SystemAdvisor/SystemAdvisor.js
Fixing a coupld of small issues with mark's PR and updating tests
=> fix(RHINENG-19077): Check if IopRemediationModal is an element

src/SmartComponents/Recs/RecsDetailsWrapped.js
https://issues.redhat.com/browse/RHINENG-19351
=> feat(RHINENG-19351): add wrapper for recs details

src/AppConstants.js, src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js, src/PresentationalComponents/Inventory/Inventory.js, src/PresentationalComponents/RulesTable/RulesTable.js, src/PresentationalComponents/RulesTable/helpers.js, src/PresentationalComponents/SystemsTable/SystemsTable.js, src/PresentationalComponents/SystemsTable/SystemsTableAssets.js, src/SmartComponents/SystemAdvisor/SystemAdvisor.js, src/SmartComponents/SystemAdvisor/SystemAdvisorAssets.js, src/Utilities/Hooks.js, src/Utilities/Hooks.test.js
https://issues.redhat.com/browse/RHINENG-19411
Insights Link contain calls to the chrome api so we need to add a toggle for it
=> feat(RHINENG-19411): add toggle for insights link that replaces it with regular link

src/Services/SystemVariety.js, src/Utilities/Api.js, src/ZeroStateWrapper.js
Improved the way we replace the base url in the system variety API calls
Made it consistent with the other API calls
=> feat(iop): update system variety api call description

src/Services/SystemVariety.js
Updated zero state wrapper api calls to fix the bug with zero state appearing when it shouldn't
=> fix(bug): fix zero state bug

src/Utilities/Api.js
Fixing the 500 error in update for api requests I made
=> fix(bug): zero state wrapper bug hotfix 2

src/PresentationalComponents/Inventory/Inventory.js
Return back the old condition for "isDisabled" because we updated it incorrectly
=> fix(iop): hotfix playbook button

src/PresentationalComponents/Inventory/Hooks/useBulkSelect/useBulkSelect.js, src/PresentationalComponents/Inventory/Inventory.js, src/PresentationalComponents/Inventory/helpers.js, src/PresentationalComponents/RulesTable/RulesTable.cy.js, src/PresentationalComponents/RulesTable/RulesTable.js, src/SmartComponents/HybridInventoryTabs/ConventionalSystems/RecommendationSystems.js
* Remove kebab to disable rule
* Remove kebabs to disable rules for selected systems
* Disable system checkboxes for rules without playbooks
Screenshot showing missing kebab to disable rules:
Screenshot showing missing kebab to disable for selected systems, and disabled checkboxes for rules without playbooks:
=> fix(RHINENG-20042): Fix minor bugs in IOP env

src/PresentationalComponents/ExecutiveReport/BuildExecReport.js, src/PresentationalComponents/ExecutiveReport/Download.js, src/SmartComponents/Recs/ListHeader.cy.js
Associated Jira ticket: # ([RHINENG-19586](https://issues.redhat.com/browse/RHINENG-19586))
Adding feature flag to PDF generation
1. Follow instructions from here to test this PR https://github.com/RedHatInsights/compliance-frontend/pull/2515#issue-3178630283 
2. Navigate to Advisor recommendations page
3. Click on download PDF
4. Observe "Lightspeed" is used if Feature flag is enabled
=> feat(RHINENG-19586): Use Lightspeed feature flag for PDF

src/SmartComponents/HybridInventoryTabs/HybridInventoryTabs.js, src/SmartComponents/HybridInventoryTabs/HybridInventorytabs.test.js, src/SmartComponents/Recs/Details.js, src/SmartComponents/Recs/DetailsPathways.js, src/SmartComponents/Recs/DetailsTitle.js, src/SmartComponents/Recs/DetailsTitle.test.js, src/SmartComponents/Recs/IopRecommendationDetails.js, src/SmartComponents/Recs/helpers.js, src/SmartComponents/Recs/helpers.test.js
https://issues.redhat.com/browse/RHINENG-19581
I removed parts of the code that are referring to Immutable tab and "edge systems" from the app
Things like Immutable filter will be updated and changed in a separate PR. 
how to test:
Due to the fact that immutable tab is already removed from hybrid inventory tab module component in inventory - you won't see any changes. This is mostly a cleanup
=> feat(RHINENG-19581): remove edge systems tab code
