src/SmartComponents/Actions/ViewActions.js
src/SmartComponents/Actions/_actions.scss

When `componentDidMount()` fires, the class is taken away. Moving that statement inside that function so it doesn't get overwritten.

Fixing class on ViewActions not always loading

---

src/SmartComponents/Actions/ViewActions.js
src/SmartComponents/Rules/ListRules.js

Currently, if I run this app just cloned from the repo, response.rules
is empty. Therefore when I visit the Actions or Rules pages I don't see
anything but an error message that you can't call .length on an
undefined method. This commit fixes that problem.

Allow lists to show with no items

---

package-lock.json
package.json
src/App.scss
src/Routes.js
src/SmartComponents/Actions/ActionsOverview.js
src/SmartComponents/Actions/ListActions.js
src/SmartComponents/Actions/ViewActions.js
src/SmartComponents/Actions/_actions.scss
src/SmartComponents/Rules/ListRules.js
src/index.html

Relies on: [Insights-Chrome#24](https://github.com/RedHatInsights/insights-chrome/pull/24)
This introduces layouts with the new chroming service. Also introduces the `Main` component. This previously was held by the `<Section type='content>` (which is still valid), but not to be used to wrap the page. 
If you want to review this PR, you *must* be running that branch of chrome with `LOCAL_CHROME=true` until it gets merged into prod.

Updating layout and pages to use new chroming service

---

src/SmartComponents/Actions/ActionsOverview.js
src/SmartComponents/Actions/ViewActions.js

fixes RHIADVISOR-196
unlike the beta tho,` https://foo.com/morefoo/actions/` will just redirect you home to advisor so we don't so much need to worry about the titleless case (though, just in case 's set to an empty string)

Adds action url title helper, ensures urls match beta 

---

src/PresentationalComponents/RulesCard/RulesCard.js
src/PresentationalComponents/Skeletons/RulesCard/RulesCardSkeleton.js
src/PresentationalComponents/SummaryChart/SummaryChart.js
src/PresentationalComponents/SummaryChartItem/SummaryChartItem.js
src/SmartComponents/Rules/ListRules.js

QE wants us to add `widget-type='InsightsFoo'` to any presentational components on the top level tag. This way they can use their DOM scanner appropriately. 
If there are multiple instances of the same widget on a page, there needs to be a separate `widget-id` that can identify it.
These only need to be applies to Insights specific components. Patternfly is doing the same thing. I will also be updating the component library to follow the same pattern.

Adding widget attributes

---

src/Store/index.js

Its a bummer not being able to use redux-devtools so till a day comes when a solution can be found whilst importing this class, gonna copy n paste it here (cuz this works) https://github.com/RedHatInsights/insights-frontend-components/blob/master/src/Utilities/ReducerRegistry.js#L25

Imports ReducerRegistry from insights-frontend-component, fixes devtools

---

package-lock.json
package.json
src/App.js
src/SmartComponents/Actions/Actions.js
src/SmartComponents/Actions/ActionsOverview.js
src/SmartComponents/Actions/ListActions.js
src/SmartComponents/Actions/ViewActions.js
src/SmartComponents/Rules/ListRules.js

This PR is blocked by https://github.com/RedHatInsights/insights-frontend-components/pull/116
* Use router params - QE has easier definition where they are located so they have much easier job.
* Use component's registry - this way we don't have to take care of our registry, but this can be maintained from component's registry. So any changes did to this registry will take effect in this one as well.

Use router params and set redux registry from frontend component

---

.babelrc
README.md
config/spandx.config.js
package-lock.json
package.json
src/App.js
src/AppActions.js
src/AppConstants.js
src/AppReducer.js
src/PresentationalComponents/Inventory/Inventory.js
src/PresentationalComponents/RulesCard/RulesCard.js
src/SmartComponents/Actions/Actions.js
src/SmartComponents/Actions/ActionsOverview.js
src/SmartComponents/Actions/ListActions.js
src/SmartComponents/Rules/ListRules.js

we need 
* ~~https://github.com/RedHatInsights/insights-advisor-api/issues/92~~ https://github.com/RedHatInsights/insights-advisor-api/pull/106
* ~~RHIADVISOR-216 Return system list for a given rule~~ https://github.com/RedHatInsights/insights-advisor-api/pull/107
* we also need this https://ansible.slack.com/archives/CADT032B0/p1539553048000200 which is a 
> For an individual rule, we can include a list of system UUIDs that are affected by that rule.  That's not too difficult, it's a query on the reports.
* ~~consume https://github.com/RedHatInsights/insights-frontend-components/tree/master/src/SmartComponents/Inventory to display affected systems~~
* ~~and we need https://github.com/RedHatInsights/insights-frontend-components/pull/139/ …

Adds api support to listactions component

---

README.md
src/Utilities/Api.js

fixes #86
A note about this... yer gonna have to stub the `x-rh-auth-identity:{ "identity": { "account_number": "1234567"}}` header for this to be agreeable on dev

This header stub is no longer required for successful api interactions!😁

---

src/PresentationalComponents/Inventory/Inventory.js
src/PresentationalComponents/Inventory/InventoryDetails.js
src/PresentationalComponents/Inventory/InventoryRuleList.js
src/SmartComponents/Actions/Actions.js

updated inventory component means details view is no longer a tab, its it's own page https://github.com/RedHatInsights/insights-frontend-components/blob/master/doc/components/inventory.md#usage-of-hot-loading
[**to get this alive follow the steps drawn out here** 
](https://github.com/RedHatInsights/insights-advisor-frontend/pull/100)

Update hotloading inventory as per new docs

---

src/SmartComponents/Actions/ViewActions.js

https://github.com/RedHatInsights/insights-advisor-api/pull/149 means we can do this
This makes the donut on the front page not a liar, when you click to see `Stability(4)` you see 4 items

Viewactions component only shows impacted systems

---

src/AppActions.js
src/AppConstants.js
src/SmartComponents/Actions/ListActions.js

Its a (potentially giant)  array called host_ids

Systems impacted by a rule are now accessed by appending /systems 

---

src/SmartComponents/Actions/ListActions.js

We no go off and fetch the kba view_uri using the node_id to ensure we're getting the right one every time, won't show the link if there isn't anything to show
Followup work will transfer this same thing to the inventory rule list

Ensure correct kba link is used for rules

---

package-lock.json
package.json
src/PresentationalComponents/Cards/RulesCard.js
src/SmartComponents/Actions/ListActions.js
src/SmartComponents/Rules/ListRules.js

In response to https://github.com/RedHatInsights/insights-advisor-api/pull/165
This will also be added https://github.com/RedHatInsights/insights-frontend-components/tree/master/src/SmartComponents/Inventory/applications/advisor

Removes depreciate _html attribute and process md/html on client

---

src/AppConstants.js
src/SmartComponents/Actions/ListActions.js
src/SmartComponents/Rules/ListRules.js

Cuz the work making this attribute available was merged https://github.com/RedHatInsights/insights-advisor-api/pull/169/files

Update resolution_risk to use rhel .risk value

---

src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js
src/SmartComponents/Actions/ListActions.js
src/SmartComponents/Actions/ViewActions.js

Reverts RedHatInsights/insights-advisor-frontend#149
This pr ended up being a regression, upon refreshing the page, breadcrumbs will break the app, `Uncaught TypeError: Cannot read property 'navigate' of undefined`

Revert "Refactor breadcrumbs to make them match based"

---

src/PresentationalComponents/Inventory/Inventory.js

Sorry for the on and off again with this one... keeps cropping up sporadically, so we rewip
Ends up whenever loading the inv component for the first time, this error gets thrown
Now we throw in an empty object to keep it from freaking out, has no other side effects

[WIP] Resolves PaginationRow Undefined error when loading inventory component

---

src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js
src/PresentationalComponents/Inventory/InventoryDetails.js

Adds breadcrumbs and additional visual enhancements to inv details

---

src/PresentationalComponents/Cards/RulesCard.js

Ensure prop type passed is one expected

---

src/App.js
src/Routes.js

This will allow users to bookmark and refresh without redirecting to root URL. If there are some malicious data or wrong URL that does match `/actions` or `/rules` but has something wrong after it we have to react to it and either show some error msg or redirect them to correct URL, but that is not part of this PR.

Update routing so refreshing does not redirect to root everytime

---

src/SmartComponents/Actions/ListActions.js
src/SmartComponents/Actions/ViewActions.js
src/SmartComponents/Rules/ListRules.js

Updated all Total Risk battery icons to be bound to `total_risk` rather than `severity`.
Fixes RHIADVISOR-414

Change battery icon to use total_risk rather than severity

---

src/AppConstants.js
src/SmartComponents/Actions/ActionsOverview.js
src/SmartComponents/Actions/ViewActions.js

to be merged with https://github.com/RedHatInsights/insights-advisor-api/pull/183
TODO: build the constant by querying `.../v1/rulecategory/`

Supports category queries by id# rather than string

---

src/AppConstants.js

Need to track down where 'Is an Incident' data gets pulled from next.  Fixes #195.

Rename values in filters to identify Low Total Risk filter

---

src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js
src/PresentationalComponents/Inventory/InventoryDetails.js
src/SmartComponents/Actions/ActionsOverview.js
src/SmartComponents/Actions/ListActions.js
src/SmartComponents/Actions/ViewActions.js

Refactored Breadcrumb is now class-based and reduces the dependencies required of parent components.  On Inventory page, breadcrumbs now use the Rule description instead of the id 
Fixes RHIADVISOR-401
Before:
After:

Fixes breadcrumb using rule.id

---

src/PresentationalComponents/Filters/Filters.js

Spaces are bad. We get rid of them so the get doesn't have `+`s

---

src/SmartComponents/Actions/ViewActions.js

fixes https://projects.engineering.redhat.com/browse/RHIADVISOR-435
once https://github.com/RedHatInsights/insights-advisor-api/pull/189 gets in, this'll work just fine 
also, `impacted_systems_count` and `has_playbook` are fields we could also use sorting on
~~this is a wip cuz we get a big ol' **500** when sorting as per https://github.com/RedHatInsights/insights-advisor-api/pull/166
`Request URL: https://prod.foo.redhat.com:1337/r/insights/platform/advisor/v1/rule/?page=1&page_size=10&impacting=true&category=1&order_by=likelihood` makes it 💥~~
~~cuz it blows up all 500 like~~
unsure why 🤷‍♂️ 
need help 🚁 
send answers 🆘 
@PaulWay  🙇 🤗

RHIADVISOR-435 - Viewactions now uses patternfly4 table and sorts with api

---

src/PresentationalComponents/Filters/Filters.js
src/SmartComponents/Actions/ViewActions.js

fixes https://projects.engineering.redhat.com/browse/RHIADVISOR-446
Default sorting of rules is by rule_id ascending, `sort` hates empty params, so we pass the default in to keep it happy
tl;dr you can now clear filters set by the overview page (total_risk and category) this work does not include RHIADVISOR-445 
🌮 💃

Reconfigure all Actions table filters to configurable (including url)

---

src/PresentationalComponents/RulesTable/RulesTable.js
src/SmartComponents/Actions/ViewActions.js
src/SmartComponents/Actions/_actions.scss
src/SmartComponents/Rules/ListRules.js

tl;dr - "Rules" tab now navigates to a unfiltered rule table!  yay. and this dry's out a bunch of stuff, more to folllllloooooowwwww
Fixes https://projects.engineering.redhat.com/browse/RHIADVISOR-450
SO this pr begets another, one where we do a crap tonne of cleanup, removing unused components n such, also right now, `ListRules` and `ViewActions` do the same thing (act as a 🏠 for rulestable) and should be named the same, thinking of renaming `ViewActions to `ListActions` and renaming `ListActions to... something that makes sense... cuz its the component for viewing a single rule

Abstracts ruletable to component, sets rules/actions lists to consume

---

src/AppConstants.js
src/PresentationalComponents/RuleDetails/RuleDetails.js
src/PresentationalComponents/RulesTable/RulesTable.js
src/SmartComponents/Actions/ViewActions.js

don't worry about the ansible icon being black (or the change from `has_playbook` to `playbook_count` this is a change already present on ci)

Adds expandable table to rules table

---

src/PresentationalComponents/RuleDetails/RuleDetails.js

Response headers
```
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
access-control-allow-methods: POST, GET, OPTIONS, DELETE, PUT
access-control-allow-headers: Content-Type, X-PINGOTHER, X-Omit, Authorization
access-control-allow-credentials: true
server: Apache-Coyote/1.1
cache-control: private
expires: Thu, 01 Jan 1970 00:00:00 UTC
access-control-max-age: 1728000
access-control-expose-headers: Content-Length, Location, View-Uri, view_uri, Uri
content-type: application/vnd.redhat.solr+json
content-encoding: gzip
vary: Accept-Encoding
date: Fri, 08 Mar 2019 16:23:32 GMT
connection: close
set-cookie: strata_auth_type=JWT_AUTH
3af49a4941ac0b71696b53a498d081ee=90ef3f4add2beecdc2bfa6b22d128542; path=/; HttpOnly
transfer-encoding: chunked
```
###and no error in ff!

Adds header to kba request, avoids throwing an xml parsing error in ff

---

src/SmartComponents/Actions/ListActions.js

Fixes what #224 broke
Chart nav from overview to rule table is now fixed

Title.split creates array, address by index, fixes overview chart nav

---

src/PresentationalComponents/Charts/ActionsOverviewDonut.js

slight roll back from #251
fixes #253

Restores donut outer most div, dashboard doesn't scale well without

---

src/PresentationalComponents/RulesTable/RulesTable.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-522

Resets page to 1 whenever any filtering is performed, keeps the api 😊

---

src/SmartComponents/Actions/ViewActions.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-552

Incorrectly displaying 0 for remediation button when playbook_count === 0

---

src/PresentationalComponents/Charts/ActionsOverviewDonut.js

fixes #155
jira https://projects.engineering.redhat.com/browse/RHCLOUD-601
you'll notice the top margin matches the risk severity list

Adds empty state to donut (when totalhits = 0)

---

src/PresentationalComponents/Charts/SummaryChart/SummaryChart.js
src/SmartComponents/Actions/ActionsOverview.js

Fixes misplaced empty donut style, rendering unnecessary 0, and severity chart hit misreporting

---

src/PresentationalComponents/Charts/ActionsOverviewDonut.js
src/Routes.js
src/Utilities/getBaseName.js

kinda fixes https://projects.engineering.redhat.com/browse/RHCLOUD-652
~This isn't a perfect fix, still does the following things:~
* ~redirects you to `/insights/undefined/actions` when `/insights` is the base url~
* ~redirects you to `/insights/actions/actions` when `/insights/actions/actions` is the base url~
[this lil nugget fixes the above issues ☝️ ](https://github.com/RedHatInsights/insights-advisor-frontend/pull/274/files#diff-b4e6341a734a41d9f7a2517ea5faaaaaR14) @iphands is 🍕 
but both of these are edge cases, fixes death by spinner, will make the app infantile more pleasant to use... followup work is to fix both of the above issues...

Resolves routing issues for `/insights`, `/insights/` and `/insights/actions`

---

src/AppActions.js
src/AppConstants.js
src/AppReducer.js
src/SmartComponents/Overview/Dashboard.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-702

Separates /stats into /stats/rules and /stats/systems

---

src/SmartComponents/Overview/Dashboard.js

works!  our issue ended up being local state wasn't updated in the didupdate, but the props indicating resources were loaded were updated

Refactor severity chart to rely on props rather than local state

---

package-lock.json
package.json

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-721
includes https://github.com/RedHatInsights/insights-frontend-components/pull/383
this removes the external icons from links in reports on a system... we'll have to circle back around and find a better way to do that or fix the react dep that breaks when minified

Removes external link icon markup from reports, it was breaking prod

---

config/base.webpack.plugins.js

So it turns out simply adding files to the static directory does not get them copied to the build output.  The API static files will now be properly copied to the output when built.

Copy api static files to build output

---

src/PresentationalComponents/RulesTable/RulesTable.js

Ends up we don't need itemsStart for pagination component

---

src/SmartComponents/Overview/Dashboard.js
src/SmartComponents/Overview/Dashboard.scss

Swaps dashboard gallery for level

---

src/PresentationalComponents/RulesTable/RulesTable.js

fixes https://docs.google.com/spreadsheets/d/1xbzvLhRUd0o27CIk1MOQWbpYMpJXktx3HUpI2MAjpk4/edit?ts=5cc0cc87#gid=967324608

As per ux design, going with large table rather than compact

---

src/SmartComponents/Overview/Dashboard.js
src/SmartComponents/Overview/Dashboard.scss

Adds padding between the charts when collapsed

---

src/PresentationalComponents/Inventory/Inventory.js

There's been a change to how inventory is fetching next pages, it used to handle pagination for ourselves, but it has changed in more robust way and now we have to paginate on our side.
In memory as of for now, we should call get current page on each `onRefresh` call so we get newest data.

Add pagination function to affected systems

---

package-lock.json
package.json

includes https://github.com/RedHatInsights/insights-frontend-components/pull/434

Now all system detail bullets are the same size

---

src/SmartComponents/Overview/Dashboard.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-1214
just gotta point out, the ansible link and the button redirect to the same place

Changes dashboard link url

---

src/PresentationalComponents/RulesTable/RulesTable.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-1216

Set default rules view to be sorted by newest first

---

src/PresentationalComponents/RulesTable/RulesTable.js

the pf class we were using, `pf-u-justify-content-space-between` decided to disappear, so giving up on that, gonna hardcode the style as much as it pains me.

Switch from flakey class to hardcoded style 

---

package-lock.json
package.json
src/PresentationalComponents/Charts/OverviewDonut.js
src/PresentationalComponents/Charts/OverviewDonut.scss

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-1433
[pf friends updated the donut to be better, so we'll update the donut to be better](http://patternfly-react.surge.sh/patternfly-4/charts/chartdonut/)
**Notes**
* all behavior, aside from mouseover slice highlight, is preserved (but that wasn't ever a pf thing to begin with)
* satisfies https://redhat.invisionapp.com/share/V4NY3C6XKRW#/357403104_Donut_Interactions
* uses bunches of less code 🤤

Update overview donut to better align with pf styles (black tooltip)

---

src/PresentationalComponents/Filters/Filters.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-1434
Plus this matches with what pf wants http://patternfly-react.surge.sh/patternfly-4/components/inputgroup/

Update search input align with the styles used elsewhere in insights

---

src/AppReducer.js
src/PresentationalComponents/Charts/OverviewDonut.js
src/PresentationalComponents/Charts/SummaryChart/SummaryChartItem.js
src/PresentationalComponents/Filters/FilterChips.js
src/PresentationalComponents/Filters/Filters.js
src/PresentationalComponents/RulesTable/RulesTable.js
src/SmartComponents/Overview/List.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-1535

Persists rule table filters in state, previously reset upon didUnmount

---

src/PresentationalComponents/Filters/FilterChips.js

Searching blows up cuz filter chips wants to register the input as a chip, which we _could_ do, but won't/shouldn't

Remove search text from filter chips

---

src/PresentationalComponents/RulesTable/RulesTable.js

This doesn't address the invalid form event bubbling up n making the input red though

0 - 0 of 0 items is the correct value to display when results are absent

---

src/PresentationalComponents/Charts/SummaryChart/SummaryChart.js
src/PresentationalComponents/Charts/SummaryChart/SummaryChartItem.js

mock looks like this https://marvelapp.com/i4441ie/screen/58398625

Update severity chart labels to be consistent with rest of app

---

src/PresentationalComponents/RulesTable/RulesTable.js
src/SmartComponents/Rules/ListRules.js

tl;dr - this pr cleans out a the `summary` code that current mocks no longer support (a carryover from ~~legacy~~  ~~classic~~  oldsights) what we gain is smaller margins, this work also will is gonna lighten the burden on #380 a lil too

Remove summary from Rulestable, we don't and won't be using it

---

src/App.js

Fixes the issue of overview not showing up as selected by default (because something somewhere else is already selecting it, when we doubly select it, it unhighlights :( )

Only fire the appNavClick if its a nav element we store a click for

---

src/PresentationalComponents/RulesTable/RulesTable.js

this changed here https://github.com/patternfly/patternfly-react/pull/2417
(previous behavior was instant execution on any input)
This is more of a cleanup than anything else, pagination change doesn't negatively effect components execution

Pagination page input now requires enter, no longer requires debounce

---

README.md
config/spandx.config.js

This change makes it easy to switch what API you are talking to.  Just change the `apiHost` in the spandx.config.js

Cleanup spandx config to make it easier to connect to a local api

---

package-lock.json
package.json
src/App.js
src/AppActions.js
src/AppConstants.js
src/AppReducer.js
src/PresentationalComponents/Filters/FilterChips.js
src/PresentationalComponents/TopicCard/TopicCard.js
src/PresentationalComponents/TopicCard/_TopicCard.scss
src/Routes.js
src/SmartComponents/Topics/Details.js
src/SmartComponents/Topics/List.js
src/SmartComponents/Topics/Topics.js
src/SmartComponents/Topics/_Details.scss
src/Store/index.js

Once we merge this, it'll be hidden from lnav until we merge this https://github.com/RedHatInsights/cloud-services-config/pull/21
also this updates `notificationsMiddleware` to display correct message and response data detail

Adds Topics (list/details views) and supporting components

---

src/App.js

Href contains entire location including origin and search field, since we include search field in URL we have to use only pathname to find which app is active.
Also do not update history if we are already on same URL so we remeber search part as well.

Use pathname to determine where user currently is

---

src/SmartComponents/Topics/List.js

Previously, api was returning a 400 when there were no topics, but now its a 200 empty array (what we expect) adding code to cover that case

Empty/error state supports an empty array 200 (signals appropriately)

---

src/PresentationalComponents/RuleDetails/RuleDetails.js

in the case this attribute is missing, we shouldn't tank the whole session

In the case that impact attribute is missing, display undefined text

---

src/SmartComponents/Overview/Dashboard.js

this surprise broke, reverting react-intl version doesn't seem to fix, gonna do this for now, cuz prod mustn't be broken looking

Revert translated text bodies that use html

---

src/SmartComponents/Topics/List.js

Ensure setBreadcrumbs action is dispatched upon visiting /topics

---

src/PresentationalComponents/RuleDetails/RuleDetails.js

Who knew, formatMessage functions that employ html need keys 🤷‍♀️

Resolves missing key warning from RuleDetails component

---

src/SmartComponents/Rules/Details.js

Its taking too long for topics to load, meaning it visibly delays rule details component, gonna render that as soon as we have the data we need, topics will come afterwards

Not gonna stop rule detail from loading while we're waiting for topics

---

src/AppConstants.js

We're having a lil trouble getting this to show up like it ought to, something about passing a translation as a value to another translation string is off... till its figured out, reverting this constant...

Complex translation passing isn't workin, revering this constant till 👍🏽

---

src/PresentationalComponents/Inventory/InventoryDetails.js

Fixes an error that can happen if user tries to go to incorrect inventory detail and then go back to inventory table list. The error is a bit cryptic and does not properly show that incorrect dependency is used.

Pass PF table to inventory detail

---

src/PresentationalComponents/RulesTable/RulesTable.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-2607
`/api/insights/v1/export/hits.json/?total_risk=4&reports_shown=true&impacting=true`
~~returns slightly more (20) than 1 system (which is what we see in the rules table)~~ i am told this is expected
SILVER LINING all systems have `"total_risk":4` which is **AWESOME** 🙇‍♀ 🤗 
text filtering doesn't yet work, but that wont change anything here, so we can go ahead n merge thissss i believe

Adds filtered export support to rules table

---

locales/data.json
locales/translations.json
src/Messages.js
src/PresentationalComponents/Modals/DisableRule.js
src/PresentationalComponents/RuleDetails/RuleDetails.js
src/PresentationalComponents/RulesTable/RulesTable.js
src/SmartComponents/Rules/Details.js
src/SmartComponents/Rules/Details.scss

**TODO:**
* ~api call n such for single system and justification~ https://projects.engineering.redhat.com/browse/RHCLOUD-2986 is where this will be done, but we laid the groundwork here
* ~possibly rolling https://projects.engineering.redhat.com/browse/RHCLOUD-2982  into this one (cuz it would be kinda ah jerk move to allow disabling on rule details without showing it)~ given api toggle is available (enable disable) this can remain separate  
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-2979

Adds disable rule justification modal and action to rule detail page

---

locales/data.json
locales/translations.json
src/AppActions.js
src/AppConstants.js
src/AppReducer.js
src/Messages.js
src/PresentationalComponents/Modals/DisableRule.js
src/PresentationalComponents/Modals/ViewHostAcks.js
src/SmartComponents/Rules/Details.js
src/SmartComponents/Rules/Details.scss

sorry, its a biggie 😭 
almost fixes https://projects.engineering.redhat.com/browse/RHCLOUD-2986
but really just: 
* https://projects.engineering.redhat.com/browse/RHCLOUD-2985
* https://projects.engineering.redhat.com/browse/RHCLOUD-2986
this work is blocked by (but not really, we'll still merge)
* https://projects.engineering.redhat.com/browse/RHCLOUD-3424
**this has one quirk** (that already existed), relating to bulk select, if you select all, then deselect items from the table, unless select none is used (or another bulk action) the table deselect is not reflected (this is because when bulk select was added, inventory didn't support it, so we rolled our own, this has since changed, and updating to inventory bulk select will fix this bug

Adds host ack capability to inv-table, updates messaging to reflect 🦚

---

src/PresentationalComponents/Modals/DisableRule.js

plus brandon said this would be useful 🤗

Ensure disable single system is true by default

---

locales/data.json
locales/translations.json
src/Messages.js
src/PresentationalComponents/Modals/ViewHostAcks.js
src/SmartComponents/Rules/Details.js

Unifies date format across ack work

---

src/AppReducer.js
src/PresentationalComponents/RulesTable/RulesTable.js
src/SmartComponents/Topics/Details.js

if you go between rules table and topics rule table, you default to `Added` (most recently)  that aside, from rules table to anywhere but topics, sorting will be preserved (reflected in url) and direct navigation with `sort=foo` will yield sorted result

Reconfigures rules table to use url to preserve table sorting 

---

src/PresentationalComponents/RulesTable/RulesTable.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-2752
aligns with https://marvelapp.com/i4441ie/screen/58398647

Adds total risk tooltip and label to rules table

---

src/PresentationalComponents/Modals/ViewHostAcks.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-3833

Only run afterFn if modal triggers action (but only once, on close)

---

src/PresentationalComponents/Inventory/Inventory.js

Plays well with bulk actions, page redirect, n edge cases of acking the last page
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-3918
acking a host, if yah were on page 10, would send you back to page 1
* acking a host, if yah were on page 10, will keep you on page 10
* checking host details will not change inv-table page
* navigating away from page and back to will not change inv-table page ~(BUT THIS HAS ONE GOTCHA (that imma fix real quick) navigating between rules won't reset page value)~ but going to away from page and to a different rule *will* reset the page to 1

Inv-table preserves page number after host ack

---

src/PresentationalComponents/RulesTable/RulesTable.js

This will also set it to false if you filter rule status by 'All' does not set it to false by default

Sets impacting=false on the "Include disabled rules" link, empty table 🦹‍♀️

---

package-lock.json
package.json
src/SmartComponents/Topics/Topics.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-4129
so now, if yah have the user flag `is_internal` yah can go to the topics admin table, else redirect to topic.. important part of this work is, we only ever check if you try to go to /admin/manage/ (opposed to of every time topics route is loaded)

Fix topics admin protected route - set a pattern for app route rbac

---

src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js
src/PresentationalComponents/Breadcrumbs/_breadcrumbs.scss

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-4180

Breadcrumbs are no longer upper case

---

locales/data.json
locales/translations.json
src/AppConstants.js
src/AppReducer.js
src/Messages.js
src/PresentationalComponents/RuleLabels/RuleLabels.js
src/PresentationalComponents/RuleLabels/_RuleLabels.scss
src/PresentationalComponents/RulesTable/RulesTable.js
src/SmartComponents/Rules/Details.js

So this work adds the incident badge and encapsulates all rule badges in one component. It adds an `incident` filter that is by default, always set to true (kinda like how we have enabled rules set to true by default). It also adds a tooltip for disabled rule badge.  (mocks here https://marvelapp.com/i4441ie/screen/63574982)
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-3648 https://projects.engineering.redhat.com/browse/RHCLOUD-3649 https://projects.engineering.redhat.com/browse/RHCLOUD-3650 https://projects.engineering.redhat.com/browse/RHCLOUD-3651

Replaces badge (incident/disabled) with label component

---

src/PresentationalComponents/Common/Tables.js
src/PresentationalComponents/RulesTable/RulesTable.js
src/PresentationalComponents/SystemsTable/SystemsTable.js

So now when you select a page or per page and navigate away from the table, upon returning previous values will persist

Persist limit n offset across app for rules/systems tables 👾

---

.travis/custom_release.sh

in order to support the new dashboard n app consolidation efforts, advisor has gotta be able to target qa/ci beta specifically, this app allows us to do that while keeping everything else the same

Release branches to support master-beta -> master -> master-stable

---

src/PresentationalComponents/Charts/SystemInventory.js

followup to https://projects.engineering.redhat.com/browse/RHCLOUD-3832 and https://projects.engineering.redhat.com/browse/RHCLOUD-4190 we now consume the correct endpoints and the systems list returns non-nulls for `stale_at`

Consumes api updates to culling attributes on stats endpoint

---

src/AppActions.js
src/PresentationalComponents/Modals/DisableRule.js
src/SmartComponents/Rules/Details.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-5007
dupe of https://github.com/RedHatInsights/insights-advisor-frontend/pull/579/ for prod-beta
works fine with host_ack actions n rule enable/disable

 Adds tagging support to rec details page

---

src/PresentationalComponents/TagsToolbar/TagsToolbar.js
src/PresentationalComponents/TagsToolbar/_TagsToolbar.scss

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-5141
cc @kybaker

Disables tag dropdown when there aren't any tags

---

src/PresentationalComponents/TopicsTable/TopicsTable.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-4011

Removes trailing slash from topics detail, matches recs table

---

src/PresentationalComponents/TagsToolbar/TagsList.js
src/PresentationalComponents/TagsToolbar/TagsToolbar.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-4917

Encoded tags are decoded where rendered! 🥳

---

src/PresentationalComponents/TagsToolbar/TagsToolbar.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-5347
Activated on hover, can't copy/paste names n such

Tooltip to tag select, (for those really long tags) ⚜️

---

src/SmartComponents/Rules/Details.js
src/SmartComponents/Rules/Details.scss
src/SmartComponents/Topics/Details.js
src/SmartComponents/Topics/_Details.scss

This PR is in response to RHCLOUD-5244 (page 3 of the google doc). We are adding large bottom margins to the `Affected Systems` title.

[RFR] Add large margins to Affected Systems Title

---

src/AppConstants.js
src/SmartComponents/Rules/Details.js
src/cveToRuleid.json

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-4989
when ah smattering of cve's map, we'll send users to a random one
when we don't have a cve and its just text, we'll send users to cve table

Redirects cve rule details to appropriate vul-fe page

---

src/PresentationalComponents/RulesTable/RulesTable.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-5548

Update rec table empty state icon (size type

---

src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-4186

Removes duplicate rec detail breadcrumb

---

src/PresentationalComponents/RuleDetails/RuleDetails.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-5802
displays summary on rec table dropdown
displays generic on detail page

Adds generic rec details to details component (details page only)

---

src/SmartComponents/Rules/Details.js

This is one of the changes suggested in RHCLOUD-5244, and can be found on page 4 of the google doc attached to that ticket. 
Currently the actions dropdown looks like:
But now we get:
🥳

Move dropdown position to onscreen

---

src/PresentationalComponents/TagsToolbar/TagsList.js

This PR is in response to RHCLOU-5628. It adds a useEffect and useState to 🤞 fix the issue where tags are remaining checked in the modal. Here's where you can find an example of this happening: https://projects.engineering.redhat.com/browse/RHCLOUD-5628. Here's what it should do:
1. Before closing the chips
2. After closing a chip

[RFR] Fix bug where tag checkboxes remain checked

---

src/PresentationalComponents/Inventory/Inventory.js

This PR is in response to RHCLOUD-5889, and it disables the action in the kebab dropdown menu on the inventory table when `selected.length === 0`.
Before:
After:

Turn off disable recs when selected.length = 0 in inventory

---

src/PresentationalComponents/ExecutiveReport/Download.js

This will render the button on initial render and everytime loading changes, so it'll prevent multiple renders.

Prevent multiple rendering when changing tabs

---

src/SmartComponents/Rules/Details.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-5934
makes redirect urls look like... `/insights/vulnerability/cves/CVE-2019-0154?security_rule=CVE_2019_0155_gpu_kernel|CVE_2019_0155_GPU_KERNEL`

Changes cve redirect as per divine guidance 🥰🎈 

---

src/SmartComponents/Rules/Details.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-5985

Fetch hostacks only once we have a rule_id, prevents dupe calls

---

src/PresentationalComponents/SystemsTable/SystemsTable.js

This PR is for RHCLOUD-5247. It makes all the pagination on the Systems Table compact per the doc.
Before:
After:

Make system table pagination compact

---

src/PresentationalComponents/Modals/DisableRule.js

This PR is in response to page 5 of RHCLOUD 5247. It allows the user to press the enter key after adding justification for disabling a rule.

Add key press handler for disable rule modal

---

src/PresentationalComponents/RuleDetails/RuleDetails.js
src/PresentationalComponents/RuleDetails/_RuleDetails.scss

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-6064
this is the wrong fix. adding css to content to make it look the same everywhere, when the content oughta be written in markdown, s just plain wrong.  alas, here we are 🔪🦹‍♀️😢

In lieu correct MD, adds styles to generic content, to match satellite

---

src/PresentationalComponents/Inventory/Inventory.js

This PR addresses RHCLOUD-5246 page 4. We are not getting a notification every time a playbook is created. This updates the Inventory component to either pass a successful notification or let the user know there's been some sort of error if either the remediation is not returned or if the notification fails to post.
I'm not sure if this is the intended fix. So just let me know 😁 🥳

Add error handling for remediations

---

src/PresentationalComponents/Common/Tables.js
src/PresentationalComponents/RulesTable/RulesTable.js
src/PresentationalComponents/SystemsTable/SystemsTable.js
src/PresentationalComponents/TagsToolbar/Common.js
src/PresentationalComponents/TagsToolbar/TagsList.js
src/PresentationalComponents/TagsToolbar/TagsToolbar.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-6366
* as tags are selected, they'll show up in the url or be removed from it
* when navigating to ah page that has tags in the param, values on the page will reflect those tags
* navigating between pages, they'll be preserved, tags
* most importantly, everything works with even doofy tags `insights-client/contact=jcordes%40redhat.com` ie `tags=insights-client%2Fcontact%3Djcordes%2540redhat.com`

Tags query param mirrors component selectedTag value 💪😝🥺😵

---

src/AppReducer.js
src/PresentationalComponents/Common/Tables.js
src/PresentationalComponents/RulesTable/RulesTable.js
src/PresentationalComponents/SystemsTable/SystemsTable.js
src/PresentationalComponents/TagsToolbar/Common.js
src/PresentationalComponents/TagsToolbar/TagsToolbar.js
src/SmartComponents/Rules/Details.js
src/SmartComponents/Topics/List.js

SO NOW we should....
* be able to navigate around app, tables  have filters persist correctly (restoration of a regression)
* only send call once tags on url have been sorted, means we'll see the response with data affecting the selected tags
* 🤸‍♀️🎈💰

Rec/sys table, dedupes tag calls, fixes param filter overwrite

---

src/AppReducer.js
src/Store/index.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-6403
SO what we do here with this work is propagate advisor store into sessionStorage and use it to hydrate the store on app load. The goal being, when you navigate away from advisor then return all filter settings will be preserved/restored.

Adds support for local storage, persists state with valid value

---

src/cveToRuleid.js

SMBloris isn't actually a CVE rule afterall, so remove it from the map in cveToRuleid.js

Update cveToRuleid mapping to remove SMBloris rules

---

locales/data.json
locales/translations.json
src/AppConstants.js
src/Messages.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-6609

Modifies titles for Likelihood & Impact scale

---

src/AppActions.js
src/PresentationalComponents/Inventory/Inventory.js
src/SmartComponents/Rules/Details.js

fixes half of https://projects.engineering.redhat.com/browse/RHCLOUD-5679 still have to sort by updated, a trivial change once this is merged though
closing #635 in favor of this and a follow-on whenever the api support shows up

Adds sorting to name column of rec details inventory table

---

src/AppConstants.js
src/PresentationalComponents/RulesTable/RulesTable.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-6191
plays well with all the persistence jazz we've come to expect

Adds reboot required filter to rec table

---

src/Messages.js
src/PresentationalComponents/Common/DownloadHelper.js
src/PresentationalComponents/Common/Tables.js
src/PresentationalComponents/RulesTable/RulesTable.js
src/PresentationalComponents/SystemsTable/SystemsTable.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-6510
also improves file download name

Adds json/csv export to system table

---

src/Messages.js
src/PresentationalComponents/TagsToolbar/TagsToolbar.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-6742

Manage all tags text always available 🤗👩‍🏭 

---

src/PresentationalComponents/TagsToolbar/TagsToolbar.js

Not sure if this is intended or a (very minor) bug ... but I found if you open the TagsToolbar dropdown, it 'remembers' the previous search text and hence filters the list, but the input box is empty.  Thus you might be unsure/confused why you aren't getting a full list of tags being displayed in the drop down.  This PR populates the input box with the previous search term so you know what it was and why the list is being filtered.
The other alternative is to `setSearchText('');`so there isn't any filtering and you get the full list of tags.
How to reproduce 'problem' ...
1. Open the tags toolbar dropdown
2. Enter in some text in the filter tags search textbox to filter the tags, eg 'ocp'
3. Click away from the filter tags dropdown to close it
4. Open the tags toolbar again
5. The tag …

Set Input's value to searchText when TagToolbar dropdown opens

---

locales/data.json
locales/translations.json
src/Messages.js
src/PresentationalComponents/RulesTable/RulesTable.js
src/PresentationalComponents/RulesTable/_RulesTable.scss

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-7224

Changes rec table filter text

---

src/PresentationalComponents/Inventory/Inventory.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-5270

When perpage is less than length, hide selection option (rec details)🛠

---

src/PresentationalComponents/TagsToolbar/TagsToolbar.js

This fixes the issue of tags not being fetched when the component mounts. This is because the debounce function is not being run ahead of time (as it was previously). This is a super hacky (but effective) way to make sure that the tags get fetched on mount by forcing the debounce function to run 💯

Force-trigger debounce to fetch tags on mount

---

src/PresentationalComponents/Inventory/Inventory.js
src/PresentationalComponents/Inventory/InventoryDetails.js
src/PresentationalComponents/SystemsTable/SystemsTable.js

We are working on inventory refactoring, since we'd like to fully use hooks and such we have to use App's react dependency. With this being used react-redux needs to be passed from application as well. If you are cautious about the size of your bundle I can pick only the functions really required by inventory.

Pass react redux to inventory loader as well

---

src/PresentationalComponents/TagsToolbar/TagsToolbar.js
src/PresentationalComponents/TagsToolbar/_TagsToolbar.scss

The inventory tags dropdown has key=value.  Modifying ours to match.  Also allowing the width of the dropdown to change to match the max width of the longest key=value text.

Add key=value to tags toolbar

---

src/PresentationalComponents/RulesTable/RulesTable.js

This PR is in response to RHCLOUD 8052. Mohan pointed out that the sorting was borked on the rules table. This adds `resolutionRisk` as a sort index, which resolves the issue.

Update sort indices on rules table

---

package-lock.json
package.json
src/PresentationalComponents/TagsToolbar/ManageTags.js

This PR adds the config for filter chips on the Tags Modal. This will be ready to go once we get https://github.com/RedHatInsights/frontend-components/pull/645 and the deps updated appropriately. Here's what they look like.
Here's what happens if you select a lot of different tags.

Add filter chips to Tags Toolbar

---

src/PresentationalComponents/TagsToolbar/ManageTags.js

@AllenBW @LI0131, I noticed a problem with the ManageTags modal when you close it by cancelling or clicking the X.  The 'selected' variable is set to `[]` so the next time you open the modal, the selected tags checkboxes aren't selected anymore.  The 'selectedTags' global variable still maintains the correct number of selected tags.
How to reproduce the problem:
1. Open TagsToolbar and select a tag (or multiple tags)
2. Click on the link to open the ManagedTags modal
3. Notice the checkboxes for the selected tags will be checked and there are filter chips for the selected tags.  All good so far ...
4. Here's the kicker though ... Click on Cancel (or X) to close the modal
5. Notice in the tags toolbar that it has the correct count for the number of selected tags
6. Open up the modal again …

Maintain selected state across all ManagedTags modal open/closes

---

package-lock.json
package.json

Updating the inventory-insights dependencies to reflect the new changes to the fec repo.
Here's how we're looking:

Update Inv-Insights dep

---

src/PresentationalComponents/RuleDetails/RuleDetails.js
src/PresentationalComponents/RuleDetails/_RuleDetails.scss

This PR addresses [RHCLOUD-8151](https://projects.engineering.redhat.com/browse/RHCLOUD-8151). It updates the way we are spacing elements in the RuleDetails component.
Before:
After:

Correct rule details spacing

---

src/PresentationalComponents/SystemsTable/SystemsTable.js
src/PresentationalComponents/SystemsTable/SystemsTable.scss

@AllenBW, my attempt at https://projects.engineering.redhat.com/browse/RHCLOUD-8282.  Not sure if this is the right way to go about fixing this tho and the last_seen column treatment is a bit experimental.  I've hidden it for a bit when the screen width really squeezes the system name column.  Feel free to close this if you've got something else (ie better :smile:) in mind.

Don't truncate system table column headings

---

src/PresentationalComponents/Inventory/Inventory.js
src/PresentationalComponents/Inventory/InventoryDetails.js
src/PresentationalComponents/SystemsTable/SystemsTable.js

There is a new feature brewing in chrome, building chrome with webpack [1]. This PR passes newly required dependencies. In future we'll use Federated modules [2] so there won't be a need for these changes, but this is required as a mid-step solution.
Also, for enabling A/B testing of inventory detail we are working on new inventory component, for now this component will be undefined so use `React.Fragment` as fallback.
[1] https://github.com/RedHatInsights/insights-chrome/pull/842
[2] https://webpack.js.org/concepts/module-federation/

Pass pf react core to inventory to properly render inventory

---

src/SmartComponents/Recs/List.js
src/SmartComponents/Recs/List.scss

This PR aligns the Recommendations title and the export Executive Report button in the recommendations header.
Before:
After:

Align items in Recs header

---

src/PresentationalComponents/RuleRating/_RuleRating.scss

similar to https://github.com/RedHatInsights/insights-advisor-frontend/pull/698/

Update rule rating success color to align with ansible check

---

src/SmartComponents/Recs/Details.js

This PR is in response to this 🎫  -> https://projects.engineering.redhat.com/browse/RHCLOUD-8490
We are seeing some errors pop up when we navigate to the Rec Details page after unacking a rule in the recommendations table. The source of the issue comes from us not updating the rule in the redux store after unacking the rule. So the value of `reports_shown` is not accurate to the state of the database, and we are getting a 404 from the `/ack` endpoint because of it 🕵️ 🔎 🤔

Add boolean to check if Rule value is up-to-date

---

src/PresentationalComponents/Modals/DisableRule.js

This fixes https://projects.engineering.redhat.com/browse/RHCLOUD-8513
Before:
After:

Remove name from text-input in DisableRule modal

---

src/PresentationalComponents/Inventory/Inventory.js

This PR gives a fix for https://projects.engineering.redhat.com/browse/RHCLOUD-6054. This might not be the desired end fix, but it will make it so the wizard always mounts. It looks like vulnerability has a ticket out for this too.
Before:
After:

Add RemediationButton as dedicatedAction

---

src/PresentationalComponents/RuleDetails/RuleDetails.js
src/PresentationalComponents/RuleDetails/_RuleDetails.scss
src/SmartComponents/Recs/Details.js
src/SmartComponents/Recs/Details.scss

Fixes some of the styling for compact mode
Before:
After:

Update RuleDetails for compact mode

---

src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js
src/SmartComponents/Recs/List.js
src/SmartComponents/Systems/List.js
src/SmartComponents/Topics/List.js

fixs https://projects.engineering.redhat.com/browse/RHCLOUD-8445

Prepends 'Advisor' to all page titles/breadcrumbs

---

src/AppConstants.js
src/entry-dev.js
src/entry.js

For the translations, we rely on the browser's language, which we can get from `navigator.language`  in JS.  
This returns a string code which is defined in `BCP 47`
This is the list of available locales 
```
ar-SA Arabic Saudi Arabia
cs-CZ Czech Czech Republic
da-DK Danish Denmark
de-DE German Germany
el-GR Modern Greek Greece
en-AU English Australia
en-GB English United Kingdom
en-IE English Ireland
en-US English United States
en-ZA English South Africa
es-ES Spanish Spain
es-MX Spanish Mexico
fi-FI Finnish Finland
fr-CA French Canada
fr-FR French France
he-IL Hebrew Israel
hi-IN Hindi India
hu-HU Hungarian Hungary
id-ID Indonesian Indonesia
it-IT Italian Italy
ja-JP Japanese Japan
ko-KR Korean Republic of Korea
nl-BE Dutch Belgium
nl-NL Dutch Netherlands
no-NO Norwegian Norway
pl-PL …
```

fix(intl): Fix missing translation for "xx-XX" locale

---

src/AppActions.js
src/PresentationalComponents/Common/Tables.js
src/PresentationalComponents/RulesTable/RulesTable.js
src/SmartComponents/Recs/Details.js

This PR addresses [RHCLOUD-7889](https://projects.engineering.redhat.com/browse/RHCLOUD-7889). It will update the way we query the advisor api to get rules with particular host tags.
Per the 🎫 , we are moving from...
`?tags=tag1,tag2`
to
`?tags=tag1&tags=tag2`
Here's a screenshot of this working:

Update tags query

---

src/PresentationalComponents/SystemsTable/SystemsTable.scss

This PR fixes https://projects.engineering.redhat.com/browse/RHCLOUD-8661
**Before:**
**After:**

Make systems table text conform to pf default

---

src/PresentationalComponents/Common/Tables.js

related to https://github.com/RedHatInsights/insights-advisor-api/pull/631
internally we need to track the undefined state, but visually, n as far as the url is concerned no need to broadcast this invalid url param
furthermore, if redirect to with the param attribute missing or undefined, will behave as expected (current state) will show all status of recs

Removes 'undefined' as reports_shown url param (when applicable)

---

src/PresentationalComponents/Inventory/Inventory.js

instead of gray screen of wtf while we're loading the inv sys table component, throw a loading screen that will then be replaced with the table once it loads (n then it has to load stuff as well, but hey no more gray screen of wtf)

Adds loading to rec details inventory table component

---

src/SmartComponents/Recs/List.scss

This PR addresses https://projects.engineering.redhat.com/browse/RHCLOUD-8707
**Before:**
**After:**
1. Safari
2. Chrome
3. Firefox

Set flex value for Recs header

---

src/SmartComponents/Recs/List.scss

This PR reverts #749 in order to keep the Rec Header size consistent when users enter text into the search field. 
Addresses 🎫  -> https://projects.engineering.redhat.com/browse/RHCLOUD-9063
Before:
After:

Keep Rec Header size consistent

---

src/PresentationalComponents/SystemsTable/SystemsTable.js

In order to show proper RBAC state in systems table we need to pass `fullView` prop to inventory component. This applies only to systems page as it's the only place where inventory table is just one component on screen. Without this prop the `unAuthorized` component would be in table, which is not correct based on our mocks.
[1] https://github.com/RedHatInsights/frontend-components/blob/master/packages/inventory/doc/inventory.md#using-rbac-with-inventory

Mark systems table as full view

---

src/SmartComponents/Recs/List.js

Does it make sense to announce about Red Hat Disabled rules if there aren't any rules just yet?  At the moment I don't believe we have any Red Hat disabled rules and not sure when that'll start happening.  So (to me at least) it seems better to make the alert conditional until we have such rules and the customer can be made aware of them then.

Only display Red Hat disabled rules alert if there are said rules

---

src/PresentationalComponents/Common/Tables.js

This PR fixes https://issues.redhat.com/browse/ADVISOR-1387
Right now we get an extra `Name` filter chip when `reports_shown` is found in the URL.
https://cloud.redhat.com/insights/advisor/recommendations?impacting=true&sort=-total_risk&limit=10&offset=0&total_risk=3&reports_shown=true
**Before:**
**After:**

Filter out non-filterTypes from chips 

---

src/PresentationalComponents/Modals/DisableRule.js

This PR should fix a minor bug involving the `onKeyPress` prop. Currently, if a user presses enter with the DisableRule Modal open, the page reloads. The changes in this PR sets the `onKeyDown` prop on the `TextInput` component instead of on the Modal, and prevents the default event (the page reload) on Enter. This stops the page from being reloaded and acts the same as pressing the `Save` button on the modal.

Update onKeyPress for DisableRule Modal

---

src/PresentationalComponents/ExecutiveReport/_Download.scss
src/SmartComponents/Recs/List.scss

Noticed the styling of the Autoack alert was mangled on smaller screen sizes.  This PR tries to make it purty(er).  Please LMK if there is a better / more-patternfly-ish way of doing this.
Before style fix:
After style fix:
At the breakpoint of style fix:

Fix styling of autoacks alert on small screen sizes

---

locales/translations.json
src/Messages.js
src/SmartComponents/Recs/ClassicRedirect.js
src/SmartComponents/Recs/Recs.js

Resolves https://issues.redhat.com/browse/ADVISOR-1403 by creating a component which handles the api request for the inventory id corresponding to the given classic id and redirects to `InventoryDetails`.
When redirect fails:

Add Redirect component for Classic ids

---

src/SmartComponents/Recs/ClassicRedirect.js

I noticed a bug with the classic redirect when in the beta environments. I hardcoded the indices we are using to determine the `id` and `classicId` values, and they become set to the wrong values, because the indices I used do not account for `/beta`
For URL: https://cloud.redhat.com/beta/insights/advisor/recommendations/classic/decreased_vm_network_performance%7CVHOST_NET_KERNEL_MODULE_NOT_LOADED/1ffb3a80-8290-4b2f-ba9d-9e6422604fd6

Update ClassicRedirect for urls with beta

---

src/SmartComponents/Recs/List.js

Actually works this time.   Whodathunk 'false' === true !?!  Programming101 fail for Mark :facepalm: 
But anyway, should I use localStorage instead of sessionStorage though?  Then the alert will never be back :terminator:

Properly persist clearing the Red Hat disabled rule alert

---

locales/translations.json
src/Messages.js
src/SmartComponents/Common/ClassicRedirect.js
src/SmartComponents/Recs/Recs.js
src/SmartComponents/Systems/Systems.js

This PR adds additional functionality to the `ClassicRedirect` component. Using a switch statement we can now handle both `recommendations/classic` and `systems/classic`.
Resolves: https://issues.redhat.com/browse/ADVISOR-1455

Update ClassicRedirect to consume systems/classic

---

src/Messages.js
src/PresentationalComponents/Inventory/InventoryDetails.js
src/SmartComponents/Recs/Details.js
src/SmartComponents/Recs/List.js
src/SmartComponents/Systems/List.js
src/SmartComponents/Topics/Details.js
src/SmartComponents/Topics/List.js
src/index.html

Not sure if this is the right/react way of doing this.  Feedback is most welcome.
Old issue: https://issues.redhat.com/browse/ADVISOR-608
Mocks: https://marvelapp.com/prototype/e5gcj47/screen/71812909
Screenshots of changes:

Use consistent page titles across Insights - add subapp name to page titles

---

src/index.html

Since the branding has changed slightly we want to remove the words `Red Hat` from browser title as well.

Remove Red Hat from insights

---

locales/translations.json
src/Messages.js
src/PresentationalComponents/Common/DownloadHelper.js
src/PresentationalComponents/Export/SystemsPdf.js
src/PresentationalComponents/Modals/DisableRule.js
src/PresentationalComponents/RulesTable/RulesTable.js
src/SmartComponents/Recs/Details.js

fixes https://issues.redhat.com/browse/ADVISOR-1705
kills the surprise list of systems that shows up after ack/unacking systems on the rec detail page
also reconfigures syspdf to use unpaginated endpoint, PDF EXPORT 100K SYSTEMS PEEEPS

Reconfigures system un/ack to use filtered (tags workload) fetch 🍦

---

src/App.scss

fixes https://issues.redhat.com/browse/ADVISOR-1618
also i know that sys-table text is incorrect, we already changed it samezies as the rec table, i might be that the inventory table doesn't accept the `deleteTitle` prop on the `activeFiltersConfig` ?

Ensures no right margin on last filter chip item 🍩☠︎

---

src/PresentationalComponents/Inventory/Inventory.js
src/PresentationalComponents/SystemsTable/SystemsTable.js

cc @AllenBW 
This ensures that nothing got broken when a new inventory is pushed in chrome.

Disable default columns in inventory table

---

src/SmartComponents/SystemAdvisor/SystemAdvisor.js

There is an error, after the system detail refactoring the detail was failing on missing Intl. This PR fixes such issue by wrapping the base system detail in wrapper that has the intl provider.

Add custom intl prop so the system detail component won't fail

---

locales/translations.json
src/Messages.js
src/PresentationalComponents/RulesTable/RulesTable.js

fixes https://issues.redhat.com/browse/ADVISOR-1751

RH disabled filter now shows n/a systems with info tooltip

---

src/PresentationalComponents/Inventory/Inventory.js

Maybe fixes https://issues.redhat.com/browse/ADVISOR-1723
Items are not required and they can be empty, however there are several `items.length` calls.
There are two approaches how to fix it:
1) add default value `[]`
2) add safe accessors 
Let me know, what you prefer. I went with the first one as it makes more sense to me.

Add default for undefined items

---

src/SmartComponents/SystemAdvisor/SystemAdvisor.js

fixes https://issues.redhat.com/browse/ADVISOR-1882

Adds incident label to system details page

---

src/PresentationalComponents/RuleDetails/RuleDetails.js

Right now, there is no resolution (risk of change) value
available in the contents of OCP Insights rules. As RuleDetails is a
shared component, we need to make sure the component does not crash or
show incorrect info when this value is absent.

Make riskOfChange optional: rule details component

---

src/PresentationalComponents/RuleDetails/RuleDetails.js

OCP infrastructure is designed in a way that the feedback is given to the set of clusterId + ruleId. There are planned changes that should change the behavior to be clusters-wide. But for now, there will be a need to hide the feedback form for OCP recommendation details page.
RHEL example when the callback is not provided:

Hide feedback form if there is no onFeedbackChanged provided

---

src/PresentationalComponents/ExecutiveReport/_Download.scss

fixes https://issues.redhat.com/browse/ADVISOR-2053
looks like someone changed the behavior of `PageHeaderTitle` component, children are no longer rendered inline 😭

HOTFIX for broken exec report button

---

package-lock.json
package.json
src/PresentationalComponents/Common/DownloadHelper.js
src/PresentationalComponents/Export/SystemsPdf.js
src/PresentationalComponents/Inventory/Inventory.js
src/PresentationalComponents/SystemsTable/SystemsTable.js
src/SmartComponents/SystemAdvisor/SystemAdvisor.js

Since we are no longer provide redux and react-redux trough fed modules dependencies, we have to wrap system detail in redux provider and assign the store passed from parent component to it. If no store is passed from parent component do not create such provider.
This PR can be merged asynchronously from inventory, the inventory update will just remove the redux and react-redux from the provided dependencies (which are not consumed in here anyway).

Fix missing provider by wrapping system detail in it

---

src/PresentationalComponents/RuleDetails/RuleDetails.js

When OCP Advisor was importing the `RuleDetails` fed module, there was an issue with the `Link` component that appeared outside the Router context. Thus, this patch adds another Router wrapper to the component once `history` is passed as a parameter. Also did small code rearrangements and cleaned up unnecessary props like `customItnl`.
Relates to https://github.com/RedHatInsights/ocp-advisor-frontend/pull/82.

Wrap RuleDetails with custom router; refactor

---

src/PresentationalComponents/SystemsTable/SystemsTable.js

This fixes the filters on the SystemsTable and makes them work properly again.
**How to test:**
1. Open the Advisor app on the Systems page
2. Verify that filters work and trigger a reload of the table with proper results.

fix(SystemsTable): ADVISOR-2104 - Update sysState not state for recs

---

src/AppConstants.js
src/Messages.js
src/PresentationalComponents/Inventory/Inventory.js
src/PresentationalComponents/RulesTable/RulesTable.js
src/SmartComponents/SystemAdvisor/SystemAdvisor.js

This updates all places mentioning "Ansible" to use the new wording.
The changes can be seen on the "Recommendations" page as well as any SystemsAdvisory page and the "Advisor" tab in the Inventory application.

fix: ADVISOR-1903 - Update "Ansible" to "remediation"

---

src/SmartComponents/SystemAdvisor/SystemAdvisor.js

This PR is intended to fix the incorrect row count after appliying a filter in Advisor System details table.
Before:
After:

chore: fix error in row count

---

src/PresentationalComponents/ExecutiveReport/Download.js

We should change current behaviour from showing 'Loading' state when download report fails to active button state. 
Before:
After:

fix: reset loading state to active state when dowload fails

---

src/PresentationalComponents/RuleDetails/_RuleDetails.scss

fix: ADVISOR-2054 - Recommendation expansion description padding

---

src/PresentationalComponents/Common/Common.js

Changed the icon color from blue to grey. No specific grey was specified, so I used the same color code from other apps

fix: Change pathways card question icon to grey

---

config/dev.webpack.config.js
package-lock.json
package.json
src/PresentationalComponents/SystemsTable/SystemsTable.js

This updates the OS filter to use the helpers provided by the Inventory applications as federated modules.
**Note:** Currently the inventory helpers are only deployed to `/beta`

feat(SystemsTable): ADVISOR-1959 - Use grouped OS selection via helpers

---

locales/data.json
locales/translations.json
src/Messages.js

Currently, if hit visit systems table and hit Systems PDF export button, intl is complaining of a non-existing noTags message. This PR is intended to resolve the issue by adding the noTags message.

chore(SystemPdf): missing noTags message is added

---

src/PresentationalComponents/Common/Common.js

There was a strange issue with this color, should be working now
Before:
After:

fix: Change pathways card question icon to correct grey

---

src/SmartComponents/Recs/Details.js

[ADVISOR-2060](https://issues.redhat.com/browse/ADVISOR-2060)
Updated label in Recommendations detail page
Before:
After:

fix(Details): ADVISOR-2060 new labels in recommendations detail

---

src/SmartComponents/Recs/DetailsPathways.js

Added Bottom margin to date, but the gap looks too big to me
Before:
After:
[ADVISOR-2117](https://issues.redhat.com/browse/ADVISOR-2117)

fix(DetailsPathways): ADVISOR-2117 add margin to pathway date

---

src/PresentationalComponents/RulesTable/RulesTable.js

The ticket description is
'Always keep the reset filters text and default filter available. Right now, when we cancel the filter, it all disappears. AND when removing the filter, it disables the export functionality which is a bug.'
With the changes I made the 'Reset Filter' button is always present, and the export functionality is always available.
To see the changes
Go to Advisor,
Click recommendations,
Delete the two default filters 'systems impacted' , and 'status enabled'
You'll see that you can still select the export button
And you'll see that now the 'Reset Filter' button is still present, and onClick the filters are restored.

ADVISOR-2127

---

src/PresentationalComponents/Cards/Pathways.js

[ADVISOR-2119](https://issues.redhat.com/browse/ADVISOR-2119)
Before:
After:
When there was only one item in the array of categories, the single item would not be displayed

fix(Pathways): ADVISOR-2119 fix missing category name when only one

---

src/PresentationalComponents/Cards/Pathways.js

[ADVISOR-2118](https://issues.redhat.com/browse/ADVISOR-2118)
Before:
After:
Chart height is smaller to be closer to the mockup, fixed triple digit chart value overflow, chart bar is a bit thicker and cards are the same height.

fix(Pathways): ADVISOR-2118 fix card and chart size

---

src/SmartComponents/SystemAdvisor/SystemAdvisor.js

After remediating systems, the selected systems are no longer selected.
To view changes
- navigate to systems tab in advisor
- select a system with at least 1 tag (ex. $uper_device has 5)
- select any combination of items available in the table
- click remediation button
- follow through remediation process ('create playbook and continue to press next)
- Once you reach the end and items have been added to a playbook, select 'return to application' or the x on the top right of the modal
- here you should see that the previously selected items are no longer selected

ADVISOR-2057 Systems are not selected after remediation 

---

src/PresentationalComponents/Inventory/Inventory.js

Bulk selector dropdown now shoes the correct 'select page' option number, and there is no empty space in the dropdown before changing the items displayed per page. 
To view changes 
- Run the app
- Click recomendations tab in the left menu
- Navigate to pathways
- Select a pathway
- select the systems tab
- open the bulk selector
Here you will see that where the empty space was, there now displays 'Select Page (20 items)'
- Edit the items show per page by clicking the pagination
- select something like 50 per page
In the bulk select, the 'select page' option will be updated with the current items per page

ADVISOR-2462, bulk selector dropdown is improved.

---

src/PresentationalComponents/Cards/Pathways.js

[ADVISOR-2364](https://issues.redhat.com/browse/ADVISOR-2364)
In Pathway Detail moved the X axis to right
Before:
After:

fix(Pathways): ADVISOR-2364 - Chart x axis moved more to the right

---

src/PresentationalComponents/Inventory/Inventory.js

To view, run the app (must be in beta)
- Click recommendations in the left menu, 
- Selected pathways tab
- Select a pathway
- Click systems tab
- Select a system
Where before the bulkselector would remain empty besides a '1 selected', it now displays a ' -  '

ADVISOR-2000, bulkselector displays correct sign when item selected

---

src/AppEntry.js

If the format.js translations were not found, Advisor would log errors in production. Removing the line sets the behavior to default: https://formatjs.io/docs/react-intl/components/#onerror and will make errors appear only if `NODE_ENV` is not set to `production`.

fix: Don't override onError for IntlProvider wrapper component

---

package-lock.json
package.json
src/PresentationalComponents/Inventory/Hooks/useBulkSelect/__snapshots__/useBulkSelect.test.js.snap
src/PresentationalComponents/Inventory/Hooks/useBulkSelect/helpers.js
src/PresentationalComponents/Inventory/Hooks/useBulkSelect/index.js
src/PresentationalComponents/Inventory/Hooks/useBulkSelect/useBulkSelect.js
src/PresentationalComponents/Inventory/Hooks/useBulkSelect/useBulkSelect.test.js
src/PresentationalComponents/Inventory/Hooks/useSelectionManager/__snapshots__/useSelectionManager.test.js.snap
src/PresentationalComponents/Inventory/Hooks/useSelectionManager/index.js
src/PresentationalComponents/Inventory/Hooks/useSelectionManager/reducer.js
src/PresentationalComponents/Inventory/Hooks/useSelectionManager/useSelectionManager.js
src/PresentationalComponents/Inventory/Hooks/useSelectionManager/useSelectionManager.test.js
src/PresentationalComponents/Inventory/Inventory.js
src/Store/AppReducer.js

This change fixes the issues regarding the bulk selector in advisor pathway details page.
Right now, when trying to view more systems, all selected items are cleared. To replicate
Click recommendations in the left menu,
Selected pathways tab
Select a pathway
Click systems tab
Select a system or two
Press a new page (look at the pagination button, select the '>' button the view items 20-40 as opposed to 1-20.
Old Behavior: selected is clear
New Behavior: When moving pages , state is carried across. Also if you do a select all and then deselect 1 item, it doesnt switch to (pagesize -1), it instead does (total Systems -1)
With this change state is carried around properly, and ADVISOR-2388 can be worked on more easily as selected items are managed/updated properly.

ADVISOR-2472 : bulk Selector refactor

---

src/Services/Filters.js

On page load for Systems tab in advisor, the tags were sent as an empty object and the api was getting angry. The tags were set to null at first. This fixes selectedTags and now you can add/remove tag filters and you can load the systems page in advisor. Currently a problem in stage env.

fix for advisor tags on systems page

---

deploy/frontend.yaml

The template should be using `apps/` for chrome to correctly handle routing. `/insights/*`  is handled via the `routes` in the module field.

[RHCLOUD-19380] Update template to use chrome path

---

src/PresentationalComponents/RulesTable/RulesTable.js
src/SmartComponents/Recs/Details.js

Fix for https://issues.redhat.com/browse/ADVISOR-2569
A rule doesn't always have a KCS article associated with it, in which case node_id will be blank.  This PR handles that situation.

fix: ADVISOR-2569 - Handle empty KCS article node_id value

---

src/PresentationalComponents/PathwaysTable/PathwaysTable.js

Backend now supports sorting via recommendation, this PR implements that change on the front end.
To test, run advisor in beta env
- head over to https://stage.foo.redhat.com:1337/beta/insights/advisor/recommendations/pathways
- click recommendation level to see it sort for low to high
- click again to see it sort from high to low

ADVISOR-2113 recommendation sorting

---

src/SmartComponents/Recs/DetailsPathways.js
src/SmartComponents/Recs/List.js
src/SmartComponents/Recs/Recs.js

These changes are to make headway against the refresh bug. It seems to be having a different result on some set ups so I want to test with more people. To test this PR
- run advisor with npm run start:proxy:beta
- Select the systems affected link (or click a pathway, and then hit the systems tab)
- select systems
- select the remediate button
- type something inside the input 'create a playbook'
Monitor to see if the data gets refresh/wiped. Ideally with this PR the data is never wiped and the 'removeQueryResult' redux call is never called

ADVISOR-2289 Refresh Bug 

---

src/Messages.js
src/SmartComponents/SystemAdvisor/SystemAdvisor.js

This fixes the invisible recommendations bug on prod-stable. The issue was due to some of the recommendations had resultion: null in the api response and all [lines](https://github.com/RedHatInsights/insights-advisor-frontend/blob/master/src/SmartComponents/SystemAdvisor/SystemAdvisor.js#L195) in which resolution is used to access a property caused type error. With this commit, all lines dealing with resolution are modified to handle resolution: null nicely.
To test:
- There is a temp commit with the API result from the customer. 
- Please import results object from **apiResponseInTheCase** file.
- provide the results object to [activeRuleFirst](https://github.com/RedHatInsights/insights-advisor-frontend/blob/master/src/SmartComponents/SystemAdvisor/SystemAdvisor.js#L618) function so that …

Fix resolution bug

---

src/AppConstants.js
src/PresentationalComponents/Common/Common.js
src/SmartComponents/SystemAdvisor/SystemAdvisor.js

Removes the redirects to console log for Intl on error, which can lock up the browser.

fix: Remove intl on error redirect to console

---

src/PresentationalComponents/Labels/RuleLabels.js
src/PresentationalComponents/TopicsTable/TopicsTable.js
src/SmartComponents/Topics/Details.js

Doing a final walk through, there were some straggling labels not previously seen in the SPUR review. This updates the remaining labels to be compact.

chore(labels) update stragling labels to be compact'

---

src/PresentationalComponents/Inventory/Inventory.js
src/SmartComponents/SystemAdvisor/SystemAdvisor.js

This PR adds a url check to the isOpen variable that controls when the first item in the recommendations list is expanded or not. When coming from systems, the first item will no longer be expanded, but when coming from recommendations, the first item will be expanded. 
To test
1st check:
Navigate to recommendations list via 
Recommendations Tab In Navbar> click recommendation under recs tab > Click on a system > see recommendation list
Desired behavior : first item is expanded, and first item is the recommendation you came from
2nd Check
Systems Tab  in Navbar > select a system > see recommendation list
Desired Behavior : first item is not expanded

fix(ADVISOR-2546) : Adds Url check to isOpen variable and sorts list

---

src/SmartComponents/SystemAdvisor/SystemAdvisor.js

Per pm, this introduces sorting by total_risk when coming from any route other than recommendations tab. 
These are the two routes to verify 
- Advisor recommendations -> recom details -> Affected system: first in the table should be the recommendation in question, expanded.
- Advisor systems -> system details: all recommendations are collapsed, sorted by total risk.

 Refactor(advisor): System Advisor sorts by total risk on first load when coming from systems route

---

src/PresentationalComponents/PathwaysPanel/PathwaysPanel.js

This refactors PathwayPanel so that it is independent of the sort on pathwaysTable. It will always be sorted via recommendation level.

Refactor(ADVISOR-2673): PathwaysPanel is sorted by rec lvl, independent of PathwaysTable 

---

src/PresentationalComponents/Inventory/Inventory.js

When rule was `undefined` (always for Pathways systems table) `renderFunc` was set to `{}` which is not a valid function and was crashing the table. Fixed by only overriding `renderFunc` when rule wasn't `undefined`.

Fix Pathways systems table crash

---

src/PresentationalComponents/Inventory/Inventory.js
src/PresentationalComponents/SystemsTable/SystemsTable.js

This follows up on and has to be merged first before https://github.com/RedHatInsights/insights-inventory-frontend/pull/1621.
In order to work correctly with the updated Inventory's OS filter, Advisor has to provide the available OS values to `buildOSFilterConfig` (which is imported from Inventory). It also replaces the static filter values in the Affected systems table and builds the filter config the same way done in the Systems.
1. Locally, in the Inventory app, checkout to https://github.com/RedHatInsights/insights-inventory-frontend/pull/1621.
2. In Advisor app folder, run `PROXY=true BETA=true npx webpack serve --config config/dev.webpack.config.js --port 8004`.
3. In Inventory app folder, run `LOCAL_API=advisor:8004~https PROXY=true BETA=true npx webpack serve --config …

Dynamic OS filter values in the Systems and Affected systems tables

---

src/PresentationalComponents/SystemsTable/SystemsTable.js

This updates the os column sort key after it has been changed on the Inventory side ([commit](https://github.com/RedHatInsights/insights-inventory-frontend/commit/ef34976e44fa0e9a7231579f981d537dfaab408d)).

fix(SystemTable): update the OS column sort key

---

src/PresentationalComponents/Inventory/Inventory.js
src/PresentationalComponents/Inventory/helpers.js

This fixes sorting in the Inventory table, while also disabling sorting for columns that are not supported by the backend.
Tickets for columns [Impacted_date, rhel_version(OS)] have been made and the backend team is aware. Once backend supports these, we can enable sorting on the frontend. 
To test navigate to recommendations - select a recommendation > try sorting on the table there with the available options.
P.S I will squash the commits. I didn't mean to grab all of these.

fix(ADVISOR-2791): Fixes sorting in Inventory table

---

src/Store/AppReducer.js

With https://github.com/RedHatInsights/insights-inventory-frontend/pull/1668 this would cause an issue. However, after investigating it seems that this does nothing, and should be safe to be removed.
Left: Local-Dev (this PR) Right: Stage

refactor(AppReducer): ESSNTL-3505 - Remove unneeded last column mangling

---

.github/workflows/cypress.yml

This PR modifies the cypress workflow config so that the tests are also run in pull requests. Also, it makes the check use the cypress binaries right from `node_modules` instead of using a GH action (which led to flaky behavior sometimes).

Run cypress in PRs, and use npm script instead

---

src/PresentationalComponents/PathwaysPanel/PathwaysPanel.js

Global filters and such were not added to pathway panels GET request. 
This causes situations like the one described in the ticket https://issues.redhat.com/browse/ADVISOR-2830 
It could also cause an issue that the pathway table show no pathways (because you add some global filter) but the pathway panels do.
To test, 
Navigate the /recommendations and select the pathways tab
Select global filters and verify that the pathway panel now also reloads when changing global filters. 
The results **should** be identical and in the same order **unless** you altered the sort/added additional filters to the table

fix(ADVISOR-2830): Adds workload,SID, and GlobalTags to PathwayPanels

---

config/dev.webpack.config.js
config/prod.webpack.config.js
src/Modules/SystemDetail.js
src/SmartComponents/SystemAdvisor/SystemAdvisor.js

Fixes an issue introduced by https://github.com/RedHatInsights/insights-advisor-frontend/pull/1035.
This extracts `SystemDetail` federated module to an extra wrapper component. The previous implementation was leading to an error since the `useSelector` hook was trying to access the store before the redux provider was set up. We still require `BaseSystemAdvisor` not to request `entityDetails` via redux store for easier component testing.
While deployed locally together with Inventory app (e.g., with test-inv.sh), check:
1) navigate to Advisor system details page and verify the rules table is rendered,
2) navigate to Inventory system details page, Advisor tab, and verify the rules table is rendered.

fix: Add federated module wrapper for SystemAdvisor

---

src/SmartComponents/SystemAdvisor/EmptyStates.js
src/SmartComponents/SystemAdvisor/SystemAdvisor.js

Fixes https://issues.redhat.com/browse/ESSNTL-3670.
This removes the checks for satellite managed systems and makes the system details page always show rule results.

fix(SystemAdvisor): show rules for satellite managed hosts

---

src/PresentationalComponents/Inventory/helpers.js
src/PresentationalComponents/SystemsTable/SystemsTable.js

https://issues.redhat.com/browse/ADVISOR-2861
Global Tags were not being sent in Get request causing unrelated systems to show up in certain scenarios.
To test head to recommendations
Add a global filter tag 
Look at the results in the table, specifically the affected systems number of the recommendation you're going to select
Selected the recommendation
It should have the same amount of systems as it said it was going to have

fix(ADVISOR-2861): Sends global tags up in inventory and systems table

---

.github/workflows/cypress.yml

Easy PR, should remove the issue of tests running twice on merging to the master-stable and prod-stable
Screenshot of the issue

feat(ghactions): improving the job script

---

src/PresentationalComponents/SystemsTable/SystemsTable.js
src/PresentationalComponents/helper.js

Currently in production when sorting in the systems page, it will send the name param and not filter down the table. This PR changes that so that the correct param is sent for the correct table.
In the systems page it needs to send display_name.
In recommendations table in needs to send text.
in pathways table it also needs to send name

fix(ESSNTL-3781-2): Name Param changes if on systems page

---

src/PresentationalComponents/RulesTable/RulesTable.cy.js
src/PresentationalComponents/RulesTable/RulesTable.js
src/PresentationalComponents/RulesTable/helpers.js

Associated Jira ticket: # ([ADVISOR-2915](https://issues.redhat.com/browse/ADVISOR-2915))
It seems Advisor rules table was originally built to update filters based off urls on page load. Different tables take in differing parameter values in advisor (this is a known issue).
Run advisor against prod env via :
CHROME_ENV=prod-stable npm run start:proxy
Access https://console.redhat.com/insights/dashboard
In the menu select Advisor > Recommendations
In the global filter select "Microsoft SQL"
Select a recommendation to show the affected systems
Click on the "Go back" button in the browser
The table would break, in the network tab it would yell about an incorrect sorting param passed in
It passes, making the default '-total_risk'
Notes: In the refactor PR I will try and optimize this page …

fix(ADVISOR-2915): Updates filters check for RulesTable

---

src/AppEntry.js

Associated Jira ticket: #RHCLOUD-23202
There's an error with global filter tags not being applied when selecting. This is caused by re-creating store on each AppEntry render. The application can render multiple times (PF contexts, navigation, etc.) and that can invalidate data stored in the redux state. This PR fixes it by using `useMemo` to create the store only on initial render.
Run Advisor app locally and select tag from global filter.

fix(RHCLOUD-23202): Do not re-create sotre on each render

---

package-lock.json
package.json

Associated Jira ticket: https://issues.redhat.com/browse/RHIF-111
This aligns the version of `redux` and `react-redux` libraries to the ones in insights-chrome.

fix(Shared dependencies): Align versions of redux

---

cypress/fixtures/kcs.json
src/SmartComponents/SystemAdvisor/SystemAdvisor.cy.js
src/SmartComponents/SystemAdvisor/SystemAdvisor.js

Associated Jira ticket: https://issues.redhat.com/browse/ADVISOR-2948.
SystemAdvisor table renders so-called "Knowledgebase article" section where it also inserts a link to access.redhat.com with info relevant for particular rule. To learn the appropriate URL and publish title, it makes additional request to access.redhat.com API and provides all necessary rule (node) IDs. The issue is that we were providing this request also the parameter `rows` and it was set to the number of rule IDs. However, the API can return more results, and in some edge cases (see Jira), there can be some rules left out from the response, and the table was breaking. By removing `rows` parameter, we are making sure we receive kcs links for all node IDs.
The scenario is hard to simulate, but I checked the customer …

fix(SystemAdvisor): Request all kcs articles

---

.github/workflows/CI.yml

Fixing the release bug
The issue was - instead of using the target of the pull request as TRAVIS_BRANCH variable I was using the current branch
Source
https://stackoverflow.com/questions/62331829/how-to-get-the-target-branch-of-the-github-pull-request-from-an-actions

fix(ghactions): fixing release in gh actions

---

src/SmartComponents/Recs/Details.js

Associated Jira ticket: # [(ADVISOR-2942)](https://issues.redhat.com/browse/ADVISOR-2942)
Fixes 'Enabling recommendation for all systems' by correctly passing function parameters. 
1. Visit Advisor recommendations tab.
2. Open any recommendation systems page.
3. Select a few systems
4. From actions in the table toolbar, click on 'Disable recommendation for selected systems'
5. click on new appeared 'Enable this recommendation for all systems' button to re-enable
6. Observer that page does not break

fix(ADVISOR-2942): fix enable all recs button

---

.codecov.yml

I encountered the issue of "codecov/patch" breaking while I was working on another PR ( see the screenshot)
To fix that issue and incorrect behavior I added a code coverage config

fix(codecov): added code coverage config

---

package.json

When I was moving deploy back to Travis I added a test step back as well
This PR removes this test step from Travis because it's already present in the GitHub actions
Also, I updated nyc settings to read from any folder under src

fix(travis):remove test step from travis and update nyc

---

src/PresentationalComponents/RulesTable/helpers.js

Bandaid fix for advisors sorting issue on page load. Sometimes the value is an array and others a string. This adds conditions to that check. 
Still investigating the real issue at hand but I wanted to send this up as its listed other major incidents. 
go to Recommendations page
apply a filter (NOT name filter)
copy the URL
navigate to the URL in a new tab
breaks on sort in url
Does not break

fix(ADVISOR-2965): adds check against url

---

src/PresentationalComponents/Inventory/InventoryDetails.js
src/SmartComponents/SystemAdvisor/SystemAdvisor.cy.js
src/SmartComponents/SystemAdvisor/SystemAdvisor.js
src/SmartComponents/SystemAdvisor/SystemAdvisorAssets.js
src/Store/AppReducer.js

Associated Jira ticket: # [RHIF-175](https://issues.redhat.com/browse/RHIF-175)
Removes AppInfo component usage and introduces some code cleanup to SystemAdvisories.
- Moves all easy to extract constants and functions into the assets file
- Wrapps some functions into `useCallback` hook
The next step should be to improve & simplify the functions extracted.
Functionality of the app should not change

chore(RHIF-175): get rid of AppInfo with some code cleanup

---

src/PresentationalComponents/Common/Common.js

Associated Jira ticket: # https://issues.redhat.com/browse/RHIF-178
Loads react-tokens using an absolute path. This enables us to reduce of the bundle by ~200kb.

enh(RHIF-178): load react-tokens only using absolute path

---

src/SmartComponents/Recs/Details.js

Updates empty state behavior so that when a user goes to a bookmark of a rule that no longer exist, they are greeted with the correct page. 
Associated Jira ticket: # (ADVISOR-3032)
Head to https://stage.foo.redhat.com:1337/beta/insights/advisor/recommendations/whatever#SIDs=&tags= 
Observe that the page does not error out but instead shows this image
The page would crash and get  "Something went wrong". 
Page does not crash anymore.

fix(ADVISOR-3032)Update empty state when rule is not found

---

src/PresentationalComponents/PathwaysTable/PathwaysTable.js

Associated Jira ticket: # (ADVISOR-3030)
When selected a pathway and going to pathway details, sometimes when going back, the page breaks. This is because the sort params on rules table dont coincide with pathway table. 
Go to pathway details, then go back a page. The page should not break regardless if the sort in url is -total_risk. 
Also paste in the url : https://stage.foo.redhat.com:1337/beta/insights/advisor/recommendations/pathways?sort=-total_risk&limit=20&offset=0&impacting=true&rule_status=enabled#SIDs=&tags= and see if it breaks
Page breaks
Page does not break

fix(ADVISOR-3030): Fix broken page

---

src/PresentationalComponents/RulesTable/RulesTable.js
src/SmartComponents/Recs/DetailsPathways.js

Associated Jira ticket: # (ADVISOR-3029)
This PR reverts some styling issues that snuck-in in the removal of that Main component in this [PR](https://github.com/RedHatInsights/insights-advisor-frontend/pull/1066) 
Ensure the padding and colors look the same in a pathway details table as they do in other tables. 
Here is a picture before that PR for reference.

fix(ADVISOR-3029): Fix Pathway details styling

---

src/PresentationalComponents/RulesTable/RulesTable.js
src/PresentationalComponents/RulesTable/helpers.js

Learning from my last large attempt at refactoring, This PR reorganizes just the RulesTable component. There should be no changes in functionality. This simply cleans up the RulesTable component so that its much easier to navigate. The file was 800+ lines of code and it caused of lot of jumping around when trying to debug the table. This PR cuts it in half and utilizes the helpers.js file

chore(Refactor): Reorganize RulesTable component

---

package-lock.json
package.json
src/PresentationalComponents/RulesTable/RulesTable.cy.js
src/PresentationalComponents/RulesTable/RulesTable.js

Implements https://issues.redhat.com/browse/RHINENG-956.
On the /recommendations page, when one expands the content, the "View affected ..." links must lead to /recommendations/%rule_id page.
1. Navigate to /recommendations
2. Expand any rule that has at least 1 system impacted
3. Click on the "View affected ... systems" and make sure you are navigated to the rule details page.

fix(RHINENG-956): Fix broken links in rule content

---

.codecov.yml

turn off codecov patch because its keep popping up and throwing CI fails in our PR's

chore(deps): remove codecov patch

---

src/PresentationalComponents/Inventory/InventoryDetails.js
src/SmartComponents/Recs/Details.js
src/SmartComponents/Recs/DetailsPathways.js
src/SmartComponents/Recs/List.js
src/SmartComponents/Systems/List.js
src/SmartComponents/Topics/Details.js
src/SmartComponents/Topics/List.js

This PR adopts the updateDocumentTitle hook from chrome. This is in an effort to fix the flow of the lastSeen objects on the landing page and just for general upkeep. 
Navigate to all the pages in advisor and see the the document title is updating properly

fix(RHIF-262): adopt chrome updateDocumentTitle hook

---

src/PresentationalComponents/ExecutiveReport/Download.js
src/Utilities/Api.js

Refactors the pdf-migration work to use the FEC shared usePDFExport hook. 
1. Run the PR locally
2. verify that you can download the executive report by clicking on 'Download executive report' on the top right corner'

chore: refactor pdf-generator migration to use shared FEC hook

---

src/PresentationalComponents/Common/DownloadHelper.js
src/SmartComponents/SystemAdvisor/SystemAdvisor.js

This ticket allows for the new export on systems advisor page to export for just one system as opposed to all. 
Associated Jira ticket: # ([RHINENG-405](https://issues.redhat.com/browse/RHINENG-405))
Head to advisor systems page and select a system
There is now an export button, click it 
select both csv and json exports and verify that the data returned is just for one system.

feat(RHINENG-405): Add single recommendation to export

---

src/SmartComponents/SystemAdvisor/SystemAdvisor.js

Inventory Advisor tab would have errors because certain advisor filters dont exist on that page. This makes it 'optional' 
https://issues.redhat.com/browse/RHINENG-1167
Inventory Advisor tab never loads
Inventory Advisor tab loads and you can export the recommendation

fix(RHINENG-1168): Fix empty filter error on inventory advisor tab

---

src/SmartComponents/SystemAdvisor/SystemAdvisor.js

When exporting a single system the text param wasnt being applied. In the current set up its not attached to the filters object. This was originally part of the massive refactor, but for the time being this adds the param in both the inventory tab and advisor's systemAdvisor component

fix(RHIN-1167):Add search value to systemAdvisor exportConfig

---

src/PresentationalComponents/SystemsTable/SystemsTable.js

Associated Jira ticket: # ([issue](https://issues.redhat.com/browse/ADVISOR-3139))
This is a temporary fix while we wait for the real pdf migration 
Navigate to Systems page and clicked the export button.
Once the PDF option loads, select it and verify that there is no 500 error. The backend doesnt support the tags field. Normally a refactor for this would be passed through, but since theres a PR for migrating to the new pdf service I'd like to pass this in until that gets QA'd and eventually removes this commit all together. 
Systems pdf export breaks
Doesnt break

fix(ADVISOR-3139): Resolve system pdf export error

---

README.md
package.json
src/PresentationalComponents/SystemsTable/createColumns.js
src/PresentationalComponents/helper.js

Implements https://issues.redhat.com/browse/ESSNTL-3715.
- Make sure that the systems table (/advisor/systems) uses "groups" parameter to filter systems by their groups,
- Change the Group column values to plain text instead of links.
Go to /advisor/systems, and check that you are able to filter by groups and also can see to which group each hosts relates to (N/A if not in any group).

Advisor Systems page and Inventory groups enhancements

---

src/SmartComponents/SystemAdvisor/SystemAdvisor.js

Fixes https://issues.redhat.com/browse/RHINENG-1847
Selecting an affected host for a particular recommendation, the wrong recommendation is expanded.  
Screenshot showing the recommendation and the affected hosts ...
Before the fix - the incorrect recommendation is expanded for the host:
After the fix - the correct recommendation is expanded for the host:

Fix(RHINENG-1847): expand the correct selected recommendation

---

src/PresentationalComponents/SystemsTable/SystemsTableAssets.js
src/PresentationalComponents/SystemsTable/createColumns.js

Fixes https://issues.redhat.com/browse/ADVISOR-3167.
This PR fixes how SystemsTable builds columns: now the overridden parameters are prioritised over the default column parameter (like renderFunc) from Inventory. This automatically fixes: 1) incorrect link to the system details page (it was wrongly redirecting to /recommendations on click before), 2) the incident tag is back (was omitted by wrongly applied default renderFunc for the name column).
Go to /systems, check that the incident label is rendered next to the name of relevant systems in the table; and check that you are able to go to system details view for any systems.

fix(ADVISOR-3167): Fix system links on /systems

---

src/PresentationalComponents/SystemsTable/SystemsTable.js
src/PresentationalComponents/SystemsTable/SystemsTableAssets.js

https://issues.redhat.com/browse/RHINENG-1834
Allow hosts to be sorted by group name.
Before PR:
After PR:

feat(RHINENG-1834): Enable sorting host table by group name

---

package-lock.json
package.json
src/Routes.js
src/SmartComponents/HybridInventoryTabs/ConventionalSystems.js
src/SmartComponents/HybridInventoryTabs/HybridInventoryTabs.js
src/SmartComponents/HybridInventoryTabs/ImmutableDevices.js
src/SmartComponents/Recs/Details.js
src/SmartComponents/Recs/DetailsRules.js
src/Utilities/Hooks.js

Associated Jira ticket: # [(RHIF-274)](https://issues.redhat.com/browse/RHIF-274)
Creates Hybrid inventory tabs on the recommendation details page. The immutable devices tab is disabled until RHIF-307.  The work is behind the feature flag: `advisor.edge_parity`
To test:
1. Visit advisor app
2. click on any recommendation to go the details page
3. Observe that now there 2 tabs
4. Observe that Conventional systems tab works as expected
5. Observe that clicking on Immutable device adds /manage-edge-inventory into the URL.

feat(RHIF-274): add HybridInventoryTabs wrapper

---

src/PresentationalComponents/PathwaysTable/PathwaysTable.js
src/PresentationalComponents/RulesTable/RulesTable.js

Associated Jira ticket: #RHINENG-2325
The padding via the TableToolbar is required to avoid colliding with the "lightbulb"
Verify the pagination on any table does not get obscured by the lightbulb

fix(Tables): RHINENG-2325 - Add padding to footer via TableToolbar

---

locales/data.json
locales/translations.json
src/Messages.js
src/PresentationalComponents/RulesTable/helpers.js
src/Utilities/intlHelper.js

We are trying to get rid of the react-intl dependency, `formatMessage` is one of it's tools and because I used this implementation for another PR #1164 and found a replacement for it that does not use formatMessage, I opened this PR to change this implementation too to help us get rid of this dependency more quickly 
Link to [comment](https://github.com/RedHatInsights/insights-advisor-frontend/pull/1164#issuecomment-1788315909) mentioning that on the PR
Associated Jira ticket: [#ADVISOR-3185](https://issues.redhat.com/browse/ADVISOR-3185)
Insure the functionality of the component does not break
It should keep the current functionality without any visual changes
RulesTable Page:
RulesTable Page (Critical label tooltip open):
RulesTable Page (Important label tooltip open):
RulesTable Page …

feat(ADVISOR-3185) - Risk Labels refactor

---

src/SmartComponents/HybridInventoryTabs/HybridInventoryTabs.js
src/ZeroStateWrapper.js

Associated Jira ticket: # [(issue)](https://issues.redhat.com/browse/RHINENG-2741)
Shows the zero state only when there is no both conventional and immutable systems.
Also, improves the API requests scattered around components to check the presence of conventional and edge systems by sharing one request result through the react context provider.
To test (preparing accounts to test the PR):
1. Open first the account without any system
2. Observe that Zero state is shown
3. Open another account with edge system
4. Observe that Zero state is not shown
5. Open another account with conventional system
6. Observe that Zero state is not shown

fix(RHINENG-2741): disables zero state when there is edge devices

---

src/PresentationalComponents/Inventory/Inventory.js
src/PresentationalComponents/SystemsTable/SystemsTable.js
src/PresentationalComponents/helper.js
src/PresentationalComponents/helper.test.js

Associated Jira ticket: #RHIN-338
This migrates the SystemsTable to use the default OS filter provided by the InventoryTable and let it handle the filter selection.
https://github.com/RedHatInsights/insights-advisor-frontend/assets/7757/e7e2d0a1-49ad-4cf4-a086-b91349e11cff
https://github.com/RedHatInsights/insights-advisor-frontend/assets/7757/1400f080-c693-47ca-b3c9-e465490fbb6d

fix(SystemsTable): RHIN-338 - Remove custom OS filter handling

---

config/setupTests.js
src/AppConstants.js
src/PresentationalComponents/Inventory/Inventory.js
src/SmartComponents/HybridInventoryTabs/ConventionalSystems/RecommendationSystems.js
src/SmartComponents/HybridInventoryTabs/HybridInventoryTabs.js
src/SmartComponents/HybridInventoryTabs/ImmutableDevices.js
src/SmartComponents/HybridInventoryTabs/ImmutableDevices.test.js
src/SmartComponents/HybridInventoryTabs/fixtures/advisorPathwayData.json
src/SmartComponents/HybridInventoryTabs/fixtures/advisorRecommendationData.json
src/SmartComponents/HybridInventoryTabs/fixtures/edgeData.json
src/SmartComponents/HybridInventoryTabs/fixtures/inventoryData.json
src/SmartComponents/HybridInventoryTabs/helpers.js
src/SmartComponents/HybridInventoryTabs/helpers.test.js
src/Utilities/TestingUtilities.js

Associated Jira ticket: https://issues.redhat.com/browse/RHIF-307
With this initial PR, we will have a new immutable device tab according to this [mockup](https://www.sketch.com/s/ac25729e-df9b-4e74-a09c-badb62787d24/p/43FFE7E9-F052-4552-8B5D-494C0CE0861E/canvas). This is the first PR dedicated for this tab. Additional, the group and tag filters will be added later.
1. Run the PR locally, 
2. Navigate to a recommendation detail page by clicking on one of them from the recommendations list
3. Observe that there is a new tab called Immutable devices(OSTREE)
4. Observe that the name and operating systems are working as expected
5. Observe that sorting works for only name, last seen and first impacted columns are sortable and they work
6. Clicking on the image name from the image column takes …

feat(RHIF-307): create immutable device tab for recommendation detail

---

src/SmartComponents/HybridInventoryTabs/ImmutableDevices.js
src/SmartComponents/HybridInventoryTabs/ImmutableDevices.test.js

Associated Jira ticket: # NO TICKET
This adds a tag filter to the Immutable Devices tab.
1. Unless https://github.com/RedHatInsights/insights-inventory-frontend/pull/2094 is merged, run this PR with it. In case, it is merged you do not have to run 2 PRs together.
2. Open a recommendation details page
3. Switch the tab to Immutable
4. Observe that table has now tags filter
5. Make sure that the filter works as expected

Enable tag filter

---

src/SmartComponents/HybridInventoryTabs/ImmutableDevices.js

Associated Jira ticket: # NO TICKET
This fixes the broken immutable devices tab on the Recommendation details page. The issue happens when you filter an already empty table and then click on the 'Reset filter' button. This was due to the fact that the `'filter[system_profile][host_type]': 'edge'` filter was placed inside a state. When the Reset button was clicked, that filter was gone and the API request brought incorrect data. Now, it is outside of useState, and thus API requests have this filter in place always.
1. Run the PR
2. Navigate to the Recommendation detail page that has no immutable devices (empty table)
3. Filter the table with Name fitler
4. Click on reset button
5. Observe that the table is not broken. (Make sure to repeat this multiple times)

fix(ImmutableDevices): pass edge filer into custom filter prop

---

src/SmartComponents/HybridInventoryTabs/ConventionalSystems/RecommendationSystems.js
src/SmartComponents/HybridInventoryTabs/ImmutableDevices.js
src/SmartComponents/HybridInventoryTabs/ImmutableDevices.test.js
src/SmartComponents/HybridInventoryTabs/helpers.js
src/SmartComponents/HybridInventoryTabs/helpers.test.js
src/SmartComponents/Recs/Details.js

Associated Jira ticket: # [(issue)](https://issues.redhat.com/browse/RHINENG-3414)
We need to enable recommendation disabling action in the recommendation details page Immutable devices tab. This action should work as it is in the conventional systems tab.
1. Open a recommendation that has an immutable device
2. Observe that now there is a table action in each row
3. Copy one of the device name in the first column
4. Try disabling the recommendation for one of them
5. Observe that the device you disabled does not exist in the table anymore by searching for your copied device name

feat(RHINENG-3414): enable recommendation disabling action in ImmutableDevices

---

src/Messages.js
src/SmartComponents/Systems/EdgeSystemsBanner.js
src/SmartComponents/Systems/EdgeSystemsBanner.test.js
src/SmartComponents/Systems/List.js
src/SmartComponents/Systems/__snapshots__/EdgeSystemsBanner.test.js.snap
src/Utilities/TestingUtilities.js

Associated Jira ticket: https://issues.redhat.com/browse/RHINENG-3076
Added banner to Advisor Systems table to indicate presence of edge systems
1. Open Advisor Systems table
2. There should be a banner when edge systems are present

feat(RHINENG-3076): Add banner for immutable systems

---

src/SmartComponents/HybridInventoryTabs/HybridInventoryTabs.js
src/SmartComponents/HybridInventoryTabs/HybridInventorytabs.test.js
src/SmartComponents/Recs/Details.js
src/SmartComponents/Recs/helpers.js
src/SmartComponents/Recs/helpers.test.js

This fixes the issue on HybridInventoryTabs. The issue happened by the fact that I understood the PM requirement wrong and made hybrid tabs switch to edge automatically when there are no conventional systems at a vulnerability account level. Instead, the correct behavior is the tabs auto-switching to the edge when there are no conventional systems affected by a CVE. Also, the tab should not auto-switch when there are no both conventional and edge devices.
1. Go Recommendations page
2. Find a recommendation that has only edge devices affected. For example: **Reboot will fail as the default initramfs file is not generated successfully**
3. Open details page
4. Observe that edge tab is automatically activated
5. Find another recommendation that has no …

fix(HybridInventoryTabs): auto switch to edge conditionally

---

src/SmartComponents/HybridInventoryTabs/fixtures/edgeData.json
src/SmartComponents/HybridInventoryTabs/fixtures/inventoryData.json
src/SmartComponents/HybridInventoryTabs/helpers.js
src/SmartComponents/HybridInventoryTabs/helpers.test.js

Implements: https://issues.redhat.com/browse/RHINENG-3415
According to the state of enforce_edge_group from /api/edge/v1/devices/devicesview endpoint, we should show groups info from edge endpoint inventory endpoint.
**When enforce_edge_group is set to true:**
groups column uses DeviceGroups from /api/edge/v1/devices/devicesview
**When enforce_edge_group is set to false:**
groups column uses groups from /api/insights/inventory/hosts

feat(RHINENG-3415): enforce edge groups conditionally

---

src/Messages.js
src/PresentationalComponents/ExecutiveReport/Download.js
src/PresentationalComponents/RulesTable/helpers.js

fixes the intl warning that was caused by passing incorrect message value. As we are migrating away intl, I tried to replace this intl message with plain text. However I have found out that advisor-components FEC package, heavily relies on intl and we need to allocate dedicated effort to remove intl from both advisor, advisor4openshift and adv-components 
1. Run the PR
2. Go to recommendations table
3. Observe that the warning is gone

fix(RuleDetails): pass correct argument to viewAffectedSystems to fix intl warning

---

src/Routes.js
src/SmartComponents/HybridInventoryTabs/ConventionalSystems/PathwaySystems.js
src/SmartComponents/HybridInventoryTabs/HybridInventoryTabs.js
src/SmartComponents/HybridInventoryTabs/HybridInventorytabs.test.js
src/SmartComponents/HybridInventoryTabs/ImmutableDevices.js
src/SmartComponents/HybridInventoryTabs/helpers.js
src/SmartComponents/HybridInventoryTabs/helpers.test.js
src/SmartComponents/Recs/Details.js
src/SmartComponents/Recs/DetailsPathways.js
src/SmartComponents/Recs/helpers.js
src/SmartComponents/Recs/helpers.test.js

Associated Jira ticket: # RHINENG-3070
This creates hybrid tabs for the pathways details page.
Acceptance criteria:
**Important: Immutable tab should behave as it is in recommendation detail page without table row actions**
1. Select the system number from a Pathway row on the main page and go to the Pathway details. If there are any conventional systems, land on details with Conventional systems in view ([Table](https://www.sketch.com/s/ac25729e-df9b-4e74-a09c-badb62787d24/a/ZVvo0ja#Inspect))
2. If ALL systems are Immutable, go to details with the Immutable tab in focus.
3. If there are NO immutable systems on the account, [Hide the tabs.](https://www.sketch.com/s/ac25729e-df9b-4e74-a09c-badb62787d24/a/kKdnAeg#Inspect)
4. Add tabs to the table if at least one Immutable system exists.
5. …

feat(RHINENG-3070): implement two tabs in pathway details page

---

src/PresentationalComponents/Inventory/Inventory.js
src/PresentationalComponents/Inventory/helpers.js
src/PresentationalComponents/SystemsTable/SystemsTable.js
src/PresentationalComponents/helper.js
src/PresentationalComponents/helper.test.js

https://issues.redhat.com/browse/RHINENG-5019
Adds the Group column to the RecommendationsSystems table and enables sorting on the OS column.  However sorting on Group column isn't enabled yet because the API doesn't support it yet.
Before PR (no group column and no sorting on OS): 
After PR:

feat(RHINENG-5019): Column modifications to RecommendationsSystems

---

config/dev.webpack.config.js
package-lock.json
package.json

This reverts commit 8c756ab9a3203fa35a0de8327668f56dc1338fc6.
This was an effort to unify the config with FEC, but FEC package version we want is far above the available release.
Currently with this removal of the deployment tag, this causes build issues in stage-beta env.

Revert "chore(fec): FEC package bump (#1207)"

---

src/SmartComponents/HybridInventoryTabs/helpers.js
src/SmartComponents/HybridInventoryTabs/helpers.test.js

This PR enables sorting OS column as the API now handles sorting on that column.
1. Go to the recommendations detail page of any recommendation
2. Sorty by OS columns
3. Observe that table is sorted correctly
4. Play with other columns so that we are sure there is no regression.

feat(ImmutableDevices): enable OS column sorting

---

src/SmartComponents/Recs/List.js
src/SmartComponents/Systems/List.js
src/SmartComponents/Topics/List.js

* This PR addresses the title changes, "Advisor titles should be presented without an 'Advisor' prefix"
* It also removes some use cases of `useIntl` that we are trying to remove from this project
Associated Jira ticket: [#RHINENG-5544](https://issues.redhat.com/browse/RHINENG-5544)
Checklist: 
Check the presented titles are shown without the "Advisor" prefix.
Recommendations Page:
Systems Page:
Topics Page:
Recommendations Page:
Systems Page:
Topics Page:

feat(RHINENG-5544): Remove Application Name Prefix From Titles

---

src/PresentationalComponents/Inventory/Inventory.js

https://issues.redhat.com/browse/RHINENG-5907
The toolbar kebab to disable rule(s) shouldn't be displayed for pathway systems because it doesn't make sense to disable individual pathway rules.  This simple PR / change removes the kebab when the inventory table shows pathway systems and displays it when they are individual rule systems.
Before PR - pressing the kebab leads to a 404:
After PR - kebab removed:

fix(RHINENG-5907): remove disable rule kebab for pathway systems

---

src/PresentationalComponents/Inventory/Inventory.js
src/SmartComponents/HybridInventoryTabs/helpers.js
src/SmartComponents/HybridInventoryTabs/helpers.test.js

Adds sorting to the groups column in the Recommendations Systems / Inventory table
Continuation of the work for https://issues.redhat.com/browse/RHINENG-5019
After adding Group sorting:

fix(RHINENG-5019): enable sorting on recs systems group column

---

src/SmartComponents/SystemAdvisor/SystemAdvisor.js

This just hides remediation button while systems_profile is being fetched from the API. This will prevent the button from being shown for a short time which decreases user experience when an immutable system is being looked at. 
Run this PR with the inventory app
1. Go to the inventory landing page and open the Immutable tab
2. Click on any immutable tab to go to the detail page
3. Open the advisor tab
4. Observe that there is no Remediate button in the table toolbar at all even while the API call is in progress
5. Navigate back to the inventory landing page, conventional tab
6. Click on any conventional system to go to the detail page
7. Open the advisor tab
7. Observe that there is a remediate button

chore(SystemsAdvisor): do not show remediation button whil systems_pr

---

src/PresentationalComponents/Inventory/Inventory.js
src/PresentationalComponents/SystemsTable/SystemsTableAssets.js

Removes the extra icon on initial table load in inventory pages by removing sortable table transformer. The table columns are by default made sortable in inventory module and advisor should not another transformer that is causing the extra icon. 

fix(Inventory): remove extra sorting icon on inventory tables

---

src/PresentationalComponents/ExecutiveReport/Download.js

…DownloadButton
Fixes broken executive report downloading by changing DownloadButtonWrapper component to DownloadButton. With this we are not explicitly loading `esm` module by using relative imports

fix(RHINENG-6162): change DownloadButtonWrapper to DownloadButton component

---

src/PresentationalComponents/Inventory/Inventory.js

https://issues.redhat.com/browse/RHINENG-5019
Adds filtering by group to the Recommendations Systems table.  The API supports filtering on group.
Before the change ...
After the change ...

fix(RHINENG-5019): enable group filtering on recs systems

---

src/PresentationalComponents/Breadcrumbs/Breadcrumbs.js
src/SmartComponents/Recs/List.js

* This PR addresses the breadcrumbs issue that is mentioned on the ticket
* Also, removes a use of `useIntl` that we are trying to remove from this app
Associated Jira ticket: [#RHINENG-5544](https://issues.redhat.com/browse/RHINENG-5544)
Ensure the breadcrumbs does not show the app name
Recommendations:
Systems:
Topics: 
Recommendations:
Systems:
Topics:

feat(RHINENG-5544): Remove Prefix From Breadcrumbs

---

src/AppConstants.js
src/PresentationalComponents/Cards/OverviewDashbarCard/__tests__/DashbarCardTitle.test.js
src/PresentationalComponents/OverviewDashbar/__tests__/OverviewDashbar.test.js

This PR addresses the title capitalization problem mentioned in the issue
Associated Jira ticket: [#RHINENG-6294](https://issues.redhat.com/browse/RHINENG-6294)
Ensure the titles of 'Important recommendations' & 'Critical recommendations' appear in the UI like written here

Bug(RHINENG-6294): OverviewDashbar Card Titles Capitalization Correction

---

src/Services/Acks.js
src/Services/Recs.js
src/SmartComponents/Recs/Details.js
src/SmartComponents/Recs/helpers.js

This PR URL encodes RHEL Advisor recommendation / rule id values whenever they are sent to the backend so the request may pass through environments enforcing strict HTTP standards (eg not allowing the pipe character "|" in URLs)
This came from a Slack discussion and I'm not sure if a Jira has been created.
Before the change, the pipe character is sent in URLs unencoded:
After the change, the pipe character is encoded:

fix: URL encode the pipe character in rule ids

---

src/AppConstants.js
src/PresentationalComponents/Common/Tables.js
src/PresentationalComponents/Filters/GeneralFilterTypes/CheckboxFilter.js
src/PresentationalComponents/Filters/impactingFilter.js
src/PresentationalComponents/RulesTable/RulesTable.cy.js
src/PresentationalComponents/RulesTable/RulesTable.js
src/PresentationalComponents/RulesTable/helpers.js
src/PresentationalComponents/RulesTable/useActionsResolver.js
src/SmartComponents/Recs/Details.js

…o maintain
Associated Jira ticket: RHINENG-3078
This PR extends the systems impacted filter in advisor to include the new options dnfyum, ostree for only accounts with edge systems. For the rest of the users, behavior should stay the same. After trying out a bunch of approaches, I decided to have simple if else conditions to map the filter values to the complex API spec in `mapUpdateMethodFilterToAPISpec` func.
API filter syntax [(RHINENG-5353)](https://issues.redhat.com/browse/RHINENG-5353)
- All rules: no query parameter
- No impacted systems: impacting=false.
- Only conventional systems: impacting=true&update_method=dnfyum.
- Only immutable systems: impacting=true&update_method=ostree.
- Any system: impacting=true.
I wrote new tests to cover the work, but I had to comment them out as …

feat(RHINENG-3078): extend systems filter with new hybrid options

---

src/PresentationalComponents/RulesTable/helpers.js

[RHINENG-8777](https://issues.redhat.com/browse/RHINENG-8777)
Not all parameters were set
How to test: 
1. Advisor > Recommendations
2. Find the Total risk filter
3. Click on Critical to check it
4. Try to uncheck it
5. It should remove the filter

fix(RHINENG-8777): unable to unselect total risk in recommendations

---

package-lock.json
src/PresentationalComponents/RulesTable/RulesTable.js
src/SmartComponents/Recs/DetailsPathways.js

https://issues.redhat.com/browse/RHINENG-9594
When selecting a pathway, the rules table component displays all rules regardless of whether they are associated with the selected pathway or not.
- Log into console.stage.redhat.com
- Go to the Insights -> Operations -> Advisor
- Select the '5' under Pathways - this lists the pathways.
- Choose one of the pathways - e.g. 'Update Kernel Boot Options'.
... all rules matching the filter conditions are displayed, not just the rules for 'Update Kernel Boot Options'

fix(RHINENG-9594): Only retrieve/display recs for the chosen pathway

---

src/PresentationalComponents/Inventory/Inventory.js
src/SmartComponents/SystemAdvisor/SystemAdvisorAssets.js

https://issues.redhat.com/browse/RHINENG-5291
System detail page table rule names are now links.
a. Advisor
1. Go to System detail page
2. Click on any recommendation link
3. It should take you to the detail view of that recommendation
b. Inventory
1. Go to System detail page
2. Click on any recommendation link
3. It should take you to the Advisor app detail view of that recommendation

RHINENG-5291 Link from System detail page to Recommendation detail page

---

src/PresentationalComponents/Inventory/Inventory.js
src/Utilities/Hooks.js

[RHINENG-10414](https://issues.redhat.com/browse/RHINENG-10414) 
In advisor the only instance of workspaces is in the inventory table. This changes that instance when the feature flag is enabled. 
Once the backend PR is merged, I can send up another PR that I have stashed locally :) 
Navigate to systems pages (or any page with the groups column) and verify it says Workspace and opposed to groups.

feat(RHINENG-10414): workspaces feature flag

---

src/PresentationalComponents/Modals/DisableRule.js

Recently we had a customer entering a value into the justification field that was longer than the max length of the field, and it had us scratching our heads for a while trying to figure out what the problem was.  We have increased the size of the field in the backend in https://gitlab.cee.redhat.com/insights-platform/advisor-backend/-/merge_requests/887 but we also think we should limit the UI text input to the same max length, to make it harder for customers to 'do the wrong thing'.  This is a simplistic solution and can easily be defeated by determined customers, but its a low-hanging fruit solution to the problem, so I'm going with it.

fix(RHINENG-10409): Limit justification to backend max length

---

src/PresentationalComponents/Inventory/Inventory.js

Associated Jira ticket: https://issues.redhat.com/browse/RHINENG-10414
Small fix where we use singular form instead of plural for consistency between apps
Ensure that Recommendations details page has "Group"/"Workspace" column. Note that This is the only one place where naming form appeared, other tables are coming from inventory

fix(RHINENG-10414): use singular form Group/Workspace

---

src/ZeroStateWrapper.js
src/ZeroStateWrapper.test.js

Associated Jira ticket: # [RHINENG-10312](https://issues.redhat.com/browse/RHINENG-10312)
Don't show ZeroState while data are still loading - also fixes persisting Global Filters from Dashboard
1. Go to Dashboard application
2. Apply global filter
3. Use any link in Advisor card to go to Advisor application
4. The Global filters should be applied

fix(ZeroStateWrapper): RHINENG-10312 dont show ZeroState on data loading

---

src/PresentationalComponents/helper.js

The API doesn't accept the incident parameter having both true and false values at the same time, eg incident=true&incident=false.  The API will return a 400 BadRequest if it does which will cause an error in the frontend.  The PR prevents the frontend from sending multiple values for the incident parameter to the API.

fix(RHINENG-11227): Prevent sending both true and false for incident filter

---

package-lock.json
src/PresentationalComponents/Labels/CategoryLabel.js
src/PresentationalComponents/Labels/RecommendationLevel.js
src/PresentationalComponents/Labels/RuleLabels.js
src/PresentationalComponents/MessageState/MessageState.js
src/PresentationalComponents/Modals/DisableRule.js
src/PresentationalComponents/Modals/ViewHostAcks.js

Fix the following error which was printed into console when running Jest tests:
> Warning: MessageState: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

Remove deprecated Component.defaultProps

---

fec.config.js
package.json

This just updates advisors sentry set up to use the new architecture

feat(RHINENG-14070): Add sentry moduleMetadata

---

.github/workflows/webpack.yml

This changes to sentry hook, to work more as a button. A manual job with an input, being the commit hash, that will upload source maps with that specific build

Update sentry webhook

---

fec.config.js

We need to inject Debug IDs every time. Otherwise, some errors get 'lost' in sentry

chore(sentry): Add debug ids on every build

---

.github/workflows/webpack.yml

Adding this release variable is overriding the default behavior from chrome.

Update sentry workflow to remove release var

---

.github/workflows/webpack.yml
fec.config.js

This also removes the issue where the plugin is initialized locally and sends up debugIDs for local env on every build
**Workflow Behavior:**
**Locally (without variables):**
The Sentry plugin won't build as SENTRY_AUTH_TOKEN is not defined.
**GitHub push to master (automatic trigger):**
The plugin won't include the authToken because commit_hash is not provided in push events.
**Manually triggered with commit_hash:**
The plugin includes the authToken and tracks the build with Sentry.

fix(sentry): Update Sentry Flow

---

.github/workflows/webpack.yml
fec.config.js

In the case the variable is false, this will ensure we dont break any schemas.
If triggered on push we build without authToken, and we trigger it via workflow we send up the authToken

fix(sentry): Syntax and sentry workflow var updates

---

cypress/support/globals.js
package-lock.json
package.json
src/PresentationalComponents/Inventory/InventoryDetails.js
src/PresentationalComponents/PathwaysTable/PathwaysTable.cy.js
src/PresentationalComponents/PathwaysTable/PathwaysTable.js
src/PresentationalComponents/RulesTable/RulesTable.cy.js
src/PresentationalComponents/RulesTable/RulesTable.js
src/PresentationalComponents/TopicsTable/TopicsTable.js
src/SmartComponents/HybridInventoryTabs/HybridInventoryTabs.js
src/SmartComponents/Recs/List.js
src/SmartComponents/SystemAdvisor/SystemAdvisor.js

Fix loading states across app to better reflect loading components
Associated Jira ticket: [RHINENG-11976](https://issues.redhat.com/browse/RHINENG-11976)
Affected pages:
`/recommendations` - Pathways tab
`/recommendation/:id` - loading spinner while the tables in the tabs are loading
`/topics` - table
`/topics/:id` - rules table
`/systems/:id` - header, table

fix(RHINENG-11976): fix loading states across app

---

cypress/rulestablesconsts.js
cypress/utils/table.js
deploy/frontend.yaml
package-lock.json
package.json
src/AppConstants.js
src/PresentationalComponents/PathwaysTable/PathwaysTable.js
src/PresentationalComponents/RulesTable/RulesTable.cy.js
src/PresentationalComponents/RulesTable/helpers.js
src/SmartComponents/HybridInventoryTabs/HybridInventoryTabs.js
src/SmartComponents/HybridInventoryTabs/ImmutableDevices.js
src/SmartComponents/HybridInventoryTabs/ImmutableDevices.test.js
src/ZeroStateWrapper.js

FEC packages had to be updated
Associated Jira ticket: [RHINENG-13681](https://issues.redhat.com/browse/RHINENG-13681)
Change Status filter to use new "Single select" filter type instead of radio selection
Keys had to be removed as part of the package upgrade
FEC packages were upgraded, so go through the app to see if anything broke
eg I had to remove `key`s from filters so the filters would work
Select the Status filter, and open the "Filter by status" filter dropdown. 
New filter type as shown below should be visible
Select the Status filter, and open the "Filter by status" filter dropdown. 
New filter type as shown below should be visible

feat(RHINENG-13681): status filter to single select type & bump fec

---

.gitignore
.travis.yml
config/cypress.webpack.config.js
coverage.sh
package-lock.json
package.json

Fix code coverage scripts and collection so that we have a cypress report generated for codecov.
Review steps:
- npm i
- npm run travis:verify
- check that the coverage-cypress/lcov.info is not empty
- check that the coverage-jest/lcov.info is not empty
- check that .nyc_output/out.json is not empty

Fix cypress test collection

---

package-lock.json
src/AppConstants.js
src/PresentationalComponents/ExecutiveReport/BuildExecReport.js
src/PresentationalComponents/ExecutiveReport/Download.js
src/PresentationalComponents/ExecutiveReport/NewBuildExecReport.js
src/PresentationalComponents/ExecutiveReport/NewDownload.js
src/PresentationalComponents/ExecutiveReport/RecommendationCharts.js

This PR updates the template for the Executive Report PDF. To test:
- navigate to Advisor -> Recommendations
- click "Download executive report"
This should render a PDF that looks similar to the previous PDF in layout, but different in design. The data should be the same as the previous PDF.
This feature should be hidden behind a feature flag.

feat(RHINENG-3020): Update Exec Report Template

---

src/Messages.js
src/PresentationalComponents/RulesTable/RulesTable.js
src/PresentationalComponents/RulesTable/helpers.js

As discovered in https://issues.redhat.com/browse/RHINENG-17315, when filtering disabled rules, the impacting=false URL parameter was being applied unnecessarily and causing the results to be incorrect.  The Advisor API backend has recently changed how it displays disabled rules, removing the need for impacting=false.
Also, Red Hat disabled rules should show how many systems are being impacted, so I removed the N/A string and tooltip and directly show how many systems are affected.  As per the attached screenshots.

fix(RHINENG-17315): Show disabled recommendations and systems counts

---

src/PresentationalComponents/RulesTable/helpers.js
src/SmartComponents/Recs/Details.js

As reported in RHINENG-17352, the justification note was not being displayed for disabled rules.  I'm not sure why Muslimjon changed the RecAckQuery like he did, but basically I rolled back his changes to it and it works again now.
I also piggybacked another change in that systems for disabled rules are not displayed, so I removed the link to the systems for a disabled rules, because there are no systems to see anyway for the disabled rule.

fix(RHINENG-17352): Show justification note for disabled rules

---

fec.config.js
src/Temporary/SatelliteDemoComponent.js

Adding temp satellite component as per request from Satellite team
Example of the same thing for vuln ui
https://github.com/RedHatInsights/vulnerability-ui/commit/fedd803623a5646be4bb3dee0fb8a144db303571

feat(iop): add temporary satellite component

---

fec.config.js
src/SmartComponents/Recs/RecommendationDetailsWrapped.js

RecsDetailsWrapper is called RecommendationDetailsWrapper on the Satellite and this seems like a better name than RecsDetailsWrapper anyway.

fix(RHINENG-19351): Rename recs wrapper to match Satellite

---

src/PresentationalComponents/ExecutiveReport/Download.js
src/PresentationalComponents/Export/SystemsPdf.js
src/PresentationalComponents/SystemsTable/SystemsTable.test.js

Oops, missed renaming the federated modules within the code, so the PDF couldn't be generated.

fix(RHINENG-19582): Missed some renamings for new PDF generator

---

src/Modules/SystemDetailWrapped.js
src/SmartComponents/SystemAdvisor/SystemAdvisorWrapped.js

Populates the Insights tab for the Satellite IoP environment

fix(RHINENG-19383): Host Insights tab populates in IoP environment

---

src/PresentationalComponents/Inventory/Inventory.js

The Tags and Workspaces filters were accidentally disabled in all the IOP shenanigans.  Stuff happens.
Showing the filters enabled again:

fix(RHINENG-19874): Enable Tags/Workspace filters accidentally disabled

---

src/AppConstants.js
src/Utilities/DownloadPlaybookButton.cy.js
src/Utilities/DownloadPlaybookButton.js

The download playbook button needs a couple of changes for it to work:
* API path needs to be prefixed with /insights_cloud
* the headers need to include the CSRF token

fix(RHINENG-19960): DownloadPlaybookButton API path and CSRF header

---

renovate.json

Currently, mintmaker will try to update all onboarded components but this is unnecessary for SC branches and just clutters the repo PR list. Only allowing renovate to run on main/master should help.

chore: configure renovate to only run on master branch

---

src/SmartComponents/HybridInventoryTabs/helpers.js
src/SmartComponents/HybridInventoryTabs/helpers.test.js

The Immutable systems tab has 2 Last seen columns because I failed to removed the original Last seen column which was incorrectly based on the 'updated' attribute
Before fix there are 2 Last seen columns:
After fix there is just one (the correct one!):

fix(RHINENG-20343): Remove updated column from immutable table

---

src/SmartComponents/Recs/ListWrapped.js

Associated Jira ticket: SAT-38669
This PR fixes an issue In Satellite with IoP:
1.) Click on Recommendations in the navigation menu. Wait for the page to load.
2.) Click on Recommendations a second time. The Recommendations table refreshes but hangs in a loading "skeleton" state.
The problem is in the `ListWrapped` component, which is what Satellite / foreman_rh_cloud imports and renders. `ListWrapped` was re-initializing its Redux store each time it was rendered. This PR fixes the issue by moving the store creation out of the component, so that it's only initialized once. With this fix in place, the page does not reload at all when clicking "Recommendations" a second time, which is the expected behavior (and matches the behavior of the "Vulnerability" page).

fix(SAT-38669): Fix store creation in ListWrapped component

---

src/PresentationalComponents/Cards/OverviewDashbarCard/OverviewDashbarCard.js
src/PresentationalComponents/Cards/ResolutionCard.js
src/PresentationalComponents/Cards/TotalRiskCard.js
src/PresentationalComponents/ExecutiveReport/RecommendationCharts.js
src/PresentationalComponents/Export/TablePage.js
src/PresentationalComponents/Inventory/Inventory.js
src/PresentationalComponents/Loading/Failed.js
src/PresentationalComponents/Loading/Loading.js
src/PresentationalComponents/Modals/ViewHostAcks.js
src/PresentationalComponents/PathwaysTable/PathwaysTable.js
src/PresentationalComponents/RulesTable/RulesTable.cy.js
src/PresentationalComponents/RulesTable/RulesTable.js
src/PresentationalComponents/TopicsAdminTable/TopicsAdminTable.js
src/PresentationalComponents/TopicsTable/TopicsTable.js
src/SmartComponents/Recs/Details.js
src/SmartComponents/Recs/IopRecommendationDetails.js
src/SmartComponents/SystemAdvisor/SystemAdvisor.cy.js
src/SmartComponents/SystemAdvisor/SystemAdvisor.js
src/Utilities/DownloadPlaybookButton.js

Adds data-ouia-component-id values for components that I can, esp Table & Card patternfly components.  However for components from RedHatInsights/frontend-components, most don't take an ouiaId prop so I can't pass an ouiaId value to them.

fix(RHINENG-20837): Add OUIA-ID to components, esp for IOP
